/* ============================================================
   BANCO DE CATEGORIAS - Bomba-Relógio Etílica
   ------------------------------------------------------------
   Para adicionar/remover categorias, basta editar as listas
   dentro de cada grupo abaixo. Cada grupo pode ser ligado ou
   desligado mudando "ativo: true" para "ativo: false".

   Como funciona:
   - Cada grupo tem um "nome", um "emoji" e uma lista "itens".
   - O jogo junta automaticamente todos os grupos com ativo: true.
   ============================================================ */

const GRUPOS_CATEGORIAS = [
    {
        nome: "Bebida & Balada",
        emoji: "🍺",
        ativo: true,
        itens: [
            "Marcas de Cerveja",
            "Tipos de Drinks / Coquetéis",
            "Coisas que dão ressaca",
            "Mentiras que se fala na balada",
            "Marcas de Vodka ou Whisky",
            "Motivos para você já estar bêbado",
            "Coisas que rolam num after",
            "Sabores de energético",
            "Frases de quem bebeu demais",
            "Marcas de Cachaça",
            "Marcas de Gin",
            "Marcas de Tequila",
            "Baladas ou casas noturnas famosas",
            "DJs famosos",
            "Coisas que você faz bêbado e se arrepende depois",
            "Desculpas para beber \"só mais um\"",
            "Jogos de bebida conhecidos",
            "Coisas que rolam numa pré-balada",
            "Frases que todo barman já ouviu",
            "Coisas que somem na balada (celular, chinelo, dignidade...)",
            "Coisas que tem numa festa open bar",
            "Marcas de cerveja artesanal",
            "Combinações de bebida que dão ruim",
            "Coisas que rolam no Carnaval",
            "Coisas que tem em todo boteco",
            "Tipos de festa (aniversário, formatura, casamento...)",
            "Coisas que você leva pra balada",
            "Motivos para sair mais cedo da festa",
            "Bebidas doces",
            "Bebidas fortes demais",
            "Marcas de espumante ou champagne",
            "Brindes que se ganha em bar",
            "Tipos de copo ou taça",
            "Coisas que caem no chão de balada",
            "Peças de roupa de balada",
            "Coisas que se esquece na balada",
            "Sinais de que a festa já era",
            "Coisas que rolam numa comemoração de gol",
            "Nomes criativos pra festa de amigos",
            "Marcas de rum",
            "Drinks tropicais",
            "Coisas que rolam num réveillon",
            "Desculpas pra não pagar a rodada",
            "Coisas que se fala pro motorista de app não cancelar",
            "Sinais de que alguém bebeu demais",
            "Tipos de festa universitária (república, calourada...)",
            "Coisas que tem numa adega",
            "Marcas de licor",
            "Bebidas sem álcool que imitam drinks",
            "Coisas que você grita pro DJ tocar"
        ]
    },
    {
        nome: "Cultura Pop & TV",
        emoji: "🎬",
        ativo: true,
        itens: [
            "Séries da Netflix",
            "Heróis da Marvel ou DC",
            "Filmes de terror",
            "Desenhos animados antigos",
            "Personagens da Disney",
            "Realities da TV brasileira",
            "Novelas famosas",
            "Vilões de filme",
            "Franquias de cinema",
            "Programas de auditório",
            "Filmes de comédia",
            "Filmes de ação",
            "Atores ou atrizes brasileiros",
            "Atores ou atrizes de Hollywood",
            "Animes famosos",
            "Personagens de desenho japonês",
            "Youtubers brasileiros",
            "Influenciadores digitais",
            "Memes que marcaram época",
            "Séries antigas de TV aberta",
            "Filmes da Pixar",
            "Filmes de super-herói",
            "Trilhas sonoras de filme",
            "Diretores de cinema famosos",
            "Personagens de video game",
            "Video games famosos",
            "Franquias de games",
            "Apresentadores de TV brasileira",
            "Humoristas brasileiros",
            "Podcasts famosos",
            "Filmes premiados no Oscar",
            "Personagens de sitcom",
            "Séries policiais",
            "Séries de época",
            "Filmes de ficção científica",
            "Vilões de desenho animado",
            "Musicais famosos",
            "Reality shows internacionais",
            "Talk shows brasileiros",
            "Apresentadores de jornal",
            "Personagens de novela mexicana",
            "Filmes cult",
            "Séries derivadas (spin-off)",
            "Frases marcantes de filme",
            "Curiosidades sobre celebridades",
            "Casais famosos de Hollywood",
            "Escândalos de famosos",
            "Streamers famosos",
            "Canais de TV brasileiros",
            "Filmes baseados em livros"
        ]
    },
    {
        nome: "Música",
        emoji: "🎵",
        ativo: true,
        itens: [
            "Cantores ou bandas de Axé/Pagode dos anos 90",
            "Bandas de Rock Nacional",
            "Cantores de Sertanejo",
            "Músicas de Funk",
            "Bandas internacionais",
            "Cantores de MPB",
            "Hits do verão",
            "Músicas que tocam em casamento",
            "Rappers brasileiros",
            "Duplas sertanejas",
            "Cantoras brasileiras",
            "Bandas de Pagode",
            "Cantores de Forró",
            "Bandas de Reggae",
            "DJs de música eletrônica",
            "Bandas de Rock internacional",
            "Cantores de Trap",
            "Músicas de paredão",
            "Músicas de academia",
            "Cantores dos anos 2000",
            "Músicas que tocam em churrasco",
            "Cantoras pop internacionais",
            "Hinos de torcida de futebol",
            "Cantores de Piseiro",
            "Músicas que todo mundo sabe cantar",
            "Bandas ou cantores dos anos 80",
            "Cantores de Bossa Nova",
            "Playlists de festa (o que não pode faltar)",
            "Cantoras de MPB",
            "Músicas de Carnaval",
            "Cantores latinos",
            "Instrumentos musicais",
            "Músicas que marcaram sua adolescência",
        ]
    },
    {
        nome: "Comida & Bebida",
        emoji: "🍕",
        ativo: true,
        itens: [
            "Sabores de pizza",
            "Comidas de boteco",
            "Frutas",
            "Doces de festa junina",
            "Marcas de salgadinho",
            "Comidas que dão gases",
            "Recheios de coxinha (ou pastel)",
            "Comidas típicas do Nordeste",
            "Coisas que se come no café da manhã",
            "Sabores de sorvete",
            "Marcas de refrigerante",
            "Doces brasileiros",
            "Comidas de churrasco",
            "Tipos de queijo",
            "Comidas japonesas",
            "Comidas italianas",
            "Comidas mexicanas",
            "Marcas de chocolate",
            "Temperos ou condimentos",
            "Comidas que combinam com cerveja",
            "Frutas tropicais",
            "Legumes",
            "Verduras",
            "Comidas de padaria",
            "Sabores de bolo",
            "Comidas que engordam só de olhar",
            "Comidas fit",
            "Pratos típicos de Minas Gerais",
            "Pratos típicos da Bahia",
            "Comidas de rodízio",
            "Tipos de massa (macarrão)",
            "Comidas de festa infantil",
            "Marcas de biscoito",
            "Comidas veganas ou vegetarianas",
            "Bebidas quentes (café, chá...)",
            "Sucos naturais",
            "Comidas apimentadas",
            "Comidas que ninguém admite gostar",
            "Marcas de fast food",
            "Ingredientes de hambúrguer",
            "Comidas de food truck",
            "Sobremesas clássicas",
            "Comidas árabes",
            "Comidas chinesas",
            "Comidas que dão azia",
            "Tira-gosto de bar",
            "Comidas de Ano Novo",
            "Comidas de festa de aniversário",
            "Comidas que se come com a mão",
            "Comidas que lembram infância"
        ]
    },
    {
        nome: "Geografia & Mundo",
        emoji: "🌎",
        ativo: true,
        itens: [
            "Países que começam com a letra 'A'",
            "Capitais do Brasil",
            "Estados brasileiros",
            "Pontos turísticos famosos",
            "Praias do Brasil",
            "Cidades que você quer conhecer",
            "Países da Europa",
            "Rios ou lagos famosos",
            "Países da América do Sul",
            "Países da África",
            "Países da Ásia",
            "Capitais da Europa",
            "Capitais da América do Sul",
            "Ilhas famosas",
            "Montanhas famosas",
            "Desertos famosos",
            "Línguas faladas no mundo",
            "Bairros do Rio de Janeiro",
            "Bairros de São Paulo",
            "Cidades do Nordeste",
            "Cidades do Sul do Brasil",
            "Pontos turísticos do Brasil",
            "Maravilhas do mundo",
            "Países que fazem fronteira com o Brasil",
            "Moedas de outros países",
            "Países que falam espanhol",
            "Cidades famosas por Carnaval",
            "Praias famosas do mundo",
            "Vulcões famosos",
            "Parques nacionais brasileiros",
            "Continentes",
            "Países pequenos e curiosos",
            "Cidades europeias famosas",
            "Cidades americanas famosas",
            "Regiões do Brasil",
            "Países de clima tropical",
            "Países de clima frio",
            "Bandeiras de países",
            "Comidas típicas de outros países",
            "Países que já sediaram Copa do Mundo",
            "Países que já sediaram Olimpíadas",
            "Rios do Brasil",
            "Cidades litorâneas",
            "Serras ou montanhas do Brasil",
            "Países que você quer visitar antes de morrer",
            "Lugares assombrados famosos",
            "Fusos horários / lugares distantes",
            "Cidades gêmeas ou irmãs",
            "Pontos turísticos de São Paulo",
            "Capitais da Ásia"
        ]
    },
    {
        nome: "Esportes",
        emoji: "⚽",
        ativo: true,
        itens: [
            "Times que já foram rebaixados no Brasileirão",
            "Jogadores de futebol famosos",
            "Esportes olímpicos",
            "Times de futebol europeus",
            "Coisas que um juiz faz",
            "Modalidades de luta",
            "Seleções que já ganharam a Copa",
            "Times brasileiros de futebol",
            "Técnicos de futebol famosos",
            "Jogadoras de futebol feminino",
            "Esportes que usam bola",
            "Esportes que usam raquete",
            "Esportes radicais",
            "Atletas olímpicos brasileiros",
            "Modalidades de atletismo",
            "Craques do passado",
            "Copas do Mundo memoráveis",
            "Times de basquete famosos",
            "Jogadores de basquete famosos (NBA)",
            "Regras esquisitas de algum esporte",
            "Coisas que acontecem num estádio de futebol",
            "Cânticos de torcida",
            "Esportes coletivos",
            "Esportes individuais",
            "Grandes rivalidades esportivas",
            "Comentaristas esportivos famosos",
            "Marcas de material esportivo",
            "Posições em um time de futebol",
            "Faltas ou cartões no futebol",
            "Esportes com bola pequena",
            "Lutadores de UFC famosos",
            "Jogadores de vôlei famosos",
            "Modalidades paralímpicas",
            "Esportes de inverno",
            "Esportes aquáticos",
            "Grandes campeões do tênis",
            "Pilotos de Fórmula 1",
            "Categorias de peso no boxe",
            "Coisas que rolam numa Copa do Mundo",
            "Mascotes de times de futebol",
            "Apelidos de jogadores famosos",
            "Estádios de futebol famosos",
            "Coisas que um torcedor fanático faz",
            "Esportes olímpicos de verão",
            "Modalidades de ginástica",
            "Esportes jogados na praia",
            "Grandes zagueiros ou goleiros",
            "Coisas que irritam um árbitro",
            "Competições de futebol (Libertadores, Champions...)",
            "Jogadores que já jogaram no exterior"
        ]
    },
    {
        nome: "Adulto & Picante",
        emoji: "🔥",
        ativo: true,
        itens: [
            "Palavrões ou Xingamentos",
            "Coisas que você encontra num motel",
            "Motivos para terminar um namoro",
            "Cantadas ruins",
            "Apelidos carinhosos para o crush",
            "Coisas que se fala no primeiro encontro",
            "Fetiches (sem julgamento!)",
            "Desculpas depois da traição",
            "Partes do corpo",
            "Coisas que você faz pra dar em cima de alguém",
            "Sinais de que alguém está a fim de você",
            "Red flags em um relacionamento",
            "Green flags em um relacionamento",
            "Coisas que rolam numa DR (briga de casal)",
            "Apps de relacionamento",
            "Coisas que rolam num date pelo Tinder",
            "Mentiras que se conta pra ficar com alguém",
            "Frases de conquista clássicas (cantadas)",
            "Coisas que se fala bêbado pro ex",
            "Motivos pra ligar pro ex de madrugada",
            "Lugares inusitados pra ficar com alguém",
            "Coisas que deixam qualquer um sem graça",
            "Perguntas que ninguém deveria fazer num encontro",
            "Coisas que rolam numa despedida de solteiro(a)",
            "Sinais de ciúmes",
            "Apelidos picantes",
            "Coisas que você esconde do crush",
            "Desculpas para não responder mensagem de quem está afim de você",
            "Coisas que rolam numa festa universitária picante",
            "Roupas íntimas",
            "Coisas que rolam quando alguém fica com ciúme",
            "Frases que se ouve numa balada de pegação",
            "Motivos para dar um fora em alguém",
            "Coisas que rolam num jogo de \"verdade ou desafio\"",
            "Apelidos que se dá pra partes do corpo",
            "Coisas que rolam numa lua de mel",
            "Sinais de paquera à distância",
            "Coisas que se fala pra terminar sem magoar",
            "Frases que estragam um clima romântico",
            "Coisas que rolam numa festa a fantasia sensual",
            "Motivos pra ficar com o ex de novo",
            "Coisas que você faz pra parecer interessante num encontro",
            "Sinais de que o crush te dá \"match\"",
            "Coisas que rolam num flerte no trabalho",
            "Presentes que se dá pro crush",
            "Coisas que se fala na hora do \"e agora, somos namorados?\"",
            "Coisas que rolam numa viagem romântica",
            "Apelidos vergonhosos que casais usam",
            "Coisas que acontecem numa balada de solteiros",
            "Motivos pra terminar um caso"
        ]
    },
    {
        nome: "Dia a Dia",
        emoji: "🏠",
        ativo: true,
        itens: [
            "Desculpas para faltar ao trabalho",
            "Nomes de cachorro cafonas",
            "Aplicativos que você tem no celular",
            "Coisas que você esquece de fazer",
            "Objetos que existem numa cozinha",
            "Profissões",
            "Coisas que dão na sua avó de presente",
            "Marcas de carro",
            "Coisas que juntam sujeira em casa",
            "Coisas que tem numa bolsa de mulher",
            "Coisas que tem no bolso de um homem",
            "Desculpas para chegar atrasado",
            "Coisas que você faz quando está entediado",
            "Objetos que existem num quarto",
            "Objetos que existem num banheiro",
            "Coisas que a mãe sempre fala",
            "Coisas que o pai sempre fala",
            "Coisas que se compra no supermercado",
            "Marcas de eletrodoméstico",
            "Coisas que você faz antes de dormir",
            "Coisas que você faz assim que acorda",
            "Apps que todo mundo tem no celular",
            "Coisas que estragam o dia de qualquer um",
            "Sinais de que você está ficando velho",
            "Coisas que você fazia quando era criança",
            "Coisas que irritam no transporte público",
            "Coisas que irritam no trânsito",
            "Profissões que exigem coragem",
            "Coisas que tem numa sala de aula",
            "Coisas que tem num escritório",
            "Desculpas para não ir à academia",
            "Coisas que se leva numa viagem",
            "Coisas que você faz quando fica sem internet",
            "Coisas que fazem barulho à noite",
            "Coisas que dão trabalho de limpar",
            "Coisas que você faz procrastinando",
            "Marcas de roupa",
            "Sinais de que alguém é folgado(a)",
            "Coisas que sua vó guarda \"porque pode ser útil\"",
            "Coisas que você faz escondido dos pais",
            "Coisas que se perde com frequência",
            "Coisas que fazem você se sentir adulto",
            "Coisas que te fazem sentir criança de novo",
            "Sinais de que você está com sono no trabalho",
            "Coisas que tem numa festa de aniversário infantil",
            "Objetos que toda casa tem, mas ninguém usa",
            "Coisas que se faz num domingo à tarde",
            "Coisas que fazem uma segunda-feira ruim",
            "Coisas que se compra e nunca usa",
            "Sinais de que é hora de trocar de emprego"
        ]
    },
    {
        nome: "Aleatório & Divertido",
        emoji: "🎲",
        ativo: true,
        itens: [
            "Coisas verdes",
            "Coisas redondas",
            "Coisas que voam",
            "Super-poderes que você queria ter",
            "Coisas que assustam",
            "Animais perigosos",
            "Coisas que existem no céu",
            "Palavras que rimam com 'amor'",
            "Coisas frias",
            "Coisas amarelas",
            "Coisas vermelhas",
            "Coisas pretas",
            "Coisas que fazem barulho",
            "Coisas pontudas",
            "Coisas fofas",
            "Coisas nojentas",
            "Coisas que dá pra encontrar numa praia",
            "Coisas que existem numa floresta",
            "Coisas que existem no espaço",
            "Super-heróis inventados na hora",
            "Animais que vivem na água",
            "Animais de estimação",
            "Coisas que brilham no escuro",
            "Coisas que fazem cócegas",
            "Palavras que rimam com 'festa'",
            "Palavras que rimam com 'copo'",
            "Coisas que pesam muito",
            "Coisas bem pequenas",
            "Coisas gigantes",
            "Coisas que dão sorte",
            "Coisas que dão azar",
            "Superstições brasileiras",
            "Coisas que só existem no Brasil",
            "Coisas que toda casa de avó tem",
            "Coisas que fazem alguém rir sem parar",
            "Poderes de super-vilão",
            "Criaturas do folclore brasileiro",
            "Coisas que você acha numa festa junina",
            "Coisas que existem num parque de diversões",
            "Coisas que dá pra fazer com uma toalha",
            "Coisas transparentes",
            "Coisas que giram",
            "Coisas que fazem cheiro bom",
            "Coisas que fazem cheiro ruim",
            "Coisas que enferrujam",
            "Coisas que flutuam na água",
            "Coisas que explodem",
            "Coisas que grudam",
            "Objetos que cabem na palma da mão",
            "Coisas que fariam você famoso da noite pro dia"
        ]
    },
    {
        nome: "Praia",
        emoji: "🏖️",
        ativo: true,
        itens: [
            "Pessoas do ccb",
            "Familiares de pessoas do grupo",
            "Pessoas que sumiram do ccb",
            "Girias que você aprendeu aqui",
            "Lugares para ficar com alguém no ccb",
            "Músicas que te lembram daqui",
            "Restaurantes da praia",
            "Nomes de pais",
            "Cachorros do camping",
            "Funcionários do camping",
            "Datas para vir para praia",
            "Pessoas que ja ficaram",
            "Coisas para fazer com o grupo",
            "Momentos vergonhosos",
            "Momentos engraçados",
            "Momentos icônicos do grupo",
            "Coisas para levar para praia",
            "Coisas que so acontecem na madrugada do camping",
            "Desculpas para não beber",
            "Apelidos de pessoas do camping",
            "Bordões da praia",
            "Sabores de flurffy",
            "Pessoas que o Jõao ja ficou",
            "Pessoas que a Malulo ja ficou",
            "Adjetivos do Luiz",
            "Adjetivos do Pedro",
            "Adjetivos do Bruno",
            "Adjetivos do João",
            "Adjetivos do Caria",
            "Adjetivos do Leo",
            "Adjetivos da Malulo",
            "Adjetivos da Thais"
        ]
    }
];

const PUNICOES = [
    "Beba 2 goles!",
    "Beba 3 goles!",
    "Escolha alguém para beber 3 goles com você!",
    "Vire o copo!",
    "Pague 1 gole para cada pessoa da mesa.",
    "Tome um shot (se tiver) ou 4 goles!",
    "Fique 1 rodada sem falar. Se falar, beba!",
    "Imite um animal antes de beber 2 goles.",
    "Conte um segredo ou beba 4 goles.",
    "A pessoa à sua direita escolhe sua bebida!",
    "Beba com o braço cruzado com alguém.",
    "Dance por 10 segundos e depois beba 2 goles."
];

/* Junta todas as categorias dos grupos ativos numa lista única. */
function montarListaCategorias() {
    const lista = [];
    GRUPOS_CATEGORIAS.forEach(function (grupo) {
        if (grupo.ativo) {
            grupo.itens.forEach(function (item) {
                lista.push(item);
            });
        }
    });
    return lista;
}
