/* ============================================================
   CHUTA AÍ — BANCO DE PERGUNTAS
   ------------------------------------------------------------
   Cada pergunta tem:
     c = categoria
     p = pergunta
     r = resposta (número)
     u = unidade
     d = curiosidade curta
   Para adicionar uma pergunta, copie um bloco { ... } e edite.
   ============================================================ */

const CATEGORIAS = [
  { nome: "Animais",       emoji: "🐾" },
  { nome: "Corpo humano",  emoji: "🫀" },
  { nome: "Futebol",       emoji: "⚽" },
  { nome: "Olimpíadas",    emoji: "🏅" },
  { nome: "Copa do Mundo", emoji: "🏆" },
  { nome: "Geografia",     emoji: "🗺️" },
  { nome: "Países",        emoji: "🌍" },
  { nome: "Tecnologia",    emoji: "💻" },
  { nome: "Espaço",        emoji: "🚀" },
  { nome: "História",      emoji: "🏛️" },
  { nome: "Carros",        emoji: "🏎️" },
  { nome: "Aviação",       emoji: "✈️" },
  { nome: "Música",        emoji: "🎵" },
  { nome: "Filmes",        emoji: "🎬" },
  { nome: "Séries",        emoji: "📺" },
  { nome: "Comidas",       emoji: "🍔" },
  { nome: "Marcas",        emoji: "🏷️" },
  { nome: "Brasil",        emoji: "🇧🇷" },
  { nome: "Ciência",       emoji: "🔬" },
  { nome: "Curiosidades",  emoji: "💡" }
];

const PERGUNTAS = [

  /* ---------- ANIMAIS ---------- */
  { c: "Animais", p: "Quanto pesa um urso polar adulto?", r: 450, u: "kg", d: "Ursos polares conseguem nadar por dias seguidos sem descansar." },
  { c: "Animais", p: "Qual a velocidade máxima de um guepardo?", r: 112, u: "km/h", d: "Ele vai de 0 a 100 km/h em cerca de 3 segundos — mais rápido que muitos carros esportivos." },
  { c: "Animais", p: "Quanto pesa um elefante africano adulto?", r: 6000, u: "kg", d: "É o maior animal terrestre do planeta e come até 300 kg de plantas por dia." },
  { c: "Animais", p: "Qual a altura de uma girafa adulta?", r: 5.5, u: "metros", d: "Apesar do pescoção, a girafa tem 7 vértebras cervicais — o mesmo número que nós." },
  { c: "Animais", p: "Quantos anos pode viver uma tartaruga-gigante?", r: 150, u: "anos", d: "Algumas tartarugas vivas hoje nasceram no século XIX." },
  { c: "Animais", p: "Quantas toneladas pesa uma baleia-azul?", r: 150, u: "toneladas", d: "Só o coração dela pesa quase 200 kg — do tamanho de um carrinho de golfe." },
  { c: "Animais", p: "Quantas vezes por minuto bate o coração de um beija-flor em voo?", r: 1200, u: "batimentos", d: "Para comparar: o coração humano bate cerca de 70 vezes por minuto." },
  { c: "Animais", p: "Quantas espécies de formigas já foram catalogadas no mundo?", r: 12000, u: "espécies", d: "Estima-se que existam 20 quatrilhões de formigas vivas na Terra." },
  { c: "Animais", p: "Qual a velocidade de um falcão-peregrino em mergulho?", r: 390, u: "km/h", d: "É o animal mais rápido do mundo — mais veloz que um carro de Fórmula 1." },
  { c: "Animais", p: "Quantos corações tem um polvo?", r: 3, u: "corações", d: "Dois bombeiam sangue para as brânquias e um para o resto do corpo. E o sangue é azul!" },
  { c: "Animais", p: "Quantos anos vive uma arara-azul?", r: 60, u: "anos", d: "Em cativeiro, algumas araras passam dos 70 anos — mais que muitos humanos antigamente." },
  { c: "Animais", p: "Quantos metros pode medir uma sucuri (anaconda)?", r: 6, u: "metros", d: "É a cobra mais pesada do mundo, podendo passar de 100 kg." },
  { c: "Animais", p: "Quantas horas por dia dorme um coala?", r: 20, u: "horas", d: "A folha de eucalipto dá tão pouca energia que ele economiza dormindo quase o dia todo." },
  { c: "Animais", p: "Quantos metros um caracol percorre em uma hora?", r: 48, u: "metros", d: "Nesse ritmo, ele levaria quase um mês para percorrer uma maratona." },
  { c: "Animais", p: "Quantos dentes tem um tubarão-branco na boca?", r: 300, u: "dentes", d: "Os dentes caem e nascem a vida toda: um tubarão troca milhares de dentes." },

  /* ---------- CORPO HUMANO ---------- */
  { c: "Corpo humano", p: "Quantos litros de sangue existem, em média, no corpo humano?", r: 5, u: "litros", d: "O sangue dá uma volta completa pelo corpo em cerca de 1 minuto." },
  { c: "Corpo humano", p: "Quantos ossos tem o corpo de um adulto?", r: 206, u: "ossos", d: "Mais da metade deles fica nas mãos e nos pés." },
  { c: "Corpo humano", p: "Com quantos ossos um bebê nasce?", r: 300, u: "ossos", d: "Vários ossos se fundem durante o crescimento até sobrarem 206." },
  { c: "Corpo humano", p: "Quantos músculos tem o corpo humano?", r: 650, u: "músculos", d: "Só para dar um passo, você usa cerca de 200 músculos." },
  { c: "Corpo humano", p: "Quantas vezes o coração bate por dia?", r: 100000, u: "batimentos", d: "Em uma vida inteira, são mais de 2,5 bilhões de batidas." },
  { c: "Corpo humano", p: "Quantos quilômetros de vasos sanguíneos existem no corpo?", r: 96000, u: "km", d: "Daria para dar mais de 2 voltas ao redor da Terra." },
  { c: "Corpo humano", p: "Quantos litros de ar cabem nos pulmões de um adulto?", r: 6, u: "litros", d: "O pulmão esquerdo é menor que o direito para dar espaço ao coração." },
  { c: "Corpo humano", p: "Qual a velocidade de um espirro?", r: 160, u: "km/h", d: "É impossível espirrar de olhos abertos — o corpo fecha automaticamente." },
  { c: "Corpo humano", p: "Quantos fios de cabelo temos na cabeça, em média?", r: 100000, u: "fios", d: "Perdemos de 50 a 100 fios por dia sem nem perceber." },
  { c: "Corpo humano", p: "Quanto pesa o cérebro humano adulto?", r: 1.4, u: "kg", d: "Ele consome cerca de 20% de toda a energia do corpo." },
  { c: "Corpo humano", p: "Quantas vezes piscamos por dia?", r: 15000, u: "piscadas", d: "Passamos cerca de 10% do tempo acordados de olhos fechados por causa das piscadas." },
  { c: "Corpo humano", p: "Quantos litros de saliva produzimos por dia?", r: 1.5, u: "litros", d: "Em uma vida, dá para encher mais de 2 piscinas infantis." },
  { c: "Corpo humano", p: "Quantos metros tem o intestino delgado?", r: 6, u: "metros", d: "Esticado, o intestino delgado é mais alto que uma girafa." },
  { c: "Corpo humano", p: "Quantos trilhões de células formam o corpo humano?", r: 37, u: "trilhões", d: "E ainda carregamos mais bactérias do que células humanas." },
  { c: "Corpo humano", p: "Quantos dias vive um glóbulo vermelho?", r: 120, u: "dias", d: "O corpo produz cerca de 2 milhões de glóbulos vermelhos novos por segundo." },

  /* ---------- FUTEBOL ---------- */
  { c: "Futebol", p: "Qual a capacidade atual do Maracanã?", r: 78838, u: "lugares", d: "Na final da Copa de 1950, estima-se que quase 200 mil pessoas entraram no estádio." },
  { c: "Futebol", p: "Quantos centímetros tem a circunferência de uma bola de futebol oficial?", r: 70, u: "cm", d: "A bola oficial deve ter entre 68 e 70 cm de circunferência." },
  { c: "Futebol", p: "Quantos gramas pesa uma bola de futebol oficial?", r: 430, u: "gramas", d: "No início de cada jogo, a bola deve pesar entre 410 e 450 gramas." },
  { c: "Futebol", p: "Quantos quilômetros um jogador corre, em média, por partida?", r: 10, u: "km", d: "Meio-campistas são os que mais correm — alguns passam de 13 km." },
  { c: "Futebol", p: "Qual a altura do gol de futebol?", r: 2.44, u: "metros", d: "A medida vem das 8 jardas inglesas usadas desde o século XIX." },
  { c: "Futebol", p: "Qual a largura do gol de futebol?", r: 7.32, u: "metros", d: "O gol tem exatamente 3 vezes a largura da própria altura." },
  { c: "Futebol", p: "Qual a distância da marca do pênalti até a linha do gol?", r: 11, u: "metros", d: "Cerca de 75% dos pênaltis cobrados em jogos profissionais viram gol." },
  { c: "Futebol", p: "Qual a capacidade do Camp Nou, estádio do Barcelona?", r: 99000, u: "lugares", d: "É o maior estádio da Europa em capacidade." },
  { c: "Futebol", p: "Quantos títulos brasileiros o Palmeiras tem?", r: 12, u: "títulos", d: "É o maior campeão nacional do Brasil." },
  { c: "Futebol", p: "Qual a velocidade do chute mais forte já registrado no futebol?", r: 210, u: "km/h", d: "O brasileiro Hulk é dono de alguns dos chutes mais fortes já medidos." },
  { c: "Futebol", p: "Quantas Libertadores tem o Independiente, maior campeão da história?", r: 7, u: "títulos", d: "O clube argentino venceu todas as 7 finais que disputou." },
  { c: "Futebol", p: "Quantos gols oficiais Messi marcou pelo Barcelona?", r: 672, u: "gols", d: "É o recorde de gols por um jogador em um único clube." },
  { c: "Futebol", p: "Em que ano foi fundado o Sheffield FC, clube de futebol mais antigo do mundo?", r: 1857, u: "(ano)", d: "O clube inglês existe até hoje, jogando divisões amadoras." },
  { c: "Futebol", p: "Quantas Champions League o Real Madrid já venceu?", r: 15, u: "títulos", d: "O segundo colocado, o Milan, tem menos da metade: 7 taças." },
  { c: "Futebol", p: "Quantos clubes disputam a Série A do Brasileirão?", r: 20, u: "clubes", d: "São 38 rodadas: cada time joga contra todos os outros em casa e fora." },

  /* ---------- OLIMPÍADAS ---------- */
  { c: "Olimpíadas", p: "Quantas medalhas de ouro olímpicas tem Michael Phelps?", r: 23, u: "medalhas", d: "Sozinho, Phelps tem mais ouros que a maioria dos países." },
  { c: "Olimpíadas", p: "Quantas medalhas olímpicas Michael Phelps ganhou no total?", r: 28, u: "medalhas", d: "É o maior medalhista da história dos Jogos." },
  { c: "Olimpíadas", p: "Qual o recorde mundial dos 100 metros rasos, de Usain Bolt?", r: 9.58, u: "segundos", d: "Na prova do recorde, Bolt chegou a 44,7 km/h." },
  { c: "Olimpíadas", p: "Em que ano aconteceu a primeira Olimpíada da era moderna?", r: 1896, u: "(ano)", d: "Foi em Atenas, com apenas 14 países e nenhuma mulher competindo." },
  { c: "Olimpíadas", p: "Quantos anéis tem o símbolo olímpico?", r: 5, u: "anéis", d: "Eles representam os cinco continentes unidos pelo esporte." },
  { c: "Olimpíadas", p: "Quantos atletas participaram dos Jogos de Paris 2024?", r: 10500, u: "atletas", d: "Foi a primeira Olimpíada com o mesmo número de homens e mulheres." },
  { c: "Olimpíadas", p: "Qual o recorde mundial do salto em altura?", r: 2.45, u: "metros", d: "O cubano Javier Sotomayor saltou isso em 1993 — e ninguém superou até hoje." },
  { c: "Olimpíadas", p: "Qual o recorde mundial do salto em distância?", r: 8.95, u: "metros", d: "Mike Powell saltou isso em 1991 — quase o comprimento de um ônibus." },
  { c: "Olimpíadas", p: "Quantas medalhas o Brasil conquistou em Tóquio 2020?", r: 21, u: "medalhas", d: "Foi o melhor desempenho do Brasil na história até então." },
  { c: "Olimpíadas", p: "Quantos esportes fizeram parte de Paris 2024?", r: 32, u: "esportes", d: "O breaking (dança) estreou como esporte olímpico em Paris." },
  { c: "Olimpíadas", p: "Quantos gramas pesa a medalha de ouro de Paris 2024?", r: 529, u: "gramas", d: "Cada medalha carrega um pedaço de ferro original da Torre Eiffel." },
  { c: "Olimpíadas", p: "Quantos gramas de ouro de verdade tem uma medalha de ouro olímpica?", r: 6, u: "gramas", d: "A medalha de 'ouro' é 92% prata — só a cobertura é ouro." },
  { c: "Olimpíadas", p: "Quantos quilômetros tem uma maratona?", r: 42.195, u: "km", d: "A distância 'quebrada' foi definida em Londres 1908 para a chegada ficar diante da família real." },
  { c: "Olimpíadas", p: "Quantas delegações participaram da Rio 2016?", r: 207, u: "delegações", d: "Incluiu, pela primeira vez, uma equipe formada só por refugiados." },
  { c: "Olimpíadas", p: "Quantos metros tem uma piscina olímpica?", r: 50, u: "metros", d: "Ela comporta cerca de 2,5 milhões de litros de água." },

  /* ---------- COPA DO MUNDO ---------- */
  { c: "Copa do Mundo", p: "Quantos gols tem o maior artilheiro da história das Copas?", r: 16, u: "gols", d: "O alemão Miroslav Klose marcou seus 16 gols em 4 Copas diferentes." },
  { c: "Copa do Mundo", p: "Quantas Copas do Mundo o Brasil já venceu?", r: 5, u: "títulos", d: "É o único país que disputou todas as edições da Copa." },
  { c: "Copa do Mundo", p: "Em que ano aconteceu a primeira Copa do Mundo?", r: 1930, u: "(ano)", d: "Foi no Uruguai, com só 13 seleções — e o dono da casa foi campeão." },
  { c: "Copa do Mundo", p: "Quantos gols foram marcados na Copa do Catar 2022?", r: 172, u: "gols", d: "Foi o recorde de gols em uma única edição de Copa." },
  { c: "Copa do Mundo", p: "Quantas pessoas assistiram à final de 1950 no Maracanã?", r: 200000, u: "pessoas", d: "O número oficial é 173.850, mas estima-se que bem mais gente entrou." },
  { c: "Copa do Mundo", p: "Quantas seleções disputam a Copa do Mundo de 2026?", r: 48, u: "seleções", d: "É a primeira Copa com 3 países-sede: EUA, México e Canadá." },
  { c: "Copa do Mundo", p: "Quantos gols Mbappé marcou na final da Copa de 2022?", r: 3, u: "gols", d: "Foi o primeiro hat-trick em final de Copa desde 1966 — e mesmo assim ele perdeu." },
  { c: "Copa do Mundo", p: "Quantas Copas do Mundo a Itália já venceu?", r: 4, u: "títulos", d: "Mesmo com 4 títulos, a Itália ficou fora das Copas de 2018 e 2022." },
  { c: "Copa do Mundo", p: "Quantos gols a Hungria marcou na maior goleada da história das Copas?", r: 10, u: "gols", d: "Hungria 10 x 1 El Salvador, em 1982." },
  { c: "Copa do Mundo", p: "Quantos quilos pesa a taça da Copa do Mundo?", r: 6.1, u: "kg", d: "Ela é feita de ouro maciço 18 quilates." },
  { c: "Copa do Mundo", p: "Quantos centímetros tem a taça da Copa do Mundo?", r: 36.8, u: "cm", d: "O campeão leva para casa apenas uma réplica banhada a ouro." },
  { c: "Copa do Mundo", p: "Quantos jogos teve uma Copa com 32 seleções?", r: 64, u: "jogos", d: "Com 48 seleções em 2026, serão 104 partidas." },
  { c: "Copa do Mundo", p: "Quantos gols o Ronaldo Fenômeno marcou em Copas do Mundo?", r: 15, u: "gols", d: "Ele foi o artilheiro da Copa de 2002 com 8 gols." },
  { c: "Copa do Mundo", p: "Quantos gols a Alemanha marcou contra o Brasil na semifinal de 2014?", r: 7, u: "gols", d: "Foram 5 gols alemães em apenas 18 minutos no primeiro tempo." },
  { c: "Copa do Mundo", p: "Quantos países diferentes já foram campeões mundiais?", r: 8, u: "países", d: "Brasil, Alemanha, Itália, Argentina, França, Uruguai, Inglaterra e Espanha." },

  /* ---------- GEOGRAFIA ---------- */
  { c: "Geografia", p: "Qual a altura do Monte Everest?", r: 8849, u: "metros", d: "O Everest cresce cerca de 4 milímetros por ano por causa das placas tectônicas." },
  { c: "Geografia", p: "Quantos quilômetros possui a Muralha da China?", r: 21196, u: "km", d: "Ao contrário do mito, ela NÃO é visível da Lua a olho nu." },
  { c: "Geografia", p: "Quantos quilômetros tem o rio Amazonas?", r: 7000, u: "km", d: "Amazonas e Nilo disputam há décadas o título de rio mais longo do mundo." },
  { c: "Geografia", p: "Qual a profundidade da Fossa das Marianas?", r: 11000, u: "metros", d: "Se o Everest fosse colocado lá dentro, ainda sobrariam 2 km de água por cima." },
  { c: "Geografia", p: "Quantos milhões de km² tem o deserto do Saara?", r: 9.2, u: "milhões de km²", d: "O Saara é maior que o Brasil inteiro." },
  { c: "Geografia", p: "Quantos países são reconhecidos pela ONU?", r: 193, u: "países", d: "O mais novo é o Sudão do Sul, criado em 2011." },
  { c: "Geografia", p: "Qual a altura das Cataratas do Iguaçu?", r: 82, u: "metros", d: "São 275 quedas d'água — mais que o dobro das quedas do Niágara." },
  { c: "Geografia", p: "Quantos quilômetros tem o rio Nilo?", r: 6650, u: "km", d: "Ele atravessa 11 países africanos antes de chegar ao Mediterrâneo." },
  { c: "Geografia", p: "Qual a profundidade do Lago Baikal, o mais fundo do mundo?", r: 1642, u: "metros", d: "Ele guarda sozinho cerca de 20% de toda a água doce líquida do planeta." },
  { c: "Geografia", p: "Quantos milhões de km² tem o território do Brasil?", r: 8.5, u: "milhões de km²", d: "O Brasil é maior que toda a Europa continental." },
  { c: "Geografia", p: "Quantos fusos horários padrão existem no mundo?", r: 24, u: "fusos", d: "Contando meios-fusos como o da Índia, chega-se a 38 horários diferentes." },
  { c: "Geografia", p: "Qual a temperatura mais baixa já registrada na Terra?", r: -89, u: "°C", d: "Foi na estação Vostok, na Antártida, em 1983." },
  { c: "Geografia", p: "Qual a temperatura mais alta já registrada na Terra?", r: 56.7, u: "°C", d: "Foi no Vale da Morte, nos EUA, em 1913." },
  { c: "Geografia", p: "Qual porcentagem da superfície da Terra é coberta por água?", r: 71, u: "%", d: "Mesmo assim, só 2,5% de toda essa água é doce." },
  { c: "Geografia", p: "Qual a altura do Salto Ángel, a cachoeira mais alta do mundo?", r: 979, u: "metros", d: "Fica na Venezuela e inspirou o filme 'Up: Altas Aventuras'." },

  /* ---------- PAÍSES ---------- */
  { c: "Países", p: "Quantos milhões de habitantes possui o Brasil?", r: 213, u: "milhões de habitantes", d: "O Brasil é o 7º país mais populoso do mundo." },
  { c: "Países", p: "Quantos bilhões de habitantes tem a China?", r: 1.4, u: "bilhões de habitantes", d: "Em 2023, a China perdeu para a Índia o posto de país mais populoso." },
  { c: "Países", p: "Quantos bilhões de habitantes tem a Índia?", r: 1.45, u: "bilhões de habitantes", d: "1 em cada 5 pessoas do mundo vive na Índia." },
  { c: "Países", p: "Quantos países existem na África?", r: 54, u: "países", d: "É o continente com mais países no mundo." },
  { c: "Países", p: "Quantos habitantes tem o Vaticano?", r: 800, u: "habitantes", d: "É o menor país do mundo — cabe inteiro dentro do Parque Ibirapuera." },
  { c: "Países", p: "Quantos milhões de km² tem a Rússia?", r: 17, u: "milhões de km²", d: "A Rússia é tão grande que faz fronteira com 14 países." },
  { c: "Países", p: "Quantas ilhas formam a Indonésia?", r: 17000, u: "ilhas", d: "Milhares delas nem sequer têm nome oficial." },
  { c: "Países", p: "Quantos milhões de habitantes tem o Japão?", r: 124, u: "milhões de habitantes", d: "O Japão vende mais fraldas para idosos do que para bebês." },
  { c: "Países", p: "Quantas línguas oficiais tem a Índia?", r: 22, u: "línguas", d: "Além delas, o país tem mais de 19 mil dialetos." },
  { c: "Países", p: "Em quantos países o português é língua oficial?", r: 9, u: "países", d: "De Brasil e Portugal até Timor-Leste, do outro lado do mundo." },
  { c: "Países", p: "Quantos km² tem o Vaticano, o menor país do mundo?", r: 0.44, u: "km²", d: "É menor que muitos shoppings brasileiros." },
  { c: "Países", p: "Quantos habitantes por km² tem Mônaco, o país mais denso do mundo?", r: 19000, u: "hab/km²", d: "Cerca de 1 em cada 3 moradores de Mônaco é milionário." },
  { c: "Países", p: "Quantos países são cortados pela linha do Equador?", r: 13, u: "países", d: "O Brasil é um deles — a linha passa perto de Macapá." },
  { c: "Países", p: "Quantos milhões de habitantes têm os Estados Unidos?", r: 335, u: "milhões de habitantes", d: "É o 3º país mais populoso, atrás de Índia e China." },
  { c: "Países", p: "Quantos fusos horários tem a Rússia?", r: 11, u: "fusos", d: "Quando é meio-dia num extremo do país, é quase meia-noite no outro." },

  /* ---------- TECNOLOGIA ---------- */
  { c: "Tecnologia", p: "Em que ano foi lançado o primeiro iPhone?", r: 2007, u: "(ano)", d: "Steve Jobs o apresentou como '3 produtos em 1': iPod, telefone e internet." },
  { c: "Tecnologia", p: "Quantos bilhões de buscas o Google processa por dia?", r: 8.5, u: "bilhões", d: "São quase 100 mil buscas por segundo." },
  { c: "Tecnologia", p: "Quantos bilhões de horas de vídeo são assistidas no YouTube por dia?", r: 1, u: "bilhão de horas", d: "Isso equivale a mais de 100 mil anos de vídeo assistidos diariamente." },
  { c: "Tecnologia", p: "Em que ano foi criada a World Wide Web?", r: 1989, u: "(ano)", d: "Tim Berners-Lee doou a invenção ao mundo sem patentear nada." },
  { c: "Tecnologia", p: "Quantos gramas pesava o primeiro celular da história?", r: 790, u: "gramas", d: "O Motorola DynaTAC (1983) tinha bateria para só 30 minutos de conversa." },
  { c: "Tecnologia", p: "Quantos dólares custava o primeiro iPhone no lançamento?", r: 499, u: "dólares", d: "Corrigindo pela inflação, seria uns 750 dólares hoje — mais barato que muitos atuais." },
  { c: "Tecnologia", p: "Quantos milhões de aplicativos existem na App Store?", r: 1.8, u: "milhões", d: "Na estreia, em 2008, eram apenas 500 aplicativos." },
  { c: "Tecnologia", p: "Quantos bilhões de pessoas usam o WhatsApp?", r: 3, u: "bilhões", d: "No Brasil, o WhatsApp está instalado em 99% dos smartphones." },
  { c: "Tecnologia", p: "Em que ano o Google foi fundado?", r: 1998, u: "(ano)", d: "Nasceu numa garagem alugada na Califórnia — que o Google depois comprou." },
  { c: "Tecnologia", p: "Quantos bilhões de e-mails são enviados por dia no mundo?", r: 350, u: "bilhões", d: "Quase metade de todo esse tráfego é spam." },
  { c: "Tecnologia", p: "Quantos megabytes armazenava o primeiro disco rígido da história (1956)?", r: 5, u: "MB", d: "Ele pesava quase 1 tonelada e era transportado de avião. Hoje 5 MB é uma foto." },
  { c: "Tecnologia", p: "Quantos bilhões de transistores tem um chip de celular moderno?", r: 20, u: "bilhões", d: "Cada transistor é milhares de vezes mais fino que um fio de cabelo." },
  { c: "Tecnologia", p: "Quantos gigabits por segundo o 5G pode atingir?", r: 10, u: "Gbps", d: "Nessa velocidade, um filme inteiro em HD baixa em poucos segundos." },
  { c: "Tecnologia", p: "Em que ano foi enviado o primeiro e-mail da história?", r: 1971, u: "(ano)", d: "O criador, Ray Tomlinson, foi quem escolheu o símbolo @ para os endereços." },
  { c: "Tecnologia", p: "Quantos milhões de domínios .com existem registrados?", r: 160, u: "milhões", d: "O primeiro .com da história, symbolics.com, foi registrado em 1985 e existe até hoje." },

  /* ---------- ESPAÇO ---------- */
  { c: "Espaço", p: "Qual a distância da Terra até a Lua?", r: 384400, u: "km", d: "Caberiam todos os outros planetas do Sistema Solar enfileirados nesse espaço." },
  { c: "Espaço", p: "Qual a temperatura média da superfície do Sol?", r: 5500, u: "°C", d: "No núcleo do Sol, a temperatura chega a 15 milhões de graus." },
  { c: "Espaço", p: "Quantos milhões de km separam a Terra do Sol?", r: 150, u: "milhões de km", d: "Essa distância é chamada de Unidade Astronômica (UA)." },
  { c: "Espaço", p: "Quantos km tem o diâmetro de Júpiter?", r: 143000, u: "km", d: "Caberiam mais de 1.300 Terras dentro de Júpiter." },
  { c: "Espaço", p: "Quantos minutos a luz do Sol demora para chegar à Terra?", r: 8, u: "minutos", d: "Se o Sol apagasse agora, só perceberíamos 8 minutos depois." },
  { c: "Espaço", p: "Em que ano o homem pisou na Lua pela primeira vez?", r: 1969, u: "(ano)", d: "O computador da Apollo 11 era menos potente que uma calculadora atual." },
  { c: "Espaço", p: "Quantas pessoas já pisaram na Lua?", r: 12, u: "pessoas", d: "Todas entre 1969 e 1972 — ninguém voltou lá desde então." },
  { c: "Espaço", p: "Qual a velocidade da luz, em km por segundo?", r: 300000, u: "km/s", d: "Em 1 segundo, a luz daria 7 voltas e meia ao redor da Terra." },
  { c: "Espaço", p: "Qual a temperatura na superfície de Vênus?", r: 460, u: "°C", d: "Vênus é mais quente que Mercúrio, mesmo estando mais longe do Sol." },
  { c: "Espaço", p: "Quantas luas confirmadas tem Saturno?", r: 274, u: "luas", d: "Em 2025, foram anunciadas 128 luas novas de uma vez só." },
  { c: "Espaço", p: "Quantos dias terrestres dura um dia em Vênus?", r: 243, u: "dias", d: "Em Vênus, o dia dura mais que o ano — que tem 225 dias." },
  { c: "Espaço", p: "A quantos km de altitude fica a Estação Espacial Internacional?", r: 400, u: "km", d: "É mais ou menos a distância de São Paulo ao Rio de Janeiro, só que para cima." },
  { c: "Espaço", p: "Qual a velocidade da Estação Espacial Internacional?", r: 28000, u: "km/h", d: "Os astronautas veem 16 nasceres do sol por dia." },
  { c: "Espaço", p: "Quantos bilhões de anos tem o universo?", r: 13.8, u: "bilhões de anos", d: "A Terra só existe nos últimos 4,5 bilhões — um 'terço' da história." },
  { c: "Espaço", p: "Quantos km tem o diâmetro da Lua?", r: 3474, u: "km", d: "A Lua é mais larga que o Brasil de norte a sul... quase: o Brasil tem 4.395 km." },

  /* ---------- HISTÓRIA ---------- */
  { c: "História", p: "Quantos anos durou o Império Romano do Ocidente?", r: 500, u: "anos", d: "Já o Império Romano do Oriente durou mais mil anos, até 1453." },
  { c: "História", p: "Em que ano caiu o Muro de Berlim?", r: 1989, u: "(ano)", d: "O muro dividiu a cidade por 28 anos." },
  { c: "História", p: "Quantos anos têm as pirâmides de Gizé?", r: 4500, u: "anos", d: "Cleópatra viveu mais perto do lançamento do iPhone do que da construção das pirâmides." },
  { c: "História", p: "Quantos trabalhadores construíram a Grande Pirâmide do Egito?", r: 20000, u: "trabalhadores", d: "Eram trabalhadores pagos e alimentados — não escravos, como se pensava." },
  { c: "História", p: "Em que ano terminou a Segunda Guerra Mundial?", r: 1945, u: "(ano)", d: "O conflito envolveu mais de 60 países." },
  { c: "História", p: "Quantos milhões de pessoas morreram na Segunda Guerra Mundial?", r: 70, u: "milhões", d: "Foi o conflito mais mortal da história da humanidade." },
  { c: "História", p: "Em que ano o Brasil se tornou independente?", r: 1822, u: "(ano)", d: "O 'grito do Ipiranga' aconteceu às margens de um riacho, em 7 de setembro." },
  { c: "História", p: "Em que ano Colombo chegou à América?", r: 1492, u: "(ano)", d: "Ele morreu acreditando que tinha chegado à Ásia." },
  { c: "História", p: "Quantos anos durou a Guerra dos Cem Anos?", r: 116, u: "anos", d: "Apesar do nome, o conflito entre França e Inglaterra durou de 1337 a 1453." },
  { c: "História", p: "Em que ano Gutenberg inventou a prensa de tipos móveis?", r: 1440, u: "(ano)", d: "O primeiro grande livro impresso foi a Bíblia, com cerca de 180 cópias." },
  { c: "História", p: "Com quantos anos morreu o faraó Tutancâmon?", r: 19, u: "anos", d: "Sua tumba foi achada intacta em 1922, com mais de 5 mil objetos." },
  { c: "História", p: "Em que ano o Titanic afundou?", r: 1912, u: "(ano)", d: "O navio era considerado 'inafundável' e afundou na viagem de estreia." },
  { c: "História", p: "Quantas pessoas morreram no naufrágio do Titanic?", r: 1500, u: "pessoas", d: "Só havia botes salva-vidas para metade dos passageiros." },
  { c: "História", p: "Em que ano a escravidão foi abolida no Brasil?", r: 1888, u: "(ano)", d: "O Brasil foi o último país das Américas a abolir a escravidão." },
  { c: "História", p: "Quantos metros de comprimento tinha o Titanic?", r: 269, u: "metros", d: "Quase 3 campos de futebol enfileirados." },

  /* ---------- CARROS ---------- */
  { c: "Carros", p: "Qual a velocidade máxima do Bugatti Chiron Super Sport?", r: 490, u: "km/h", d: "Nessa velocidade, ele percorre um campo de futebol em menos de 1 segundo." },
  { c: "Carros", p: "Quantos milhões de carros são produzidos por ano no mundo?", r: 90, u: "milhões", d: "Isso dá quase 3 carros novos por segundo." },
  { c: "Carros", p: "Em que ano foi criado o primeiro automóvel, por Karl Benz?", r: 1886, u: "(ano)", d: "Tinha 3 rodas e menos potência que um cortador de grama moderno." },
  { c: "Carros", p: "Por quantos milhões de euros foi vendido o carro mais caro da história?", r: 135, u: "milhões de euros", d: "Uma Mercedes 300 SLR de 1955 — só existem 2 no mundo." },
  { c: "Carros", p: "Qual a maior velocidade já registrada por um carro de Fórmula 1 em corrida?", r: 372, u: "km/h", d: "Foi Valtteri Bottas, no GP do México de 2016." },
  { c: "Carros", p: "Quantas peças tem, em média, um carro de passeio?", r: 30000, u: "peças", d: "Contando cada parafuso, porca e clipe de plástico." },
  { c: "Carros", p: "Quantos milhões de Fuscas foram produzidos no mundo?", r: 21.5, u: "milhões", d: "É um dos carros mais produzidos da história, fabricado por 65 anos." },
  { c: "Carros", p: "Quantos km de autonomia tem um Tesla Model S?", r: 600, u: "km", d: "Daria para ir de São Paulo ao Rio sem recarregar — e ainda sobraria bateria." },
  { c: "Carros", p: "Quantos cavalos de potência tem um carro de Fórmula 1 atual?", r: 1000, u: "cv", d: "É mais de 10 vezes a potência de um carro popular." },
  { c: "Carros", p: "Em quantos segundos o carro elétrico mais rápido vai de 0 a 100 km/h?", r: 2, u: "segundos", d: "Mais rápido que a queda livre de um objeto solto da mesma altura." },
  { c: "Carros", p: "Quantos bilhões de carros existem no mundo?", r: 1.5, u: "bilhões", d: "Se todos parassem lado a lado, cobririam um país inteiro do tamanho de Portugal." },
  { c: "Carros", p: "Quantos litros tem o tanque de um carro popular?", r: 50, u: "litros", d: "Um carro de F1 usa cerca de 110 kg de combustível numa corrida." },
  { c: "Carros", p: "Em que ano a Ferrari foi fundada?", r: 1947, u: "(ano)", d: "Enzo Ferrari dizia vender carros de rua só para bancar as corridas." },
  { c: "Carros", p: "Quantos quilos pesa um carro popular?", r: 1000, u: "kg", d: "Um carro de F1 pesa bem menos: cerca de 800 kg com o piloto." },
  { c: "Carros", p: "Qual o recorde de velocidade em terra, batido pelo ThrustSSC?", r: 1228, u: "km/h", d: "Foi o primeiro carro a quebrar a barreira do som, em 1997." },

  /* ---------- AVIAÇÃO ---------- */
  { c: "Aviação", p: "Qual a velocidade de cruzeiro de um Boeing 747?", r: 900, u: "km/h", d: "Com vento a favor, alguns voos comerciais já passaram de 1.200 km/h em relação ao solo." },
  { c: "Aviação", p: "A quantos metros de altitude voa um avião comercial?", r: 11000, u: "metros", d: "Lá em cima, o ar é fino demais para respirar — por isso a cabine é pressurizada." },
  { c: "Aviação", p: "Quantos passageiros cabem num Airbus A380 em configuração máxima?", r: 850, u: "passageiros", d: "É o maior avião de passageiros do mundo, com dois andares completos." },
  { c: "Aviação", p: "Em que ano Santos Dumont voou com o 14-Bis em Paris?", r: 1906, u: "(ano)", d: "Foi o primeiro voo público homologado de um avião na história." },
  { c: "Aviação", p: "Quantas toneladas pesa um Airbus A380 na decolagem?", r: 575, u: "toneladas", d: "O equivalente a cerca de 100 elefantes africanos voando." },
  { c: "Aviação", p: "Quantos voos comerciais acontecem por dia no mundo?", r: 100000, u: "voos", d: "A cada instante, há mais de 10 mil aviões no ar." },
  { c: "Aviação", p: "Quantos metros de pista um A380 precisa para decolar?", r: 3000, u: "metros", d: "São 30 campos de futebol de corrida antes de sair do chão." },
  { c: "Aviação", p: "Qual era a velocidade máxima do Concorde?", r: 2180, u: "km/h", d: "Ele fazia Paris–Nova York em 3h30 — mais rápido que o fuso: 'chegava antes de partir'." },
  { c: "Aviação", p: "Quantos litros de combustível cabem num Boeing 747?", r: 216000, u: "litros", d: "Daria para abastecer um carro popular por mais de 40 anos." },
  { c: "Aviação", p: "Quantas horas dura o voo comercial mais longo do mundo?", r: 19, u: "horas", d: "Singapura–Nova York, sem escalas, cruzando meio planeta." },
  { c: "Aviação", p: "Quantos metros tem a envergadura (asa a asa) de um A380?", r: 80, u: "metros", d: "Maior que um campo de futebol de largura." },
  { c: "Aviação", p: "Quantos milhões de pessoas estão voando neste exato momento?", r: 1, u: "milhão", d: "É como se uma cidade inteira vivesse no céu o tempo todo." },
  { c: "Aviação", p: "Qual a temperatura do lado de fora do avião em altitude de cruzeiro?", r: -55, u: "°C", d: "Mais frio que o inverno na Sibéria — a poucos centímetros da sua janela." },
  { c: "Aviação", p: "Em que ano os irmãos Wright fizeram seu primeiro voo?", r: 1903, u: "(ano)", d: "O primeiro voo durou 12 segundos e percorreu apenas 36 metros." },
  { c: "Aviação", p: "Quantos aviões comerciais existem em operação no mundo?", r: 28000, u: "aviões", d: "A previsão é dobrar esse número em 20 anos." },

  /* ---------- MÚSICA ---------- */
  { c: "Música", p: "Quantos milhões de músicas existem no catálogo do Spotify?", r: 100, u: "milhões", d: "Ouvindo sem parar, você levaria mais de 600 anos para escutar tudo." },
  { c: "Música", p: "Quantos milhões de cópias vendeu 'Thriller', o álbum mais vendido da história?", r: 70, u: "milhões", d: "Michael Jackson segue com o recorde há mais de 40 anos." },
  { c: "Música", p: "Quantas teclas tem um piano?", r: 88, u: "teclas", d: "São 52 brancas e 36 pretas." },
  { c: "Música", p: "Quantas cordas tem uma harpa de concerto?", r: 47, u: "cordas", d: "Os pedais da harpa mudam o tom de todas as cordas ao mesmo tempo." },
  { c: "Música", p: "Quantos milhões de pessoas assistiram ao show de Rod Stewart em Copacabana (1994)?", r: 3.5, u: "milhões", d: "É até hoje o maior público de um show de música da história." },
  { c: "Música", p: "Quantos Grammys tem Beyoncé, a maior vencedora da história?", r: 35, u: "prêmios", d: "Ela ultrapassou o recorde histórico em 2023 e seguiu ampliando." },
  { c: "Música", p: "Em que ano os Beatles se formaram?", r: 1960, u: "(ano)", d: "A banda durou só 10 anos, mas mudou a música para sempre." },
  { c: "Música", p: "Quantas músicas os Beatles gravaram oficialmente?", r: 213, u: "músicas", d: "Quase tudo composto em menos de 8 anos de estúdio." },
  { c: "Música", p: "Por quantos milhões de dólares foi vendida a guitarra mais cara da história?", r: 6, u: "milhões de dólares", d: "O violão de Kurt Cobain no MTV Unplugged, leiloado em 2020." },
  { c: "Música", p: "Quantos minutos dura 'Bohemian Rhapsody', do Queen?", r: 6, u: "minutos", d: "5min55 — as rádios diziam que era longa demais para tocar. Erraram feio." },
  { c: "Música", p: "Quantos decibéis atinge um show de rock?", r: 110, u: "decibéis", d: "É quase o barulho de uma turbina de avião — por isso existem protetores de ouvido." },
  { c: "Música", p: "Em que ano aconteceu o primeiro Rock in Rio?", r: 1985, u: "(ano)", d: "Queen, AC/DC e Iron Maiden tocaram na mesma edição." },
  { c: "Música", p: "Quantos milhões de pessoas foram ao primeiro Rock in Rio?", r: 1.4, u: "milhões", d: "Foram 10 dias de festival numa cidade do rock construída do zero." },
  { c: "Música", p: "Quantas notas musicais existem na escala tradicional?", r: 7, u: "notas", d: "Contando os sustenidos e bemóis, são 12 sons diferentes por oitava." },
  { c: "Música", p: "Quantos milhões de discos Elvis Presley vendeu?", r: 500, u: "milhões", d: "Estimativas variam, mas ele segue entre os artistas mais vendidos de todos os tempos." },

  /* ---------- FILMES ---------- */
  { c: "Filmes", p: "Quantos bilhões de dólares 'Avatar' arrecadou nos cinemas?", r: 2.9, u: "bilhões de dólares", d: "É a maior bilheteria da história do cinema." },
  { c: "Filmes", p: "Quantos Oscars o filme 'Titanic' ganhou?", r: 11, u: "estatuetas", d: "Empatado com 'Ben-Hur' e 'O Senhor dos Anéis' como recordista." },
  { c: "Filmes", p: "Quantos minutos dura 'Vingadores: Ultimato'?", r: 181, u: "minutos", d: "Muita gente treinou para não ir ao banheiro durante a sessão." },
  { c: "Filmes", p: "Quantos milhões de dólares custou 'Vingadores: Ultimato'?", r: 356, u: "milhões de dólares", d: "É um dos filmes mais caros já produzidos." },
  { c: "Filmes", p: "Quantos filmes o Universo Marvel (MCU) já lançou?", r: 36, u: "filmes", d: "Tudo começou com 'Homem de Ferro', em 2008, considerado uma aposta arriscada." },
  { c: "Filmes", p: "Em que ano os irmãos Lumière exibiram o primeiro filme da história?", r: 1895, u: "(ano)", d: "Dizem que a plateia se assustou com a imagem de um trem vindo em sua direção." },
  { c: "Filmes", p: "Quantos milhões de dólares Robert Downey Jr. ganhou por 'Ultimato'?", r: 75, u: "milhões de dólares", d: "No primeiro 'Homem de Ferro', ele recebeu 'só' 500 mil." },
  { c: "Filmes", p: "Quantos Oscars o Brasil tem?", r: 1, u: "estatueta", d: "'Ainda Estou Aqui' venceu Melhor Filme Internacional em 2025." },
  { c: "Filmes", p: "Quantos minutos dura 'O Irlandês', um dos filmes mais longos da Netflix?", r: 209, u: "minutos", d: "Quase 3 horas e meia — muita gente dividiu em 'episódios'." },
  { c: "Filmes", p: "Quantos filmes a Índia produz por ano?", r: 2000, u: "filmes", d: "Bollywood produz mais filmes que Hollywood e vende mais ingressos também." },
  { c: "Filmes", p: "Quantos bilhões de dólares 'Vingadores: Ultimato' arrecadou?", r: 2.8, u: "bilhões de dólares", d: "Ficou atrás apenas de 'Avatar' na história do cinema." },
  { c: "Filmes", p: "Em que ano estreou o primeiro 'Star Wars'?", r: 1977, u: "(ano)", d: "O estúdio achava que seria um fracasso e quase cancelou o projeto." },
  { c: "Filmes", p: "Quantos mil dólares custou 'A Bruxa de Blair'?", r: 60, u: "mil dólares", d: "Arrecadou 248 milhões — um dos maiores lucros proporcionais da história." },
  { c: "Filmes", p: "Quantos quilos pesa a estatueta do Oscar?", r: 3.8, u: "kg", d: "Ela é de bronze banhado a ouro 24 quilates." },
  { c: "Filmes", p: "Quantos centímetros tem a estatueta do Oscar?", r: 34, u: "cm", d: "O desenho da estatueta não muda desde 1929." },

  /* ---------- SÉRIES ---------- */
  { c: "Séries", p: "Quantos episódios tem 'Friends'?", r: 236, u: "episódios", d: "Assistir tudo de uma vez levaria cerca de 4 dias sem dormir." },
  { c: "Séries", p: "Quantos episódios 'Os Simpsons' já passaram?", r: 790, u: "episódios", d: "É a série roteirizada mais longa da história da TV americana." },
  { c: "Séries", p: "Quantos milhões de dólares custou cada episódio da última temporada de 'Game of Thrones'?", r: 15, u: "milhões de dólares", d: "A batalha de Winterfell levou 55 noites seguidas de filmagem." },
  { c: "Séries", p: "Quantas temporadas tem 'Grey's Anatomy'?", r: 21, u: "temporadas", d: "É a série médica mais longa da história da TV." },
  { c: "Séries", p: "Quantos milhões de dólares cada ator de 'Friends' ganhava por episódio no final?", r: 1, u: "milhão de dólares", d: "Os seis negociaram juntos e receberam o mesmo valor." },
  { c: "Séries", p: "Quantos episódios tem 'Breaking Bad'?", r: 62, u: "episódios", d: "É esse o número de elementos químicos que aparecem... aliás, 62 é o samário (Sm)." },
  { c: "Séries", p: "Em que ano estreou 'Stranger Things'?", r: 2016, u: "(ano)", d: "A série fez as vendas de walkie-talkies dispararem no mundo todo." },
  { c: "Séries", p: "Quantos dias sem parar levaria para assistir todos os 'Simpsons'?", r: 12, u: "dias", d: "E a cada ano são adicionadas mais de 8 horas de episódios novos." },
  { c: "Séries", p: "Quantos episódios tem o anime 'One Piece'?", r: 1100, u: "episódios", d: "A história começou no mangá em 1997 e ainda não acabou." },
  { c: "Séries", p: "Quantos milhões de pessoas assistiram ao último episódio de 'Friends' nos EUA?", r: 52, u: "milhões", d: "Anúncios naquele episódio custaram 2 milhões de dólares por 30 segundos." },
  { c: "Séries", p: "Quantos milhões de dólares custou cada episódio da 4ª temporada de 'Stranger Things'?", r: 30, u: "milhões de dólares", d: "Mais caro que muitos filmes de cinema inteiros." },
  { c: "Séries", p: "Quantos episódios tem 'La Casa de Papel'?", r: 41, u: "episódios", d: "A série quase foi cancelada na Espanha antes de virar febre mundial na Netflix." },
  { c: "Séries", p: "Quantos prêmios Emmy 'Game of Thrones' ganhou?", r: 59, u: "prêmios", d: "É a série de drama mais premiada da história do Emmy." },
  { c: "Séries", p: "Quantas temporadas tem 'Supernatural'?", r: 15, u: "temporadas", d: "Foram 327 episódios ao longo de 15 anos no ar." },
  { c: "Séries", p: "Em que ano 'Chaves' estreou na TV brasileira?", r: 1984, u: "(ano)", d: "No México, a série original já tinha acabado 4 anos antes." },

  /* ---------- COMIDAS ---------- */
  { c: "Comidas", p: "Quantos milhões de pizzas o Brasil consome por dia?", r: 1.5, u: "milhões", d: "São Paulo é uma das cidades que mais comem pizza no mundo." },
  { c: "Comidas", p: "Quantas calorias tem um Big Mac?", r: 550, u: "calorias", d: "O molho especial do Big Mac tem receita guardada a sete chaves desde 1968." },
  { c: "Comidas", p: "Quantos grãos de arroz existem em 1 kg?", r: 50000, u: "grãos", d: "O arroz alimenta mais da metade da população mundial." },
  { c: "Comidas", p: "Quantos kg de chocolate um suíço come por ano?", r: 9, u: "kg", d: "A Suíça é o país que mais consome chocolate per capita no mundo." },
  { c: "Comidas", p: "Quantos mil dólares custa a pizza mais cara do mundo?", r: 12, u: "mil dólares", d: "A 'Louis XIII' leva 3 tipos de caviar e é preparada na sua casa por 3 chefs." },
  { c: "Comidas", p: "Quantos kg de café o brasileiro consome por ano?", r: 6, u: "kg", d: "O Brasil é o maior produtor de café do mundo há mais de 150 anos." },
  { c: "Comidas", p: "Quantos milhões de unidades Scoville tem a pimenta Carolina Reaper?", r: 2.2, u: "milhões de Scoville", d: "Uma pimenta dedo-de-moça comum tem 'só' 15 mil unidades." },
  { c: "Comidas", p: "Quantos sabores de Kit Kat já foram lançados no Japão?", r: 300, u: "sabores", d: "Tem de wasabi, batata-doce e até saquê." },
  { c: "Comidas", p: "Quantos m² tinha a maior pizza do mundo?", r: 1300, u: "m²", d: "Feita em Los Angeles em 2023, usou mais de 6 toneladas de massa." },
  { c: "Comidas", p: "Quantas calorias tem uma banana?", r: 90, u: "calorias", d: "A banana é levemente radioativa por causa do potássio — mas totalmente inofensiva." },
  { c: "Comidas", p: "Quantos litros de refrigerante o brasileiro bebe por ano?", r: 60, u: "litros", d: "O guaraná é uma invenção 100% brasileira, criada em 1921." },
  { c: "Comidas", p: "Quantos milhões de flores as abelhas visitam para fazer 1 kg de mel?", r: 4, u: "milhões de flores", d: "O mel é o único alimento que praticamente não estraga — acharam mel comestível em tumbas egípcias." },
  { c: "Comidas", p: "Quantos hambúrgueres o McDonald's vende por segundo no mundo?", r: 75, u: "por segundo", d: "São mais de 6 milhões de hambúrgueres por dia." },
  { c: "Comidas", p: "Qual a porcentagem de água em uma melancia?", r: 92, u: "%", d: "Tecnicamente, a melancia é uma fruta e um legume ao mesmo tempo." },
  { c: "Comidas", p: "Quantos ovos uma galinha põe por ano?", r: 300, u: "ovos", d: "A cor do ovo depende da raça da galinha — não da alimentação." },

  /* ---------- MARCAS ---------- */
  { c: "Marcas", p: "Quantos trilhões de dólares vale a Apple?", r: 3.5, u: "trilhões de dólares", d: "Vale mais que o PIB de quase todos os países do mundo." },
  { c: "Marcas", p: "Quantas lojas o McDonald's tem no mundo?", r: 40000, u: "lojas", d: "Presente em mais de 100 países — mas não na Islândia nem na Bolívia." },
  { c: "Marcas", p: "Quantos bilhões de porções de Coca-Cola são vendidas por dia?", r: 1.9, u: "bilhões", d: "Só 2 países do mundo não vendem Coca-Cola oficialmente: Cuba e Coreia do Norte." },
  { c: "Marcas", p: "Em que ano a Nike foi fundada?", r: 1964, u: "(ano)", d: "Começou como 'Blue Ribbon Sports', vendendo tênis japoneses em corridas." },
  { c: "Marcas", p: "Quantos dólares a Nike pagou pelo seu logo, o 'swoosh'?", r: 35, u: "dólares", d: "A estudante que o desenhou depois ganhou ações da empresa de presente." },
  { c: "Marcas", p: "Em quantos países a Coca-Cola é vendida?", r: 200, u: "países", d: "'Coca-Cola' é uma das palavras mais reconhecidas do planeta." },
  { c: "Marcas", p: "Quantos bilhões de pecinhas a LEGO produz por ano?", r: 36, u: "bilhões", d: "A LEGO é a maior fabricante de 'pneus' do mundo — em quantidade de rodinhas." },
  { c: "Marcas", p: "Em que ano a LEGO foi fundada?", r: 1932, u: "(ano)", d: "O nome vem do dinamarquês 'leg godt': 'brinque bem'." },
  { c: "Marcas", p: "Quantas lojas o Starbucks tem no mundo?", r: 38000, u: "lojas", d: "O nome vem de um personagem do livro 'Moby Dick'." },
  { c: "Marcas", p: "Em que ano surgiu a rede McDonald's como franquia?", r: 1955, u: "(ano)", d: "Os irmãos McDonald venderam tudo por 2,7 milhões de dólares — hoje vale centenas de bilhões." },
  { c: "Marcas", p: "Quantos bilhões de iPhones já foram vendidos desde 2007?", r: 2.3, u: "bilhões", d: "Se cada iPhone tivesse 15 cm, enfileirados dariam quase 9 voltas na Terra." },
  { c: "Marcas", p: "Quantos milhões de funcionários tem a Amazon?", r: 1.5, u: "milhões", d: "Começou em 1994 como uma livraria online na garagem de Jeff Bezos." },
  { c: "Marcas", p: "Por quantos bilhões de dólares o Facebook comprou o Instagram?", r: 1, u: "bilhão de dólares", d: "Em 2012, o Instagram tinha só 13 funcionários." },
  { c: "Marcas", p: "Por quantos bilhões de dólares o Facebook comprou o WhatsApp?", r: 19, u: "bilhões de dólares", d: "Foi uma das maiores aquisições de tecnologia da história." },
  { c: "Marcas", p: "Quantos milhões de carros a Toyota produz por ano?", r: 10, u: "milhões", d: "É a maior montadora do mundo em volume há vários anos." },

  /* ---------- BRASIL ---------- */
  { c: "Brasil", p: "Quantos municípios tem o Brasil?", r: 5570, u: "municípios", d: "O menor, Serra da Saudade (MG), tem cerca de 800 habitantes." },
  { c: "Brasil", p: "Quantos quilômetros tem o litoral brasileiro?", r: 7367, u: "km", d: "É um dos litorais mais extensos do mundo, com mais de 2 mil praias." },
  { c: "Brasil", p: "Qual a altura do Cristo Redentor (com o pedestal)?", r: 38, u: "metros", d: "A cabeça sozinha pesa 30 toneladas e foi montada em pedaços." },
  { c: "Brasil", p: "Em que ano a cidade de São Paulo foi fundada?", r: 1554, u: "(ano)", d: "Nasceu como um colégio jesuíta no Pátio do Colégio." },
  { c: "Brasil", p: "Quantos milhões de habitantes tem a cidade de São Paulo?", r: 11.5, u: "milhões de habitantes", d: "É a cidade mais populosa do hemisfério sul." },
  { c: "Brasil", p: "Quantos quilômetros tem a ponte Rio–Niterói?", r: 13, u: "km", d: "Na inauguração, em 1974, era a segunda ponte mais longa do mundo." },
  { c: "Brasil", p: "Quantas espécies de aves existem no Brasil?", r: 1970, u: "espécies", d: "O Brasil é um dos 3 países com mais espécies de aves do planeta." },
  { c: "Brasil", p: "Quantos milhões de km² tem a Floresta Amazônica?", r: 5.5, u: "milhões de km²", d: "Cerca de 60% dela fica em território brasileiro." },
  { c: "Brasil", p: "Quantos km² tem o Pantanal?", r: 150000, u: "km²", d: "É a maior planície alagável do planeta." },
  { c: "Brasil", p: "Em que ano Brasília foi inaugurada?", r: 1960, u: "(ano)", d: "Vista de cima, a cidade tem formato de avião (ou borboleta, dizem alguns)." },
  { c: "Brasil", p: "Em quantos meses Brasília foi construída?", r: 41, u: "meses", d: "Trabalhadores de todo o país, os 'candangos', ergueram a capital no cerrado." },
  { c: "Brasil", p: "Qual a maior temperatura já registrada oficialmente no Brasil?", r: 44.8, u: "°C", d: "Foi em Araçuaí (MG), em novembro de 2023." },
  { c: "Brasil", p: "Quantos quilômetros tem o rio São Francisco?", r: 2830, u: "km", d: "O 'Velho Chico' nasce em Minas e atravessa 5 estados." },
  { c: "Brasil", p: "Quantos milhões de turistas estrangeiros visitam o Brasil por ano?", r: 6, u: "milhões", d: "Só a França recebe mais de 90 milhões — o Brasil ainda tem muito a explorar." },
  { c: "Brasil", p: "Quantas línguas indígenas ainda são faladas no Brasil?", r: 274, u: "línguas", d: "Antes da colonização, estima-se que eram mais de 1.000." },

  /* ---------- CIÊNCIA ---------- */
  { c: "Ciência", p: "Qual a velocidade do som no ar, em km/h?", r: 1234, u: "km/h", d: "Por isso vemos o raio antes de ouvir o trovão." },
  { c: "Ciência", p: "Qual a temperatura do zero absoluto?", r: -273, u: "°C", d: "É a temperatura mais fria possível no universo — nada pode ser mais gelado." },
  { c: "Ciência", p: "Quantos elementos existem na tabela periódica?", r: 118, u: "elementos", d: "Os últimos foram criados em laboratório e duram frações de segundo." },
  { c: "Ciência", p: "Quantos bilhões de anos tem a Terra?", r: 4.5, u: "bilhões de anos", d: "Se a história da Terra fosse 1 dia, os humanos surgiriam no último minuto." },
  { c: "Ciência", p: "Qual a temperatura de um raio?", r: 30000, u: "°C", d: "É 5 vezes mais quente que a superfície do Sol." },
  { c: "Ciência", p: "A que velocidade a Terra gira na linha do Equador?", r: 1670, u: "km/h", d: "Estamos todos girando mais rápido que um avião comercial — sem sentir nada." },
  { c: "Ciência", p: "Quantos metros tem o buraco mais fundo já cavado pelo homem?", r: 12262, u: "metros", d: "O Poço de Kola, na Rússia, levou 20 anos para ser perfurado." },
  { c: "Ciência", p: "Quantos anos-luz nos separam da estrela mais próxima (além do Sol)?", r: 4.2, u: "anos-luz", d: "Com a nave mais rápida já feita, levaríamos milhares de anos até Proxima Centauri." },
  { c: "Ciência", p: "Quantas toneladas pesa uma nuvem comum?", r: 500, u: "toneladas", d: "Ela flutua porque o peso está espalhado em trilhões de gotículas minúsculas." },
  { c: "Ciência", p: "Quantos milhões de espécies já foram catalogadas na Terra?", r: 2, u: "milhões", d: "Estima-se que existam 8,7 milhões — a maioria ainda nem foi descoberta." },
  { c: "Ciência", p: "Qual a frequência máxima que o ouvido humano consegue escutar?", r: 20000, u: "Hz", d: "Cachorros escutam até 45.000 Hz — por isso apitos 'silenciosos' funcionam." },
  { c: "Ciência", p: "Quantos litros de água são gastos para produzir 1 kg de carne bovina?", r: 15000, u: "litros", d: "É o equivalente a mais de 150 banhos de 10 minutos." },
  { c: "Ciência", p: "Qual a temperatura do núcleo da Terra?", r: 5500, u: "°C", d: "É praticamente a mesma temperatura da superfície do Sol, bem embaixo de nós." },
  { c: "Ciência", p: "Quantos bilhões de neurônios tem o cérebro humano?", r: 86, u: "bilhões", d: "Cada neurônio se conecta a até 10 mil outros." },
  { c: "Ciência", p: "Quantos milissegundos dura um piscar de olhos?", r: 300, u: "milissegundos", d: "É daí que vem a expressão 'num piscar de olhos'." },

  /* ---------- CURIOSIDADES ---------- */
  { c: "Curiosidades", p: "Quantas vezes é possível dobrar uma folha de papel ao meio?", r: 7, u: "dobras", d: "O recorde mundial é 12 dobras — com um papel de 1,2 km de comprimento." },
  { c: "Curiosidades", p: "Quantos passos por dia a famosa recomendação manda dar?", r: 10000, u: "passos", d: "O número nasceu de uma campanha de marketing japonesa nos anos 1960." },
  { c: "Curiosidades", p: "Quantas toneladas pesa a Torre Eiffel?", r: 10100, u: "toneladas", d: "No calor, ela 'cresce' até 15 cm por causa da dilatação do ferro." },
  { c: "Curiosidades", p: "Qual a altura da Torre Eiffel?", r: 330, u: "metros", d: "Ela seria demolida após 20 anos — foi salva por servir de antena de rádio." },
  { c: "Curiosidades", p: "Quantos degraus tem a Torre Eiffel até o topo?", r: 1665, u: "degraus", d: "Todo ano acontece uma corrida oficial subindo as escadas." },
  { c: "Curiosidades", p: "Quantos milhões de itens tem a Biblioteca do Congresso dos EUA, a maior do mundo?", r: 170, u: "milhões", d: "As prateleiras somam mais de 1.300 km de comprimento." },
  { c: "Curiosidades", p: "Quantos sonhos temos por noite, em média?", r: 5, u: "sonhos", d: "Esquecemos 95% deles poucos minutos depois de acordar." },
  { c: "Curiosidades", p: "Quantos mil verbetes tem o dicionário Houaiss?", r: 228, u: "mil verbetes", d: "Uma pessoa comum usa só cerca de 3 mil palavras no dia a dia." },
  { c: "Curiosidades", p: "Quantos quilômetros uma pessoa caminha ao longo da vida?", r: 120000, u: "km", d: "Dá para dar 3 voltas completas ao redor da Terra." },
  { c: "Curiosidades", p: "Quantos litros de água gasta um banho de 10 minutos?", r: 90, u: "litros", d: "Um minuto a menos no chuveiro economiza milhares de litros por ano." },
  { c: "Curiosidades", p: "Quantos bilhões de bactérias vivem na boca humana?", r: 20, u: "bilhões", d: "Há mais bactérias na sua boca do que pessoas na Terra." },
  { c: "Curiosidades", p: "Quantos dias durou o recorde de uma pessoa sem dormir?", r: 11, u: "dias", d: "Randy Gardner, 17 anos, ficou 264 horas acordado em 1964 — não tente repetir." },
  { c: "Curiosidades", p: "Quantas cartas tem um baralho comum?", r: 52, u: "cartas", d: "52 cartas como as semanas do ano, 4 naipes como as estações. Coincidência?" },
  { c: "Curiosidades", p: "Quantas línguas são faladas no mundo?", r: 7000, u: "línguas", d: "Uma língua desaparece, em média, a cada 40 dias." },
  { c: "Curiosidades", p: "Quantos dias uma barata sobrevive sem a cabeça?", r: 9, u: "dias", d: "Ela respira pelo corpo — e só morre porque não consegue beber água." }
];

