// ============================================================
//  DADOS DO JOGO
//  Cada categoria tem um `label` e uma lista de palavras.
//  Cada palavra guarda junto a sua `hint` (dica do impostor).
//
//  As dicas são SUTIS de propósito: estão relacionadas à palavra,
//  mas são vagas e valem para vários itens do tema — dão só um
//  empurrãozinho para o impostor blefar, sem entregar quem é.
//  (O tema em si todo mundo já conhece.)
//
//  Para adicionar uma palavra, basta incluir { word, hint }.
// ============================================================

const CATEGORIES = {

  brasileirao_jogadores: {
    label: "⚽ Jogadores do Brasil",
    words: [
      { word: "Hulk",             hint: "É bem forte" },
      { word: "Gabigol",          hint: "Faz gols" },
      { word: "Pedro",            hint: "Joga na frente" },
      { word: "Arrascaeta",       hint: "Não é brasileiro" },
      { word: "Everton Ribeiro",  hint: "É habilidoso" },
      { word: "Yuri Alberto",     hint: "É rápido" },
      { word: "Rony",             hint: "É baixinho" },
      { word: "Raphael Veiga",    hint: "Chuta bem" },
      { word: "Germán Cano",      hint: "Não é brasileiro" },
      { word: "Luiz Araújo",      hint: "Corre bastante" },
      { word: "Gerson",           hint: "Joga no meio" },
      { word: "David Luiz",       hint: "Já é experiente" },
      { word: "Weverton",         hint: "Joga com luvas" },
      { word: "Cássio",           hint: "Já é veterano" },
      { word: "Diego Costa",      hint: "É bem intenso" },
      { word: "Marcos Rocha",     hint: "Um dos mais velhos" },
      { word: "Alan Franco",      hint: "Não é brasileiro" },
      { word: "Deyverson",        hint: "Vive em polêmica" },
      { word: "Vitor Roque",      hint: "É bem jovem" },
      { word: "Endrick",          hint: "É muito novo" },
      { word: "Estêvão",          hint: "É uma promessa" },
      { word: "Memphis Depay",    hint: "Jogou na Europa" },
      { word: "Calleri",          hint: "Não é brasileiro" },
      { word: "Luciano",          hint: "Faz gols" },
      { word: "Soteldo",          hint: "É bem baixinho" },
      { word: "Paulinho",         hint: "Bom de cabeça" },
      { word: "Bruno Henrique",   hint: "É veloz" },
      { word: "Everton Cebolinha",hint: "Chuta de canhota" },
      { word: "Tiquinho Soares",  hint: "Joga na frente" },
      { word: "Marcos Leonardo",  hint: "É bem jovem" },
      { word: "Nino",             hint: "Joga na defesa" },
      { word: "Gustavo Gómez",    hint: "Não é brasileiro" },
      { word: "Dudu",             hint: "Gosta de driblar" },
      { word: "Ganso",            hint: "Dá bons passes" },
      { word: "Thiago Silva",     hint: "Bem experiente" },
      { word: "Óscar",            hint: "Jogou longe do Brasil" },
      { word: "Wesley",           hint: "É jovem" },
      { word: "Alex Sandro",      hint: "Jogou na Europa" },
      { word: "Danilo",           hint: "Já jogou fora" },
      { word: "Léo Ortiz",        hint: "Joga na defesa" },
      { word: "Fabrício Bruno",   hint: "Joga na defesa" },
      { word: "Pedro Raul",       hint: "Joga na frente" },
      { word: "Kaio Jorge",       hint: "É jovem" },
      { word: "Lucas Moura",      hint: "Voltou da Europa" },
      { word: "Fábio",            hint: "Goleiro veterano" },
      { word: "Everson",          hint: "Joga no gol" },
      { word: "Rossi",            hint: "Joga no gol" },
      { word: "Léo Jardim",       hint: "Joga no gol" },
      { word: "William",          hint: "Joga na lateral" },
      { word: "André",            hint: "É volante" },
      { word: "Alan Patrick",     hint: "Meia experiente" },
      { word: "Richard Ríos",     hint: "Não é brasileiro" },
      { word: "Flaco López",      hint: "Não é brasileiro" },
      { word: "Vegetti",          hint: "Não é brasileiro" },
      { word: "Payet",            hint: "Não é brasileiro" },
      { word: "Cauly",            hint: "Joga no meio" },
      { word: "Talles Magno",     hint: "É jovem" },
      { word: "Igor Jesus",       hint: "Faz gols" },
      { word: "Maurício",         hint: "Joga no meio" }
    ]
  },

  jogadores_famosos: {
    label: "🌟 Jogadores famosos",
    words: [
      { word: "Lionel Messi",        hint: "É canhoto" },
      { word: "Cristiano Ronaldo",   hint: "Muito famoso" },
      { word: "Kylian Mbappé",       hint: "Muito rápido" },
      { word: "Neymar Jr",           hint: "É brasileiro" },
      { word: "Erling Haaland",      hint: "É bem alto" },
      { word: "Vinícius Júnior",     hint: "É brasileiro" },
      { word: "Kevin De Bruyne",     hint: "Dá muitas assistências" },
      { word: "Robert Lewandowski",  hint: "Faz muitos gols" },
      { word: "Luka Modrić",         hint: "Já é veterano" },
      { word: "Mohamed Salah",       hint: "Não é europeu" },
      { word: "Harry Kane",          hint: "Bom de finalização" },
      { word: "Jude Bellingham",     hint: "É jovem" },
      { word: "Rodri",               hint: "Joga no meio" },
      { word: "Antoine Griezmann",   hint: "É baixinho" },
      { word: "Karim Benzema",       hint: "Já é veterano" },
      { word: "Luis Suárez",         hint: "Não é brasileiro" },
      { word: "Sergio Ramos",        hint: "Joga na defesa" },
      { word: "Manuel Neuer",        hint: "Joga no gol" },
      { word: "Pelé",                hint: "Ídolo antigo" },
      { word: "Diego Maradona",      hint: "Ídolo antigo" },
      { word: "Zinédine Zidane",     hint: "É careca" },
      { word: "Ronaldinho Gaúcho",   hint: "Vivia sorrindo" },
      { word: "Ronaldo Fenômeno",    hint: "Fez muitos gols" },
      { word: "Zico",                hint: "Ídolo antigo" },
      { word: "Romário",             hint: "É baixinho" },
      { word: "Kaká",                hint: "Foi elegante em campo" },
      { word: "Andrés Iniesta",      hint: "Joga no meio" },
      { word: "Xavi",                hint: "Dava muitos passes" },
      { word: "Cafu",                hint: "Jogava na lateral" },
      { word: "Roberto Carlos",      hint: "Chutava muito forte" },
      { word: "Iker Casillas",       hint: "Jogava no gol" },
      { word: "Gareth Bale",         hint: "É veloz" },
      { word: "Thierry Henry",       hint: "Fazia muitos gols" },
      { word: "Wayne Rooney",        hint: "É inglês" },
      { word: "Franck Ribéry",       hint: "Jogava pela ponta" },
      { word: "Sergio Agüero",       hint: "Baixinho e goleador" },
      { word: "David Beckham",       hint: "Batia bem as faltas" },
      { word: "Andrea Pirlo",        hint: "Dava belos passes" },
      { word: "Paolo Maldini",       hint: "Jogava na defesa" },
      { word: "Francesco Totti",     hint: "Ídolo de um clube só" },
      { word: "Johan Cruyff",        hint: "Ídolo antigo" },
      { word: "Franz Beckenbauer",   hint: "Ídolo antigo" },
      { word: "Michel Platini",      hint: "Ídolo antigo" },
      { word: "Rivaldo",             hint: "É brasileiro" },
      { word: "Garrincha",           hint: "Ídolo antigo" },
      { word: "Gianluigi Buffon",    hint: "Jogava no gol" },
      { word: "Oliver Kahn",         hint: "Jogava no gol" },
      { word: "Steven Gerrard",      hint: "É inglês" },
      { word: "Frank Lampard",       hint: "É inglês" },
      { word: "Didier Drogba",       hint: "Não é europeu" },
      { word: "Samuel Eto'o",        hint: "Não é europeu" },
      { word: "Zlatan Ibrahimović",  hint: "É bem alto" },
      { word: "Andriy Shevchenko",   hint: "Fazia muitos gols" },
      { word: "Toni Kroos",          hint: "Dava muitos passes" },
      { word: "Marcelo",             hint: "É brasileiro" },
      { word: "Dani Alves",          hint: "É brasileiro" },
      { word: "Carles Puyol",        hint: "Jogava na defesa" }
    ]
  },

  famosos: {
    label: "🎬 Famosos",
    words: [
      { word: "Xuxa",              hint: "Aparece na TV" },
      { word: "Silvio Santos",     hint: "Aparecia na TV" },
      { word: "Ivete Sangalo",     hint: "Canta" },
      { word: "Anitta",            hint: "Canta" },
      { word: "Whindersson Nunes", hint: "Faz as pessoas rirem" },
      { word: "Fernanda Montenegro",hint: "Já atuou muito" },
      { word: "Taylor Swift",      hint: "Canta" },
      { word: "Beyoncé",           hint: "Canta e dança" },
      { word: "Michael Jackson",   hint: "Ficou famoso dançando" },
      { word: "Oprah Winfrey",     hint: "Aparece na TV" },
      { word: "Tom Hanks",         hint: "Faz filmes" },
      { word: "Adele",             hint: "Tem uma voz forte" },
      { word: "Rihanna",           hint: "Canta" },
      { word: "Elon Musk",         hint: "É muito rico" },
      { word: "Bill Gates",        hint: "É muito rico" },
      { word: "Steve Jobs",        hint: "Mexia com tecnologia" },
      { word: "Albert Einstein",   hint: "Muito inteligente" },
      { word: "Charlie Chaplin",   hint: "Do cinema antigo" },
      { word: "Madonna",           hint: "Canta há muito tempo" },
      { word: "Freddie Mercury",   hint: "Tinha voz marcante" },
      { word: "Faustão",           hint: "Aparece na TV" },
      { word: "Luciano Huck",      hint: "Aparece na TV" },
      { word: "Ana Maria Braga",   hint: "Aparece na TV" },
      { word: "Roberto Carlos",    hint: "Canta há muito tempo" },
      { word: "Gusttavo Lima",     hint: "Canta" },
      { word: "Marília Mendonça",  hint: "Cantava" },
      { word: "Wesley Safadão",    hint: "Canta" },
      { word: "Ludmilla",          hint: "Canta" },
      { word: "Luísa Sonza",       hint: "Canta" },
      { word: "Pabllo Vittar",     hint: "Canta" },
      { word: "Larissa Manoela",   hint: "Atua" },
      { word: "Bruna Marquezine",  hint: "Atua" },
      { word: "Virginia Fonseca",  hint: "Famosa na internet" },
      { word: "Carlinhos Maia",    hint: "Famoso na internet" },
      { word: "Casimiro",          hint: "Famoso na internet" },
      { word: "Ayrton Senna",      hint: "Foi ídolo no esporte" },
      { word: "LeBron James",      hint: "É atleta" },
      { word: "Kim Kardashian",    hint: "Famosa na internet" },
      { word: "Leonardo DiCaprio", hint: "Faz filmes" },
      { word: "Will Smith",        hint: "Faz filmes" },
      { word: "Drake",             hint: "Canta" },
      { word: "Justin Bieber",     hint: "Canta" },
      { word: "Lady Gaga",         hint: "Canta" },
      { word: "Ariana Grande",     hint: "Canta" },
      { word: "Bruno Mars",        hint: "Canta" },
      { word: "Ed Sheeran",        hint: "Canta" },
      { word: "Shakira",           hint: "Canta e dança" },
      { word: "Katy Perry",        hint: "Canta" },
      { word: "Alok",              hint: "Faz música eletrônica" },
      { word: "Ana Castela",       hint: "Canta" },
      { word: "Selena Gomez",      hint: "Famosa desde nova" },
      { word: "Dwayne Johnson",    hint: "Faz filmes" },
      { word: "Brad Pitt",         hint: "Faz filmes" },
      { word: "Johnny Depp",       hint: "Faz filmes" },
      { word: "Robert Downey Jr",  hint: "Faz filmes" },
      { word: "Keanu Reeves",      hint: "Faz filmes" },
      { word: "Cauã Reymond",      hint: "Atua" },
      { word: "Marina Ruy Barbosa",hint: "Atua" },
      { word: "Tatá Werneck",      hint: "Faz as pessoas rirem" },
      { word: "Sabrina Sato",      hint: "Aparece na TV" },
      { word: "Eliana",            hint: "Aparece na TV" },
      { word: "Angélica",          hint: "Aparece na TV" },
      { word: "William Bonner",    hint: "Aparece na TV" },
      { word: "Galvão Bueno",      hint: "Fala nos jogos" },
      { word: "Gisele Bündchen",   hint: "Trabalha como modelo" }
    ]
  },

  times_europa: {
    label: "🏆 Times da Europa",
    words: [
      { word: "Real Madrid",         hint: "Muito vencedor" },
      { word: "Barcelona",           hint: "Camisa listrada" },
      { word: "Manchester City",     hint: "Forte atualmente" },
      { word: "Manchester United",   hint: "Já foi dominante" },
      { word: "Liverpool",           hint: "Camisa vermelha" },
      { word: "Bayern de Munique",   hint: "Domina no país" },
      { word: "Paris Saint-Germain", hint: "Clube rico" },
      { word: "Juventus",            hint: "Camisa listrada" },
      { word: "Milan",               hint: "Camisa listrada" },
      { word: "Inter de Milão",      hint: "Camisa listrada" },
      { word: "Chelsea",             hint: "Camisa azul" },
      { word: "Arsenal",             hint: "Camisa vermelha" },
      { word: "Tottenham",           hint: "Camisa branca" },
      { word: "Atlético de Madrid",  hint: "Camisa listrada" },
      { word: "Borussia Dortmund",   hint: "Camisa amarela" },
      { word: "Bayer Leverkusen",    hint: "Camisa vermelha" },
      { word: "RB Leipzig",          hint: "Clube recente" },
      { word: "Ajax",                hint: "Revela jovens" },
      { word: "PSV",                 hint: "Revela jovens" },
      { word: "Feyenoord",           hint: "Torcida fiel" },
      { word: "Napoli",              hint: "Camisa azul" },
      { word: "Roma",                hint: "Camisa vermelha" },
      { word: "Sevilla",             hint: "Ganha copas menores" },
      { word: "Valencia",            hint: "Já foi mais forte" },
      { word: "Villarreal",          hint: "Camisa amarela" },
      { word: "Real Sociedad",       hint: "Time discreto" },
      { word: "Porto",               hint: "Vence bastante no país" },
      { word: "Benfica",             hint: "Torcida enorme" },
      { word: "Sporting",            hint: "Revela jovens" },
      { word: "Lyon",                hint: "Já foi dominante" },
      { word: "Marseille",           hint: "Torcida quente" },
      { word: "Monaco",              hint: "Clube pequeno e rico" },
      { word: "Newcastle",           hint: "Camisa listrada" },
      { word: "Aston Villa",         hint: "Time antigo" },
      { word: "Celtic",              hint: "Camisa listrada" },
      { word: "Galatasaray",         hint: "Torcida barulhenta" },
      { word: "Fenerbahçe",          hint: "Torcida barulhenta" },
      { word: "West Ham",            hint: "Fica em Londres" },
      { word: "Everton",             hint: "Camisa azul" },
      { word: "Leicester",           hint: "Já foi campeão surpresa" },
      { word: "Wolverhampton",       hint: "Camisa amarela" },
      { word: "Brighton",            hint: "Camisa listrada" },
      { word: "Athletic Bilbao",     hint: "Camisa listrada" },
      { word: "Real Betis",          hint: "Camisa listrada" },
      { word: "Fiorentina",          hint: "Camisa roxa" },
      { word: "Lazio",               hint: "Camisa azul" },
      { word: "Atalanta",            hint: "Camisa listrada" },
      { word: "Schalke 04",          hint: "Camisa azul" },
      { word: "Eintracht Frankfurt", hint: "Time alemão" },
      { word: "Wolfsburg",           hint: "Camisa verde" },
      { word: "Lille",               hint: "Já foi campeão surpresa" },
      { word: "Nice",                hint: "Camisa vermelha" },
      { word: "Rennes",              hint: "Time discreto" },
      { word: "Sporting Braga",      hint: "Revela jovens" },
      { word: "Rangers",             hint: "Torcida fiel" },
      { word: "Shakhtar",            hint: "Revela brasileiros" },
      { word: "Zenit",               hint: "Time do frio" },
      { word: "Club Brugge",         hint: "Torcida fiel" },
      { word: "Anderlecht",          hint: "Revela jovens" }
    ]
  },

  times_brasileirao: {
    label: "🇧🇷 Times do Brasileirão",
    words: [
      { word: "Flamengo",              hint: "Torcida gigante" },
      { word: "Palmeiras",             hint: "Ganhou títulos recentes" },
      { word: "Corinthians",           hint: "Torcida gigante" },
      { word: "São Paulo",             hint: "Camisa tricolor" },
      { word: "Santos",                hint: "Revelou craques" },
      { word: "Grêmio",                hint: "Camisa listrada" },
      { word: "Internacional",         hint: "Camisa vermelha" },
      { word: "Atlético Mineiro",      hint: "Camisa listrada" },
      { word: "Cruzeiro",              hint: "Camisa azul" },
      { word: "Vasco da Gama",         hint: "Camisa com faixa" },
      { word: "Botafogo",              hint: "Camisa listrada" },
      { word: "Fluminense",            hint: "Camisa tricolor" },
      { word: "Bahia",                 hint: "Camisa tricolor" },
      { word: "Fortaleza",             hint: "Cresceu recentemente" },
      { word: "Athletico Paranaense",  hint: "Camisa listrada" },
      { word: "Sport Recife",          hint: "Time do Nordeste" },
      { word: "Vitória",               hint: "Camisa listrada" },
      { word: "Ceará",                 hint: "Camisa listrada" },
      { word: "Goiás",                 hint: "Camisa verde" },
      { word: "Coritiba",              hint: "Camisa listrada" },
      { word: "Cuiabá",                hint: "Time do interior" },
      { word: "Bragantino",            hint: "Time do interior" },
      { word: "Juventude",             hint: "Camisa listrada" },
      { word: "América Mineiro",       hint: "Vive subindo e caindo" },
      { word: "Chapecoense",           hint: "Time do interior" },
      { word: "Avaí",                  hint: "Camisa azul" },
      { word: "Criciúma",              hint: "Camisa listrada" },
      { word: "Ponte Preta",           hint: "Time do interior" },
      { word: "Guarani",               hint: "Time do interior" },
      { word: "Náutico",               hint: "Time do Nordeste" },
      { word: "Atlético Goianiense",   hint: "Camisa listrada" },
      { word: "Remo",                  hint: "Time do Norte" },
      { word: "Paysandu",              hint: "Time do Norte" },
      { word: "Mirassol",              hint: "Time do interior" },
      { word: "Vila Nova",             hint: "Time do Centro-Oeste" },
      { word: "CRB",                   hint: "Time do Nordeste" },
      { word: "CSA",                   hint: "Time do Nordeste" },
      { word: "Sampaio Corrêa",        hint: "Time do Nordeste" },
      { word: "Botafogo-SP",           hint: "Time do interior" },
      { word: "Novorizontino",         hint: "Time do interior" },
      { word: "Operário",              hint: "Time do interior" },
      { word: "Londrina",              hint: "Time do interior" },
      { word: "Ituano",                hint: "Time do interior" },
      { word: "Ypiranga",              hint: "Time do interior" },
      { word: "Brusque",               hint: "Time do interior" },
      { word: "ABC",                   hint: "Time do Nordeste" },
      { word: "Santa Cruz",            hint: "Time do Nordeste" },
      { word: "América-RN",            hint: "Time do Nordeste" },
      { word: "Confiança",             hint: "Time do Nordeste" },
      { word: "Amazonas",              hint: "Time do Norte" },
      { word: "Ferroviária",           hint: "Time do interior" },
      { word: "Portuguesa",            hint: "Time tradicional de SP" },
      { word: "Volta Redonda",         hint: "Time do interior" },
      { word: "Tombense",              hint: "Time do interior" },
      { word: "Paraná",                hint: "Time do sul" },
      { word: "Figueirense",           hint: "Camisa listrada" }
    ]
  },

  selecoes: {
    label: "🌎 Seleções",
    words: [
      { word: "Brasil",          hint: "Já foi campeã várias vezes" },
      { word: "Argentina",       hint: "Rival histórico do Brasil" },
      { word: "França",          hint: "Já foi campeã" },
      { word: "Alemanha",        hint: "Já foi campeã" },
      { word: "Espanha",         hint: "Já foi campeã" },
      { word: "Inglaterra",      hint: "Onde o futebol nasceu" },
      { word: "Portugal",        hint: "Fala português" },
      { word: "Itália",          hint: "Já foi campeã" },
      { word: "Uruguai",         hint: "País pequeno e tradicional" },
      { word: "Holanda",         hint: "Cor laranja" },
      { word: "Bélgica",         hint: "Teve boa geração" },
      { word: "Croácia",         hint: "Camisa quadriculada" },
      { word: "Colômbia",        hint: "Da América do Sul" },
      { word: "Chile",           hint: "Da América do Sul" },
      { word: "Paraguai",        hint: "Faz divisa com o Brasil" },
      { word: "Peru",            hint: "Da América do Sul" },
      { word: "Equador",         hint: "Da América do Sul" },
      { word: "Japão",           hint: "Bem distante" },
      { word: "Coreia do Sul",   hint: "Bem distante" },
      { word: "México",          hint: "Da América do Norte" },
      { word: "Estados Unidos",  hint: "País bem rico" },
      { word: "Canadá",          hint: "País de clima frio" },
      { word: "Costa Rica",      hint: "País pequeno" },
      { word: "Marrocos",        hint: "Surpreendeu na Copa" },
      { word: "Senegal",         hint: "Da África" },
      { word: "Nigéria",         hint: "Da África" },
      { word: "Camarões",        hint: "Da África" },
      { word: "Gana",            hint: "Da África" },
      { word: "Egito",           hint: "Tem pirâmides" },
      { word: "Austrália",       hint: "Do outro lado do mundo" },
      { word: "Suíça",           hint: "País de clima frio" },
      { word: "Dinamarca",       hint: "País de clima frio" },
      { word: "Suécia",          hint: "País de clima frio" },
      { word: "Polônia",         hint: "Do leste europeu" },
      { word: "Sérvia",          hint: "Do leste europeu" },
      { word: "Escócia",         hint: "Da Europa" },
      { word: "Turquia",         hint: "Fica entre continentes" },
      { word: "Grécia",          hint: "Já foi campeã europeia" },
      { word: "Rússia",          hint: "País bem grande" },
      { word: "Ucrânia",         hint: "Do leste europeu" },
      { word: "Áustria",         hint: "País de clima frio" },
      { word: "Noruega",         hint: "País de clima frio" },
      { word: "País de Gales",   hint: "Fala inglês" },
      { word: "Irlanda",         hint: "Da Europa" },
      { word: "Costa do Marfim", hint: "Da África" },
      { word: "Argélia",         hint: "Da África" },
      { word: "Tunísia",         hint: "Da África" },
      { word: "África do Sul",   hint: "Da África" },
      { word: "Arábia Saudita",  hint: "País do deserto" },
      { word: "Irã",             hint: "Da Ásia" },
      { word: "Catar",           hint: "Sediou uma Copa" },
      { word: "China",           hint: "País bem populoso" },
      { word: "Venezuela",       hint: "Da América do Sul" },
      { word: "Bolívia",         hint: "Joga na altitude" },
      { word: "Panamá",          hint: "Da América Central" },
      { word: "Jamaica",         hint: "Ilha do Caribe" },
      { word: "Nova Zelândia",   hint: "Da Oceania" }
    ]
  },

  comida: {
    label: "🍕 Comida",
    words: [
      { word: "Pizza",           hint: "Dá pra dividir" },
      { word: "Feijoada",        hint: "Prato pesado" },
      { word: "Churrasco",       hint: "Feito na brasa" },
      { word: "Coxinha",         hint: "Salgado de festa" },
      { word: "Pão de Queijo",   hint: "Melhor quentinho" },
      { word: "Brigadeiro",      hint: "Doce de festa" },
      { word: "Açaí",            hint: "Servido gelado" },
      { word: "Sushi",           hint: "Comida oriental" },
      { word: "Hambúrguer",      hint: "Lanche rápido" },
      { word: "Lasanha",         hint: "Vai ao forno" },
      { word: "Pastel",          hint: "Comprado na feira" },
      { word: "Moqueca",         hint: "Leva peixe" },
      { word: "Tapioca",         hint: "Comida do Nordeste" },
      { word: "Picanha",         hint: "Bem suculenta" },
      { word: "Sorvete",         hint: "Servido gelado" },
      { word: "Cachorro-quente", hint: "Lanche de rua" },
      { word: "Pipoca",          hint: "Combina com cinema" },
      { word: "Batata frita",    hint: "Acompanhamento comum" },
      { word: "Macarrão",        hint: "Do dia a dia" },
      { word: "Strogonoff",      hint: "Bem cremoso" },
      { word: "Escondidinho",    hint: "Leva purê" },
      { word: "Panqueca",        hint: "Vem enrolada" },
      { word: "Bolo",            hint: "Tem em aniversário" },
      { word: "Pudim",           hint: "Sobremesa clássica" },
      { word: "Beijinho",        hint: "Doce de festa" },
      { word: "Quindim",         hint: "Doce amarelinho" },
      { word: "Cuscuz",          hint: "Café da manhã nordestino" },
      { word: "Vatapá",          hint: "Prato da Bahia" },
      { word: "Acarajé",         hint: "Comida de rua baiana" },
      { word: "Baião de dois",   hint: "Prato do Nordeste" },
      { word: "Empada",          hint: "Salgado recheado" },
      { word: "Esfiha",          hint: "Salgado de padaria" },
      { word: "Kibe",            hint: "Salgado meio árabe" },
      { word: "Nhoque",          hint: "Massa italiana" },
      { word: "Risoto",          hint: "Bem cremoso" },
      { word: "Taco",            hint: "Comida mexicana" },
      { word: "Ramen",           hint: "Comida oriental" },
      { word: "Yakisoba",        hint: "Comida oriental" },
      { word: "Temaki",          hint: "Comida japonesa" },
      { word: "Paçoca",          hint: "Doce de festa junina" },
      { word: "Pé de moleque",   hint: "Doce de festa junina" },
      { word: "Rabanada",        hint: "Aparece no Natal" },
      { word: "Canjica",         hint: "Doce de festa junina" },
      { word: "Milkshake",       hint: "Bebida gelada" },
      { word: "Miojo",           hint: "Fica pronto rápido" },
      { word: "Sopa",            hint: "Servida quente" },
      { word: "Salada",          hint: "Bem leve" },
      { word: "Omelete",         hint: "Leva ovo" },
      { word: "Pão francês",     hint: "De padaria" },
      { word: "Misto-quente",    hint: "Lanche simples" },
      { word: "Waffle",          hint: "Café da manhã doce" },
      { word: "Crepe",           hint: "Massa fininha" },
      { word: "Torta",           hint: "Pode ser doce ou salgada" },
      { word: "Mousse",          hint: "Sobremesa cremosa" },
      { word: "Cocada",          hint: "Doce de coco" },
      { word: "Cajuzinho",       hint: "Doce de festa" },
      { word: "Sonho",           hint: "Doce de padaria" },
      { word: "Churros",         hint: "Doce de rua" },
      { word: "Fondue",          hint: "Come mergulhando" },
      { word: "Sanduíche",       hint: "Lanche rápido" },
      { word: "Nuggets",         hint: "Petisco de frango" },
      { word: "Costela",         hint: "Assa por horas" },
      { word: "Feijão tropeiro", hint: "Prato mineiro" },
      { word: "Pamonha",         hint: "Feita de milho" },
      { word: "Curau",           hint: "Doce de milho" },
      { word: "Bolinho de chuva",hint: "Doce fritinho" }
    ]
  },

  objetos: {
    label: "🎒 Objetos",
    words: [
      { word: "Guarda-chuva",     hint: "Útil em certos dias" },
      { word: "Óculos",           hint: "Fica no rosto" },
      { word: "Celular",          hint: "Quase todo mundo tem" },
      { word: "Mochila",          hint: "Dá pra carregar coisas" },
      { word: "Relógio",          hint: "Fica no pulso" },
      { word: "Chave",            hint: "Bem pequena" },
      { word: "Espelho",          hint: "Feito de vidro" },
      { word: "Travesseiro",      hint: "Bem macio" },
      { word: "Cadeira",          hint: "Tem em toda casa" },
      { word: "Escova de dente",  hint: "Item de banheiro" },
      { word: "Fone de ouvido",   hint: "Fica na orelha" },
      { word: "Carteira",         hint: "Cabe no bolso" },
      { word: "Lanterna",         hint: "Útil no escuro" },
      { word: "Tesoura",          hint: "Bem afiada" },
      { word: "Vela",             hint: "Feita de cera" },
      { word: "Ventilador",       hint: "Bom no calor" },
      { word: "Geladeira",        hint: "Fica na cozinha" },
      { word: "Televisão",        hint: "Fica na sala" },
      { word: "Controle remoto",  hint: "Fica na mão" },
      { word: "Computador",       hint: "Usado no trabalho" },
      { word: "Teclado",          hint: "Cheio de botões" },
      { word: "Mouse",            hint: "Cabe na mão" },
      { word: "Caneta",           hint: "Cabe no bolso" },
      { word: "Lápis",            hint: "Bem simples" },
      { word: "Caderno",          hint: "Cheio de folhas" },
      { word: "Livro",            hint: "Cheio de páginas" },
      { word: "Copo",             hint: "Fica na cozinha" },
      { word: "Prato",            hint: "Fica na cozinha" },
      { word: "Garfo",            hint: "Fica na cozinha" },
      { word: "Faca",             hint: "Bem afiada" },
      { word: "Colher",           hint: "Fica na cozinha" },
      { word: "Panela",           hint: "Fica no fogão" },
      { word: "Vassoura",         hint: "Serve pra limpar" },
      { word: "Chinelo",          hint: "Vai no pé" },
      { word: "Boné",             hint: "Vai na cabeça" },
      { word: "Cinto",            hint: "Vai na cintura" },
      { word: "Anel",             hint: "Vai no dedo" },
      { word: "Colar",            hint: "Vai no pescoço" },
      { word: "Toalha",           hint: "Fica no banheiro" },
      { word: "Sabonete",         hint: "Fica no banheiro" },
      { word: "Isqueiro",         hint: "Cabe no bolso" },
      { word: "Martelo",          hint: "Ferramenta comum" },
      { word: "Régua",            hint: "Bem reta" },
      { word: "Sofá",             hint: "Fica na sala" },
      { word: "Cama",             hint: "Fica no quarto" },
      { word: "Mesa",             hint: "Tem em toda casa" },
      { word: "Abajur",           hint: "Fica no quarto" },
      { word: "Cortina",          hint: "Fica na janela" },
      { word: "Tapete",           hint: "Fica no chão" },
      { word: "Liquidificador",   hint: "Fica na cozinha" },
      { word: "Micro-ondas",      hint: "Fica na cozinha" },
      { word: "Ferro de passar",  hint: "Esquenta bastante" },
      { word: "Guarda-roupa",     hint: "Fica no quarto" },
      { word: "Cômoda",           hint: "Fica no quarto" },
      { word: "Estante",          hint: "Guarda coisas" },
      { word: "Almofada",         hint: "Bem macia" },
      { word: "Cobertor",         hint: "Bom no frio" },
      { word: "Lençol",           hint: "Fica na cama" },
      { word: "Pente",            hint: "Serve pro cabelo" },
      { word: "Secador",          hint: "Esquenta o ar" },
      { word: "Perfume",          hint: "Tem cheiro bom" },
      { word: "Batom",            hint: "Item de maquiagem" },
      { word: "Mala",             hint: "Vai em viagem" },
      { word: "Chave de fenda",   hint: "Ferramenta comum" },
      { word: "Alicate",          hint: "Ferramenta comum" },
      { word: "Prego",            hint: "Bem pequeno" },
      { word: "Balde",            hint: "Serve pra água" },
      { word: "Pano de prato",    hint: "Fica na cozinha" },
      { word: "Garrafa",          hint: "Serve pra líquidos" },
      { word: "Calculadora",      hint: "Faz contas" },
      { word: "Câmera",           hint: "Registra imagens" },
      { word: "Carregador",       hint: "Fica na tomada" },
      { word: "Óculos de sol",    hint: "Fica no rosto" },
      { word: "Chaveiro",         hint: "Bem pequeno" }
    ]
  },

  profissoes: {
    label: "👷 Profissões",
    words: [
      { word: "Médico",          hint: "Estudou muitos anos" },
      { word: "Professor",       hint: "Trabalha explicando" },
      { word: "Bombeiro",        hint: "Trabalho arriscado" },
      { word: "Advogado",        hint: "Usa terno" },
      { word: "Cozinheiro",      hint: "Trabalha em pé" },
      { word: "Policial",        hint: "Usa uniforme" },
      { word: "Piloto",          hint: "Trabalha viajando" },
      { word: "Dentista",        hint: "Trabalha sentado" },
      { word: "Eletricista",     hint: "Trabalha com as mãos" },
      { word: "Jornalista",      hint: "Vive informado" },
      { word: "Cabeleireiro",    hint: "Trabalha com as mãos" },
      { word: "Engenheiro",      hint: "Bom em cálculos" },
      { word: "Enfermeiro",      hint: "Ajuda os doentes" },
      { word: "Fotógrafo",       hint: "Trabalho criativo" },
      { word: "Garçom",          hint: "Trabalha em pé" },
      { word: "Arquiteto",       hint: "Trabalho criativo" },
      { word: "Pintor",          hint: "Trabalha com as mãos" },
      { word: "Pedreiro",        hint: "Trabalho pesado" },
      { word: "Encanador",       hint: "Trabalha com as mãos" },
      { word: "Mecânico",        hint: "Fica meio sujo" },
      { word: "Motorista",       hint: "Trabalha na rua" },
      { word: "Padeiro",         hint: "Acorda cedo" },
      { word: "Açougueiro",      hint: "Trabalha com as mãos" },
      { word: "Vendedor",        hint: "Fala com muita gente" },
      { word: "Contador",        hint: "Trabalha com números" },
      { word: "Programador",     hint: "Trabalha no computador" },
      { word: "Designer",        hint: "Trabalho criativo" },
      { word: "Veterinário",     hint: "Gosta de animais" },
      { word: "Farmacêutico",    hint: "Trabalha numa loja" },
      { word: "Psicólogo",       hint: "Sabe escutar" },
      { word: "Nutricionista",   hint: "Entende de comida" },
      { word: "Juiz",            hint: "Usa toga" },
      { word: "Delegado",        hint: "Trabalho sério" },
      { word: "Soldado",         hint: "Usa farda" },
      { word: "Astronauta",      hint: "Profissão rara" },
      { word: "Cientista",       hint: "Vive pesquisando" },
      { word: "Biólogo",         hint: "Estuda a natureza" },
      { word: "Escritor",        hint: "Trabalha escrevendo" },
      { word: "Ator",            hint: "Aparece em cena" },
      { word: "Cantor",          hint: "Trabalha com a voz" },
      { word: "Músico",          hint: "Trabalha com som" },
      { word: "Dançarino",       hint: "Trabalha com o corpo" },
      { word: "Modelo",          hint: "Aparece bastante" },
      { word: "Costureira",      hint: "Trabalha com as mãos" },
      { word: "Jardineiro",      hint: "Trabalha ao ar livre" },
      { word: "Agricultor",      hint: "Trabalha ao ar livre" },
      { word: "Pescador",        hint: "Trabalha perto da água" },
      { word: "Carteiro",        hint: "Anda bastante" },
      { word: "Segurança",       hint: "Fica de olho" },
      { word: "Barbeiro",        hint: "Trabalha com as mãos" },
      { word: "Confeiteiro",     hint: "Trabalha com doces" },
      { word: "Árbitro",         hint: "Trabalha apitando" },
      { word: "Recepcionista",   hint: "Atende as pessoas" },
      { word: "Caixa",           hint: "Trabalha numa loja" },
      { word: "Faxineiro",       hint: "Deixa tudo limpo" },
      { word: "Porteiro",        hint: "Fica na entrada" },
      { word: "Taxista",         hint: "Trabalha dirigindo" },
      { word: "Entregador",      hint: "Trabalha na rua" },
      { word: "Marinheiro",      hint: "Trabalha na água" },
      { word: "Salva-vidas",     hint: "Fica de olho na água" },
      { word: "Comissário de bordo", hint: "Trabalha voando" },
      { word: "Cirurgião",       hint: "Área da saúde" },
      { word: "Pediatra",        hint: "Cuida de crianças" },
      { word: "Historiador",     hint: "Estuda o passado" },
      { word: "Tradutor",        hint: "Trabalha com idiomas" },
      { word: "Locutor",         hint: "Trabalha com a voz" },
      { word: "Palhaço",         hint: "Faz as pessoas rirem" },
      { word: "Mágico",          hint: "Faz truques" },
      { word: "Manicure",        hint: "Cuida das unhas" },
      { word: "Sapateiro",       hint: "Conserta calçados" },
      { word: "Marceneiro",      hint: "Trabalha com madeira" },
      { word: "Frentista",       hint: "Trabalha no posto" },
      { word: "Detetive",        hint: "Vive investigando" },
      { word: "Maquiador",       hint: "Trabalho criativo" }
    ]
  },

  animais: {
    label: "🐾 Animais",
    words: [
      { word: "Elefante",     hint: "Bem pesado" },
      { word: "Girafa",       hint: "Come folhas" },
      { word: "Leão",         hint: "Vive em bando" },
      { word: "Jacaré",       hint: "Vive perto da água" },
      { word: "Tartaruga",    hint: "Anda devagar" },
      { word: "Papagaio",     hint: "Tem penas coloridas" },
      { word: "Canguru",      hint: "Dá saltos" },
      { word: "Golfinho",     hint: "Vive no mar" },
      { word: "Águia",        hint: "Voa alto" },
      { word: "Coruja",       hint: "Sai de noite" },
      { word: "Camelo",       hint: "Aguenta o calor" },
      { word: "Pinguim",      hint: "Aguenta o frio" },
      { word: "Zebra",        hint: "Vive na savana" },
      { word: "Urso",         hint: "Bem grandão" },
      { word: "Macaco",       hint: "Sobe em árvores" },
      { word: "Tigre",        hint: "Caçador solitário" },
      { word: "Leopardo",     hint: "Corre bastante" },
      { word: "Onça",         hint: "Vive na mata" },
      { word: "Lobo",         hint: "Vive em bando" },
      { word: "Raposa",       hint: "Bem esperta" },
      { word: "Cavalo",       hint: "Corre bastante" },
      { word: "Vaca",         hint: "Vive na fazenda" },
      { word: "Porco",        hint: "Vive na fazenda" },
      { word: "Ovelha",       hint: "Vive na fazenda" },
      { word: "Cabra",        hint: "Vive na fazenda" },
      { word: "Galinha",      hint: "Vive no galinheiro" },
      { word: "Pato",         hint: "Gosta de água" },
      { word: "Cachorro",     hint: "Bem comum em casa" },
      { word: "Gato",         hint: "Bem comum em casa" },
      { word: "Coelho",       hint: "Pula bastante" },
      { word: "Rato",         hint: "Bem pequeno" },
      { word: "Esquilo",      hint: "Sobe em árvores" },
      { word: "Hipopótamo",   hint: "Fica na água" },
      { word: "Rinoceronte",  hint: "Bem pesado" },
      { word: "Gorila",       hint: "Bem forte" },
      { word: "Panda",        hint: "Come bambu" },
      { word: "Coala",        hint: "Vive em árvores" },
      { word: "Preguiça",     hint: "Bem lenta" },
      { word: "Tamanduá",     hint: "Tem língua comprida" },
      { word: "Tatu",         hint: "Tem casco duro" },
      { word: "Capivara",     hint: "Vive perto da água" },
      { word: "Foca",         hint: "Vive no mar" },
      { word: "Baleia",       hint: "Bem enorme" },
      { word: "Tubarão",      hint: "Vive no mar" },
      { word: "Polvo",        hint: "Vive no mar" },
      { word: "Caranguejo",   hint: "Anda de lado" },
      { word: "Cobra",        hint: "Rasteja" },
      { word: "Lagarto",      hint: "Gosta do sol" },
      { word: "Sapo",         hint: "Vive perto da água" },
      { word: "Aranha",       hint: "Faz teia" },
      { word: "Abelha",       hint: "Faz zumbido" },
      { word: "Borboleta",    hint: "Tem asas coloridas" },
      { word: "Formiga",      hint: "Vive em grupo" },
      { word: "Escorpião",    hint: "Tem ferrão" },
      { word: "Morcego",      hint: "Sai de noite" },
      { word: "Pavão",        hint: "Tem penas bonitas" },
      { word: "Flamingo",     hint: "Fica numa perna só" },
      { word: "Cisne",        hint: "Nada com elegância" },
      { word: "Avestruz",     hint: "Corre muito" },
      { word: "Tucano",       hint: "Tem bico grande" },
      { word: "Beija-flor",   hint: "Bem pequenininho" },
      { word: "Cervo",        hint: "Vive na floresta" },
      { word: "Guaxinim",     hint: "Bem esperto" },
      { word: "Suricato",     hint: "Fica em pé vigiando" },
      { word: "Hiena",        hint: "Vive em bando" },
      { word: "Búfalo",       hint: "Bem pesado" },
      { word: "Alce",         hint: "Vive no frio" },
      { word: "Rena",         hint: "Vive no frio" },
      { word: "Lhama",        hint: "Bem peludo" },
      { word: "Burro",        hint: "Parece cavalo" },
      { word: "Camaleão",     hint: "Muda de cor" },
      { word: "Iguana",       hint: "Gosta do sol" },
      { word: "Peixe",        hint: "Vive na água" },
      { word: "Cavalo-marinho",hint: "Vive no mar" },
      { word: "Lagosta",      hint: "Vive no mar" },
      { word: "Camarão",      hint: "Vive na água" },
      { word: "Caracol",      hint: "Anda devagar" },
      { word: "Gafanhoto",    hint: "Dá saltos" },
      { word: "Joaninha",     hint: "Bem pequenininha" },
      { word: "Mosca",        hint: "Voa por aí" },
      { word: "Vaga-lume",    hint: "Brilha no escuro" },
      { word: "Codorna",      hint: "Bem pequena" },
      { word: "Pombo",        hint: "Vive na cidade" },
      { word: "Arara",        hint: "Tem penas coloridas" },
      { word: "Guepardo",     hint: "Corre muito rápido" },
      { word: "Lontra",       hint: "Vive perto da água" },
      { word: "Ouriço",       hint: "Cheio de espinhos" }
    ]
  }

};
