// ============================================================
//  DADOS DO JOGO
//  Cada categoria tem um `label` e uma lista de palavras.
//  Cada palavra guarda junto a sua `hint` (dica do impostor).
//
//  As dicas são SUTIS de propósito: estão relacionadas à palavra,
//  mas são vagas e valem para vários itens do tema — dão só um
//  empurrãozinho para o impostor blefar, sem entregar quem é.
//  (O tema em si todo mundo já conhece.)
//
//  Para adicionar uma palavra, basta incluir { word, hint }.
// ============================================================

const CATEGORIES = {

  brasileirao_jogadores: {
    label: "⚽ Jogadores do Brasil",
    words: [
      { word: "Hulk",             hint: "É bem forte" },
      { word: "Gabigol",          hint: "Faz gols" },
      { word: "Pedro",            hint: "Joga na frente" },
      { word: "Arrascaeta",       hint: "Não é brasileiro" },
      { word: "Everton Ribeiro",  hint: "É habilidoso" },
      { word: "Yuri Alberto",     hint: "É rápido" },
      { word: "Rony",             hint: "É baixinho" },
      { word: "Raphael Veiga",    hint: "Chuta bem" },
      { word: "Germán Cano",      hint: "Não é brasileiro" },
      { word: "Luiz Araújo",      hint: "Corre bastante" },
      { word: "Gerson",           hint: "Joga no meio" },
      { word: "David Luiz",       hint: "Já é experiente" },
      { word: "Weverton",         hint: "Joga com luvas" },
      { word: "Cássio",           hint: "Já é veterano" },
      { word: "Diego Costa",      hint: "É bem intenso" },
      { word: "Marcos Rocha",     hint: "Um dos mais velhos" },
      { word: "Alan Franco",      hint: "Não é brasileiro" },
      { word: "Deyverson",        hint: "Vive em polêmica" },
      { word: "Vitor Roque",      hint: "É bem jovem" },
      { word: "Endrick",          hint: "É muito novo" },
      { word: "Estêvão",          hint: "É uma promessa" },
      { word: "Memphis Depay",    hint: "Jogou na Europa" },
      { word: "Calleri",          hint: "Não é brasileiro" },
      { word: "Luciano",          hint: "Faz gols" },
      { word: "Soteldo",          hint: "É bem baixinho" },
      { word: "Paulinho",         hint: "Bom de cabeça" },
      { word: "Bruno Henrique",   hint: "É veloz" },
      { word: "Everton Cebolinha",hint: "Chuta de canhota" },
      { word: "Tiquinho Soares",  hint: "Joga na frente" },
      { word: "Marcos Leonardo",  hint: "É bem jovem" },
      { word: "Nino",             hint: "Joga na defesa" },
      { word: "Gustavo Gómez",    hint: "Não é brasileiro" },
      { word: "Dudu",             hint: "Gosta de driblar" },
      { word: "Ganso",            hint: "Dá bons passes" },
      { word: "Thiago Silva",     hint: "Bem experiente" },
      { word: "Óscar",            hint: "Jogou longe do Brasil" },
      { word: "Wesley",           hint: "É jovem" },
      { word: "Alex Sandro",      hint: "Jogou na Europa" },
      { word: "Danilo",           hint: "Já jogou fora" },
      { word: "Léo Ortiz",        hint: "Joga na defesa" },
      { word: "Fabrício Bruno",   hint: "Joga na defesa" },
      { word: "Pedro Raul",       hint: "Joga na frente" },
      { word: "Kaio Jorge",       hint: "É jovem" },
      { word: "Lucas Moura",      hint: "Voltou da Europa" },
      { word: "Fábio",            hint: "Goleiro veterano" },
      { word: "Everson",          hint: "Joga no gol" },
      { word: "Rossi",            hint: "Joga no gol" },
      { word: "Léo Jardim",       hint: "Joga no gol" },
      { word: "William",          hint: "Joga na lateral" },
      { word: "André",            hint: "É volante" },
      { word: "Alan Patrick",     hint: "Meia experiente" },
      { word: "Richard Ríos",     hint: "Não é brasileiro" },
      { word: "Flaco López",      hint: "Não é brasileiro" },
      { word: "Vegetti",          hint: "Não é brasileiro" },
      { word: "Payet",            hint: "Não é brasileiro" },
      { word: "Cauly",            hint: "Joga no meio" },
      { word: "Talles Magno",     hint: "É jovem" },
      { word: "Igor Jesus",       hint: "Faz gols" },
      { word: "Maurício",         hint: "Joga no meio" },
      { word: "Renato Augusto",   hint: "Meia experiente" },
      { word: "Fagner",           hint: "Joga na lateral" },
      { word: "Filipe Luís",      hint: "Jogou na Europa" },
      { word: "Diego Ribas",      hint: "Meia veterano" },
      { word: "Fred",             hint: "Fazia muitos gols" },
      { word: "Zé Rafael",        hint: "Joga no meio" },
      { word: "Piquerez",         hint: "Não é brasileiro" },
      { word: "Murilo",           hint: "Joga na defesa" },
      { word: "Léo Pereira",      hint: "Joga na defesa" },
      { word: "Ayrton Lucas",     hint: "Joga na lateral" },
      { word: "Matheuzinho",      hint: "Joga na lateral" },
      { word: "De la Cruz",       hint: "Não é brasileiro" },
      { word: "Pulgar",           hint: "Não é brasileiro" },
      { word: "Jhon Arias",       hint: "Não é brasileiro" },
      { word: "Marchesín",        hint: "Joga com luvas" },
      { word: "Arboleda",         hint: "Não é brasileiro" },
      { word: "Bobadilla",        hint: "Não é brasileiro" },
      { word: "Rafael",           hint: "Joga no gol" },
      { word: "Hugo Souza",       hint: "Joga no gol" },
      { word: "John",             hint: "Joga no gol" },
      { word: "Matheus Pereira",  hint: "É habilidoso" },
      { word: "Gustavo Scarpa",   hint: "Chuta bem" },
      { word: "Keno",             hint: "É veloz" },
      { word: "Marinho",          hint: "Chuta forte" },
      { word: "Yago Pikachu",     hint: "Tem apelido curioso" },
      { word: "Felipe Melo",      hint: "É bem intenso" },
      { word: "Thiago Maia",      hint: "É volante" },
      { word: "Jean Lucas",       hint: "Joga no meio" },
      { word: "Gabriel Menino",   hint: "É jovem" },
      { word: "Aníbal Moreno",    hint: "Não é brasileiro" },
      { word: "Ángel Romero",     hint: "Não é brasileiro" },
      { word: "Borja",            hint: "Faz gols" },
      { word: "Lucero",           hint: "Não é brasileiro" },
      { word: "Breno Lopes",      hint: "Fez gol importante" },
      { word: "Everaldo",         hint: "Joga na frente" },
      { word: "Erick Pulga",      hint: "É veloz" },
      { word: "Guilherme",        hint: "Faz gols" },
      { word: "Vitinho",          hint: "Gosta de driblar" },
      { word: "Zaracho",          hint: "Não é brasileiro" },
      { word: "Otávio",           hint: "É volante" },
      { word: "Igor Gomes",       hint: "Joga no meio" },
      { word: "Tchê Tchê",        hint: "Tem nome curioso" },
      { word: "Wellington Rato",  hint: "Joga no meio" },
      { word: "Lucas Lima",       hint: "Dá bons passes" },
      { word: "Walace",           hint: "É volante" },
      { word: "Hyoran",           hint: "Joga no meio" },
      { word: "Rodinei",          hint: "Joga na lateral" },
      { word: "Reinaldo",         hint: "Bate pênaltis" },
      { word: "Michael",          hint: "É veloz" },
      { word: "Marlon Freitas",   hint: "É volante" }
    ]
  },

  jogadores_famosos: {
    label: "🌟 Jogadores famosos",
    words: [
      { word: "Lionel Messi",        hint: "É canhoto" },
      { word: "Cristiano Ronaldo",   hint: "Muito famoso" },
      { word: "Kylian Mbappé",       hint: "Muito rápido" },
      { word: "Neymar Jr",           hint: "É brasileiro" },
      { word: "Erling Haaland",      hint: "É bem alto" },
      { word: "Vinícius Júnior",     hint: "É brasileiro" },
      { word: "Kevin De Bruyne",     hint: "Dá muitas assistências" },
      { word: "Robert Lewandowski",  hint: "Faz muitos gols" },
      { word: "Luka Modrić",         hint: "Já é veterano" },
      { word: "Mohamed Salah",       hint: "Não é europeu" },
      { word: "Harry Kane",          hint: "Bom de finalização" },
      { word: "Jude Bellingham",     hint: "É jovem" },
      { word: "Rodri",               hint: "Joga no meio" },
      { word: "Antoine Griezmann",   hint: "É baixinho" },
      { word: "Karim Benzema",       hint: "Já é veterano" },
      { word: "Luis Suárez",         hint: "Não é brasileiro" },
      { word: "Sergio Ramos",        hint: "Joga na defesa" },
      { word: "Manuel Neuer",        hint: "Joga no gol" },
      { word: "Pelé",                hint: "Ídolo antigo" },
      { word: "Diego Maradona",      hint: "Ídolo antigo" },
      { word: "Zinédine Zidane",     hint: "É careca" },
      { word: "Ronaldinho Gaúcho",   hint: "Vivia sorrindo" },
      { word: "Ronaldo Fenômeno",    hint: "Fez muitos gols" },
      { word: "Zico",                hint: "Ídolo antigo" },
      { word: "Romário",             hint: "É baixinho" },
      { word: "Kaká",                hint: "Foi elegante em campo" },
      { word: "Andrés Iniesta",      hint: "Joga no meio" },
      { word: "Xavi",                hint: "Dava muitos passes" },
      { word: "Cafu",                hint: "Jogava na lateral" },
      { word: "Roberto Carlos",      hint: "Chutava muito forte" },
      { word: "Iker Casillas",       hint: "Jogava no gol" },
      { word: "Gareth Bale",         hint: "É veloz" },
      { word: "Thierry Henry",       hint: "Fazia muitos gols" },
      { word: "Wayne Rooney",        hint: "É inglês" },
      { word: "Franck Ribéry",       hint: "Jogava pela ponta" },
      { word: "Sergio Agüero",       hint: "Baixinho e goleador" },
      { word: "David Beckham",       hint: "Batia bem as faltas" },
      { word: "Andrea Pirlo",        hint: "Dava belos passes" },
      { word: "Paolo Maldini",       hint: "Jogava na defesa" },
      { word: "Francesco Totti",     hint: "Ídolo de um clube só" },
      { word: "Johan Cruyff",        hint: "Ídolo antigo" },
      { word: "Franz Beckenbauer",   hint: "Ídolo antigo" },
      { word: "Michel Platini",      hint: "Ídolo antigo" },
      { word: "Rivaldo",             hint: "É brasileiro" },
      { word: "Garrincha",           hint: "Ídolo antigo" },
      { word: "Gianluigi Buffon",    hint: "Jogava no gol" },
      { word: "Oliver Kahn",         hint: "Jogava no gol" },
      { word: "Steven Gerrard",      hint: "É inglês" },
      { word: "Frank Lampard",       hint: "É inglês" },
      { word: "Didier Drogba",       hint: "Não é europeu" },
      { word: "Samuel Eto'o",        hint: "Não é europeu" },
      { word: "Zlatan Ibrahimović",  hint: "É bem alto" },
      { word: "Andriy Shevchenko",   hint: "Fazia muitos gols" },
      { word: "Toni Kroos",          hint: "Dava muitos passes" },
      { word: "Marcelo",             hint: "É brasileiro" },
      { word: "Dani Alves",          hint: "É brasileiro" },
      { word: "Carles Puyol",        hint: "Jogava na defesa" },
      { word: "Lamine Yamal",        hint: "É muito novo" },
      { word: "Rodrygo",             hint: "É brasileiro" },
      { word: "Bukayo Saka",         hint: "É inglês" },
      { word: "Phil Foden",          hint: "É inglês" },
      { word: "Declan Rice",         hint: "É inglês" },
      { word: "Bernardo Silva",      hint: "Joga no meio" },
      { word: "Bruno Fernandes",     hint: "Dá muitas assistências" },
      { word: "João Félix",          hint: "Já custou caro" },
      { word: "Pedri",               hint: "Joga no meio" },
      { word: "Gavi",                hint: "É jovem" },
      { word: "Frenkie de Jong",     hint: "Joga no meio" },
      { word: "Virgil van Dijk",     hint: "Joga na defesa" },
      { word: "Alisson",             hint: "Joga no gol" },
      { word: "Ederson",             hint: "Joga no gol" },
      { word: "Courtois",            hint: "É bem alto" },
      { word: "Ter Stegen",          hint: "Joga no gol" },
      { word: "Donnarumma",          hint: "Joga no gol" },
      { word: "Marquinhos",          hint: "É brasileiro" },
      { word: "Casemiro",            hint: "É volante" },
      { word: "Richarlison",         hint: "É brasileiro" },
      { word: "Gabriel Jesus",       hint: "É brasileiro" },
      { word: "Raphinha",            hint: "É brasileiro" },
      { word: "Lautaro Martínez",    hint: "Faz muitos gols" },
      { word: "Julián Álvarez",      hint: "Não é europeu" },
      { word: "Ángel Di María",      hint: "Já é veterano" },
      { word: "Paulo Dybala",        hint: "É canhoto" },
      { word: "Emiliano Martínez",   hint: "Joga no gol" },
      { word: "Sadio Mané",          hint: "Não é europeu" },
      { word: "Victor Osimhen",      hint: "Não é europeu" },
      { word: "Achraf Hakimi",       hint: "Não é europeu" },
      { word: "Son Heung-min",       hint: "Não é europeu" },
      { word: "Kai Havertz",         hint: "É alemão" },
      { word: "Joshua Kimmich",      hint: "Joga no meio" },
      { word: "Thomas Müller",       hint: "Já é veterano" },
      { word: "Antonio Rüdiger",     hint: "Joga na defesa" },
      { word: "Ousmane Dembélé",     hint: "Muito rápido" },
      { word: "Marcus Rashford",     hint: "É inglês" },
      { word: "Jack Grealish",       hint: "É inglês" },
      { word: "Cole Palmer",         hint: "É jovem" },
      { word: "Federico Valverde",   hint: "Corre bastante" },
      { word: "Aurélien Tchouaméni", hint: "É volante" },
      { word: "Eduardo Camavinga",   hint: "É jovem" },
      { word: "William Saliba",      hint: "Joga na defesa" },
      { word: "Rúben Dias",          hint: "Joga na defesa" },
      { word: "Alexander-Arnold",    hint: "Cruza muito bem" },
      { word: "Andrew Robertson",    hint: "Joga na lateral" },
      { word: "Theo Hernández",      hint: "Joga na lateral" },
      { word: "Rafael Leão",         hint: "É veloz" },
      { word: "Kvaratskhelia",       hint: "Gosta de driblar" },
      { word: "Eden Hazard",         hint: "Gostava de driblar" }
    ]
  },

  famosos: {
    label: "🎬 Famosos",
    words: [
      { word: "Xuxa",              hint: "Aparece na TV" },
      { word: "Silvio Santos",     hint: "Aparecia na TV" },
      { word: "Ivete Sangalo",     hint: "Canta" },
      { word: "Anitta",            hint: "Canta" },
      { word: "Whindersson Nunes", hint: "Faz as pessoas rirem" },
      { word: "Fernanda Montenegro",hint: "Já atuou muito" },
      { word: "Taylor Swift",      hint: "Canta" },
      { word: "Beyoncé",           hint: "Canta e dança" },
      { word: "Michael Jackson",   hint: "Ficou famoso dançando" },
      { word: "Oprah Winfrey",     hint: "Aparece na TV" },
      { word: "Tom Hanks",         hint: "Faz filmes" },
      { word: "Adele",             hint: "Tem uma voz forte" },
      { word: "Rihanna",           hint: "Canta" },
      { word: "Elon Musk",         hint: "É muito rico" },
      { word: "Bill Gates",        hint: "É muito rico" },
      { word: "Steve Jobs",        hint: "Mexia com tecnologia" },
      { word: "Albert Einstein",   hint: "Muito inteligente" },
      { word: "Charlie Chaplin",   hint: "Do cinema antigo" },
      { word: "Madonna",           hint: "Canta há muito tempo" },
      { word: "Freddie Mercury",   hint: "Tinha voz marcante" },
      { word: "Faustão",           hint: "Aparece na TV" },
      { word: "Luciano Huck",      hint: "Aparece na TV" },
      { word: "Ana Maria Braga",   hint: "Aparece na TV" },
      { word: "Roberto Carlos",    hint: "Canta há muito tempo" },
      { word: "Gusttavo Lima",     hint: "Canta" },
      { word: "Marília Mendonça",  hint: "Cantava" },
      { word: "Wesley Safadão",    hint: "Canta" },
      { word: "Ludmilla",          hint: "Canta" },
      { word: "Luísa Sonza",       hint: "Canta" },
      { word: "Pabllo Vittar",     hint: "Canta" },
      { word: "Larissa Manoela",   hint: "Atua" },
      { word: "Bruna Marquezine",  hint: "Atua" },
      { word: "Virginia Fonseca",  hint: "Famosa na internet" },
      { word: "Carlinhos Maia",    hint: "Famoso na internet" },
      { word: "Casimiro",          hint: "Famoso na internet" },
      { word: "Ayrton Senna",      hint: "Foi ídolo no esporte" },
      { word: "LeBron James",      hint: "É atleta" },
      { word: "Kim Kardashian",    hint: "Famosa na internet" },
      { word: "Leonardo DiCaprio", hint: "Faz filmes" },
      { word: "Will Smith",        hint: "Faz filmes" },
      { word: "Drake",             hint: "Canta" },
      { word: "Justin Bieber",     hint: "Canta" },
      { word: "Lady Gaga",         hint: "Canta" },
      { word: "Ariana Grande",     hint: "Canta" },
      { word: "Bruno Mars",        hint: "Canta" },
      { word: "Ed Sheeran",        hint: "Canta" },
      { word: "Shakira",           hint: "Canta e dança" },
      { word: "Katy Perry",        hint: "Canta" },
      { word: "Alok",              hint: "Faz música eletrônica" },
      { word: "Ana Castela",       hint: "Canta" },
      { word: "Selena Gomez",      hint: "Famosa desde nova" },
      { word: "Dwayne Johnson",    hint: "Faz filmes" },
      { word: "Brad Pitt",         hint: "Faz filmes" },
      { word: "Johnny Depp",       hint: "Faz filmes" },
      { word: "Robert Downey Jr",  hint: "Faz filmes" },
      { word: "Keanu Reeves",      hint: "Faz filmes" },
      { word: "Cauã Reymond",      hint: "Atua" },
      { word: "Marina Ruy Barbosa",hint: "Atua" },
      { word: "Tatá Werneck",      hint: "Faz as pessoas rirem" },
      { word: "Sabrina Sato",      hint: "Aparece na TV" },
      { word: "Eliana",            hint: "Aparece na TV" },
      { word: "Angélica",          hint: "Aparece na TV" },
      { word: "William Bonner",    hint: "Aparece na TV" },
      { word: "Galvão Bueno",      hint: "Fala nos jogos" },
      { word: "Gisele Bündchen",   hint: "Trabalha como modelo" },
      { word: "Zeca Pagodinho",    hint: "Canta há muito tempo" },
      { word: "Caetano Veloso",    hint: "Canta há muito tempo" },
      { word: "Gilberto Gil",      hint: "Canta há muito tempo" },
      { word: "Chico Buarque",     hint: "Canta e escreve" },
      { word: "Tim Maia",          hint: "Tinha voz marcante" },
      { word: "Cazuza",            hint: "Cantava" },
      { word: "Raul Seixas",       hint: "Cantava" },
      { word: "Renato Russo",      hint: "Cantava" },
      { word: "Rita Lee",          hint: "Cantava" },
      { word: "Milton Nascimento", hint: "Tem voz marcante" },
      { word: "Djavan",            hint: "Canta" },
      { word: "Seu Jorge",         hint: "Canta e atua" },
      { word: "Leonardo",          hint: "Canta há muito tempo" },
      { word: "Zezé Di Camargo",   hint: "Canta em dupla" },
      { word: "Simone Mendes",     hint: "Canta" },
      { word: "Rodrigo Faro",      hint: "Aparece na TV" },
      { word: "Marcos Mion",       hint: "Aparece na TV" },
      { word: "Celso Portiolli",   hint: "Aparece na TV" },
      { word: "Ratinho",           hint: "Aparece na TV" },
      { word: "Datena",            hint: "Aparece na TV" },
      { word: "Pedro Bial",        hint: "Aparece na TV" },
      { word: "Tadeu Schmidt",     hint: "Aparece na TV" },
      { word: "Fátima Bernardes",  hint: "Aparece na TV" },
      { word: "Serginho Groisman", hint: "Aparece na TV" },
      { word: "Jô Soares",         hint: "Fazia as pessoas rirem" },
      { word: "Renato Aragão",     hint: "Faz as pessoas rirem" },
      { word: "Paulo Gustavo",     hint: "Fazia as pessoas rirem" },
      { word: "Leandro Hassum",    hint: "Faz as pessoas rirem" },
      { word: "Fábio Porchat",     hint: "Faz as pessoas rirem" },
      { word: "Danilo Gentili",    hint: "Aparece na TV" },
      { word: "Gkay",              hint: "Famosa na internet" },
      { word: "Felipe Neto",       hint: "Famoso na internet" },
      { word: "Luccas Neto",       hint: "Famoso na internet" },
      { word: "Juliette",          hint: "Saiu de um reality" },
      { word: "Grazi Massafera",   hint: "Atua" },
      { word: "Paolla Oliveira",   hint: "Atua" },
      { word: "Juliana Paes",      hint: "Atua" },
      { word: "Wagner Moura",      hint: "Atua" },
      { word: "Rodrigo Santoro",   hint: "Atua" },
      { word: "Selton Mello",      hint: "Atua" },
      { word: "Lázaro Ramos",      hint: "Atua" },
      { word: "Taís Araújo",       hint: "Atua" },
      { word: "Tony Ramos",        hint: "Atua há muito tempo" },
      { word: "Susana Vieira",     hint: "Atua há muito tempo" },
      { word: "Tom Cruise",        hint: "Faz filmes" },
      { word: "Angelina Jolie",    hint: "Faz filmes" },
      { word: "Scarlett Johansson",hint: "Faz filmes" },
      { word: "Billie Eilish",     hint: "Canta" },
      { word: "Dua Lipa",          hint: "Canta" },
      { word: "MrBeast",           hint: "Famoso na internet" }
    ]
  },

  times_europa: {
    label: "🏆 Times da Europa",
    words: [
      { word: "Real Madrid",         hint: "Muito vencedor" },
      { word: "Barcelona",           hint: "Camisa listrada" },
      { word: "Manchester City",     hint: "Forte atualmente" },
      { word: "Manchester United",   hint: "Já foi dominante" },
      { word: "Liverpool",           hint: "Camisa vermelha" },
      { word: "Bayern de Munique",   hint: "Domina no país" },
      { word: "Paris Saint-Germain", hint: "Clube rico" },
      { word: "Juventus",            hint: "Camisa listrada" },
      { word: "Milan",               hint: "Camisa listrada" },
      { word: "Inter de Milão",      hint: "Camisa listrada" },
      { word: "Chelsea",             hint: "Camisa azul" },
      { word: "Arsenal",             hint: "Camisa vermelha" },
      { word: "Tottenham",           hint: "Camisa branca" },
      { word: "Atlético de Madrid",  hint: "Camisa listrada" },
      { word: "Borussia Dortmund",   hint: "Camisa amarela" },
      { word: "Bayer Leverkusen",    hint: "Camisa vermelha" },
      { word: "RB Leipzig",          hint: "Clube recente" },
      { word: "Ajax",                hint: "Revela jovens" },
      { word: "PSV",                 hint: "Revela jovens" },
      { word: "Feyenoord",           hint: "Torcida fiel" },
      { word: "Napoli",              hint: "Camisa azul" },
      { word: "Roma",                hint: "Camisa vermelha" },
      { word: "Sevilla",             hint: "Ganha copas menores" },
      { word: "Valencia",            hint: "Já foi mais forte" },
      { word: "Villarreal",          hint: "Camisa amarela" },
      { word: "Real Sociedad",       hint: "Time discreto" },
      { word: "Porto",               hint: "Vence bastante no país" },
      { word: "Benfica",             hint: "Torcida enorme" },
      { word: "Sporting",            hint: "Revela jovens" },
      { word: "Lyon",                hint: "Já foi dominante" },
      { word: "Marseille",           hint: "Torcida quente" },
      { word: "Monaco",              hint: "Clube pequeno e rico" },
      { word: "Newcastle",           hint: "Camisa listrada" },
      { word: "Aston Villa",         hint: "Time antigo" },
      { word: "Celtic",              hint: "Camisa listrada" },
      { word: "Galatasaray",         hint: "Torcida barulhenta" },
      { word: "Fenerbahçe",          hint: "Torcida barulhenta" },
      { word: "West Ham",            hint: "Fica em Londres" },
      { word: "Everton",             hint: "Camisa azul" },
      { word: "Leicester",           hint: "Já foi campeão surpresa" },
      { word: "Wolverhampton",       hint: "Camisa amarela" },
      { word: "Brighton",            hint: "Camisa listrada" },
      { word: "Athletic Bilbao",     hint: "Camisa listrada" },
      { word: "Real Betis",          hint: "Camisa listrada" },
      { word: "Fiorentina",          hint: "Camisa roxa" },
      { word: "Lazio",               hint: "Camisa azul" },
      { word: "Atalanta",            hint: "Camisa listrada" },
      { word: "Schalke 04",          hint: "Camisa azul" },
      { word: "Eintracht Frankfurt", hint: "Time alemão" },
      { word: "Wolfsburg",           hint: "Camisa verde" },
      { word: "Lille",               hint: "Já foi campeão surpresa" },
      { word: "Nice",                hint: "Camisa vermelha" },
      { word: "Rennes",              hint: "Time discreto" },
      { word: "Sporting Braga",      hint: "Revela jovens" },
      { word: "Rangers",             hint: "Torcida fiel" },
      { word: "Shakhtar",            hint: "Revela brasileiros" },
      { word: "Zenit",               hint: "Time do frio" },
      { word: "Club Brugge",         hint: "Torcida fiel" },
      { word: "Anderlecht",          hint: "Revela jovens" },
      { word: "Girona",              hint: "Já surpreendeu no campeonato" },
      { word: "Getafe",              hint: "Time discreto" },
      { word: "Osasuna",             hint: "Time discreto" },
      { word: "Celta de Vigo",       hint: "Camisa azul clara" },
      { word: "Espanyol",            hint: "Divide a cidade com um gigante" },
      { word: "Mallorca",            hint: "Time de ilha" },
      { word: "Las Palmas",          hint: "Time de ilha" },
      { word: "La Coruña",           hint: "Já foi mais forte" },
      { word: "Málaga",              hint: "Já jogou a Champions" },
      { word: "Bologna",             hint: "Time italiano" },
      { word: "Torino",              hint: "Divide a cidade com um gigante" },
      { word: "Sampdoria",           hint: "Camisa listrada" },
      { word: "Genoa",               hint: "Camisa listrada" },
      { word: "Parma",               hint: "Já foi mais forte" },
      { word: "Cagliari",            hint: "Time de ilha" },
      { word: "Udinese",             hint: "Camisa listrada" },
      { word: "Sassuolo",            hint: "Camisa verde" },
      { word: "Monza",               hint: "Clube recente na elite" },
      { word: "Fulham",              hint: "Fica em Londres" },
      { word: "Crystal Palace",      hint: "Fica em Londres" },
      { word: "Brentford",           hint: "Fica em Londres" },
      { word: "Bournemouth",         hint: "Camisa listrada" },
      { word: "Nottingham Forest",   hint: "Já venceu a Europa" },
      { word: "Southampton",         hint: "Camisa listrada" },
      { word: "Leeds United",        hint: "Torcida fiel" },
      { word: "Sunderland",          hint: "Camisa listrada" },
      { word: "Blackburn",           hint: "Já foi campeão surpresa" },
      { word: "Stuttgart",           hint: "Camisa branca" },
      { word: "Mönchengladbach",     hint: "Nome difícil de falar" },
      { word: "Werder Bremen",       hint: "Camisa verde" },
      { word: "Hamburgo",            hint: "Já foi mais forte" },
      { word: "Colônia",             hint: "Time alemão" },
      { word: "Union Berlin",        hint: "Time da capital" },
      { word: "Hertha Berlin",       hint: "Time da capital" },
      { word: "Hoffenheim",          hint: "Clube recente" },
      { word: "Mainz",               hint: "Time alemão" },
      { word: "Freiburg",            hint: "Time discreto" },
      { word: "Saint-Étienne",       hint: "Já foi dominante" },
      { word: "Bordeaux",            hint: "Já foi mais forte" },
      { word: "Nantes",              hint: "Camisa amarela" },
      { word: "Lens",                hint: "Torcida quente" },
      { word: "Toulouse",            hint: "Camisa roxa" },
      { word: "Strasbourg",          hint: "Time francês" },
      { word: "Montpellier",         hint: "Já foi campeão surpresa" },
      { word: "Boavista",            hint: "Camisa quadriculada" },
      { word: "Vitória de Guimarães",hint: "Time português" },
      { word: "Besiktas",            hint: "Torcida barulhenta" },
      { word: "Trabzonspor",         hint: "Time turco" },
      { word: "Olympiacos",          hint: "Domina no país" },
      { word: "Panathinaikos",       hint: "Camisa verde" }
    ]
  },

  times_brasileirao: {
    label: "🇧🇷 Times do Brasileirão",
    words: [
      { word: "Flamengo",              hint: "Torcida gigante" },
      { word: "Palmeiras",             hint: "Ganhou títulos recentes" },
      { word: "Corinthians",           hint: "Torcida gigante" },
      { word: "São Paulo",             hint: "Camisa tricolor" },
      { word: "Santos",                hint: "Revelou craques" },
      { word: "Grêmio",                hint: "Camisa listrada" },
      { word: "Internacional",         hint: "Camisa vermelha" },
      { word: "Atlético Mineiro",      hint: "Camisa listrada" },
      { word: "Cruzeiro",              hint: "Camisa azul" },
      { word: "Vasco da Gama",         hint: "Camisa com faixa" },
      { word: "Botafogo",              hint: "Camisa listrada" },
      { word: "Fluminense",            hint: "Camisa tricolor" },
      { word: "Bahia",                 hint: "Camisa tricolor" },
      { word: "Fortaleza",             hint: "Cresceu recentemente" },
      { word: "Athletico Paranaense",  hint: "Camisa listrada" },
      { word: "Sport Recife",          hint: "Time do Nordeste" },
      { word: "Vitória",               hint: "Camisa listrada" },
      { word: "Ceará",                 hint: "Camisa listrada" },
      { word: "Goiás",                 hint: "Camisa verde" },
      { word: "Coritiba",              hint: "Camisa listrada" },
      { word: "Cuiabá",                hint: "Time do interior" },
      { word: "Bragantino",            hint: "Time do interior" },
      { word: "Juventude",             hint: "Camisa listrada" },
      { word: "América Mineiro",       hint: "Vive subindo e caindo" },
      { word: "Chapecoense",           hint: "Time do interior" },
      { word: "Avaí",                  hint: "Camisa azul" },
      { word: "Criciúma",              hint: "Camisa listrada" },
      { word: "Ponte Preta",           hint: "Time do interior" },
      { word: "Guarani",               hint: "Time do interior" },
      { word: "Náutico",               hint: "Time do Nordeste" },
      { word: "Atlético Goianiense",   hint: "Camisa listrada" },
      { word: "Remo",                  hint: "Time do Norte" },
      { word: "Paysandu",              hint: "Time do Norte" },
      { word: "Mirassol",              hint: "Time do interior" },
      { word: "Vila Nova",             hint: "Time do Centro-Oeste" },
      { word: "CRB",                   hint: "Time do Nordeste" },
      { word: "CSA",                   hint: "Time do Nordeste" },
      { word: "Sampaio Corrêa",        hint: "Time do Nordeste" },
      { word: "Botafogo-SP",           hint: "Time do interior" },
      { word: "Novorizontino",         hint: "Time do interior" },
      { word: "Operário",              hint: "Time do interior" },
      { word: "Londrina",              hint: "Time do interior" },
      { word: "Ituano",                hint: "Time do interior" },
      { word: "Ypiranga",              hint: "Time do interior" },
      { word: "Brusque",               hint: "Time do interior" },
      { word: "ABC",                   hint: "Time do Nordeste" },
      { word: "Santa Cruz",            hint: "Time do Nordeste" },
      { word: "América-RN",            hint: "Time do Nordeste" },
      { word: "Confiança",             hint: "Time do Nordeste" },
      { word: "Amazonas",              hint: "Time do Norte" },
      { word: "Ferroviária",           hint: "Time do interior" },
      { word: "Portuguesa",            hint: "Time tradicional de SP" },
      { word: "Volta Redonda",         hint: "Time do interior" },
      { word: "Tombense",              hint: "Time do interior" },
      { word: "Paraná",                hint: "Time do sul" },
      { word: "Figueirense",           hint: "Camisa listrada" },
      { word: "Santo André",           hint: "Já foi campeão surpresa" },
      { word: "São Caetano",           hint: "Já foi mais forte" },
      { word: "Joinville",             hint: "Time do Sul" },
      { word: "Caxias",                hint: "Time do Sul" },
      { word: "Brasil de Pelotas",     hint: "Time do Sul" },
      { word: "Novo Hamburgo",         hint: "Time do Sul" },
      { word: "São José",              hint: "Time do Sul" },
      { word: "Marcílio Dias",         hint: "Time do Sul" },
      { word: "Villa Nova",            hint: "Time mineiro" },
      { word: "Caldense",              hint: "Time mineiro" },
      { word: "Ipatinga",              hint: "Time mineiro" },
      { word: "Uberlândia",            hint: "Time mineiro" },
      { word: "Tupi",                  hint: "Time mineiro" },
      { word: "Pouso Alegre",          hint: "Time mineiro" },
      { word: "Bangu",                 hint: "Time carioca tradicional" },
      { word: "Madureira",             hint: "Time carioca" },
      { word: "Nova Iguaçu",           hint: "Time carioca" },
      { word: "Olaria",                hint: "Time carioca" },
      { word: "América-RJ",            hint: "Time carioca tradicional" },
      { word: "Inter de Limeira",      hint: "Time do interior" },
      { word: "XV de Piracicaba",      hint: "Time do interior" },
      { word: "Água Santa",            hint: "Time paulista" },
      { word: "Marília",               hint: "Time do interior" },
      { word: "São Bento",             hint: "Time do interior" },
      { word: "Velo Clube",            hint: "Time do interior" },
      { word: "Noroeste",              hint: "Time do interior" },
      { word: "Oeste",                 hint: "Time do interior" },
      { word: "Treze",                 hint: "Time do Nordeste" },
      { word: "Campinense",            hint: "Time do Nordeste" },
      { word: "Botafogo-PB",           hint: "Time do Nordeste" },
      { word: "Ferroviário",           hint: "Time do Nordeste" },
      { word: "Sergipe",               hint: "Time do Nordeste" },
      { word: "Itabaiana",             hint: "Time do Nordeste" },
      { word: "ASA",                   hint: "Time do Nordeste" },
      { word: "River-PI",              hint: "Time do Nordeste" },
      { word: "Moto Club",             hint: "Time do Nordeste" },
      { word: "Imperatriz",            hint: "Time do Nordeste" },
      { word: "Retrô",                 hint: "Clube recente" },
      { word: "Manaus",                hint: "Time do Norte" },
      { word: "Nacional-AM",           hint: "Time do Norte" },
      { word: "São Raimundo",          hint: "Time do Norte" },
      { word: "Tuna Luso",             hint: "Time do Norte" },
      { word: "Castanhal",             hint: "Time do Norte" },
      { word: "Tocantinópolis",        hint: "Time do Norte" },
      { word: "Porto Velho",           hint: "Time do Norte" },
      { word: "Brasiliense",           hint: "Time da capital" },
      { word: "Gama",                  hint: "Time da capital" },
      { word: "Ceilândia",             hint: "Time da capital" },
      { word: "Aparecidense",          hint: "Time do Centro-Oeste" },
      { word: "Mixto",                 hint: "Time do Centro-Oeste" }
    ]
  },

  selecoes: {
    label: "🌎 Seleções",
    words: [
      { word: "Brasil",          hint: "Já foi campeã várias vezes" },
      { word: "Argentina",       hint: "Rival histórico do Brasil" },
      { word: "França",          hint: "Já foi campeã" },
      { word: "Alemanha",        hint: "Já foi campeã" },
      { word: "Espanha",         hint: "Já foi campeã" },
      { word: "Inglaterra",      hint: "Onde o futebol nasceu" },
      { word: "Portugal",        hint: "Fala português" },
      { word: "Itália",          hint: "Já foi campeã" },
      { word: "Uruguai",         hint: "País pequeno e tradicional" },
      { word: "Holanda",         hint: "Cor laranja" },
      { word: "Bélgica",         hint: "Teve boa geração" },
      { word: "Croácia",         hint: "Camisa quadriculada" },
      { word: "Colômbia",        hint: "Da América do Sul" },
      { word: "Chile",           hint: "Da América do Sul" },
      { word: "Paraguai",        hint: "Faz divisa com o Brasil" },
      { word: "Peru",            hint: "Da América do Sul" },
      { word: "Equador",         hint: "Da América do Sul" },
      { word: "Japão",           hint: "Bem distante" },
      { word: "Coreia do Sul",   hint: "Bem distante" },
      { word: "México",          hint: "Da América do Norte" },
      { word: "Estados Unidos",  hint: "País bem rico" },
      { word: "Canadá",          hint: "País de clima frio" },
      { word: "Costa Rica",      hint: "País pequeno" },
      { word: "Marrocos",        hint: "Surpreendeu na Copa" },
      { word: "Senegal",         hint: "Da África" },
      { word: "Nigéria",         hint: "Da África" },
      { word: "Camarões",        hint: "Da África" },
      { word: "Gana",            hint: "Da África" },
      { word: "Egito",           hint: "Tem pirâmides" },
      { word: "Austrália",       hint: "Do outro lado do mundo" },
      { word: "Suíça",           hint: "País de clima frio" },
      { word: "Dinamarca",       hint: "País de clima frio" },
      { word: "Suécia",          hint: "País de clima frio" },
      { word: "Polônia",         hint: "Do leste europeu" },
      { word: "Sérvia",          hint: "Do leste europeu" },
      { word: "Escócia",         hint: "Da Europa" },
      { word: "Turquia",         hint: "Fica entre continentes" },
      { word: "Grécia",          hint: "Já foi campeã europeia" },
      { word: "Rússia",          hint: "País bem grande" },
      { word: "Ucrânia",         hint: "Do leste europeu" },
      { word: "Áustria",         hint: "País de clima frio" },
      { word: "Noruega",         hint: "País de clima frio" },
      { word: "País de Gales",   hint: "Fala inglês" },
      { word: "Irlanda",         hint: "Da Europa" },
      { word: "Costa do Marfim", hint: "Da África" },
      { word: "Argélia",         hint: "Da África" },
      { word: "Tunísia",         hint: "Da África" },
      { word: "África do Sul",   hint: "Da África" },
      { word: "Arábia Saudita",  hint: "País do deserto" },
      { word: "Irã",             hint: "Da Ásia" },
      { word: "Catar",           hint: "Sediou uma Copa" },
      { word: "China",           hint: "País bem populoso" },
      { word: "Venezuela",       hint: "Da América do Sul" },
      { word: "Bolívia",         hint: "Joga na altitude" },
      { word: "Panamá",          hint: "Da América Central" },
      { word: "Jamaica",         hint: "Ilha do Caribe" },
      { word: "Nova Zelândia",   hint: "Da Oceania" },
      { word: "República Tcheca", hint: "Do leste europeu" },
      { word: "Eslováquia",      hint: "Do leste europeu" },
      { word: "Eslovênia",       hint: "Do leste europeu" },
      { word: "Hungria",         hint: "Do leste europeu" },
      { word: "Romênia",         hint: "Do leste europeu" },
      { word: "Bulgária",        hint: "Do leste europeu" },
      { word: "Islândia",        hint: "País de clima frio" },
      { word: "Finlândia",       hint: "País de clima frio" },
      { word: "Albânia",         hint: "Do leste europeu" },
      { word: "Macedônia do Norte", hint: "Do leste europeu" },
      { word: "Bósnia",          hint: "Do leste europeu" },
      { word: "Montenegro",      hint: "Do leste europeu" },
      { word: "Kosovo",          hint: "País bem novo" },
      { word: "Geórgia",         hint: "Fica entre continentes" },
      { word: "Armênia",         hint: "Fica entre continentes" },
      { word: "Israel",          hint: "Do Oriente Médio" },
      { word: "Chipre",          hint: "Ilha do Mediterrâneo" },
      { word: "Malta",           hint: "País bem pequeno" },
      { word: "Luxemburgo",      hint: "País bem pequeno" },
      { word: "Andorra",         hint: "País bem pequeno" },
      { word: "San Marino",      hint: "Quase nunca vence" },
      { word: "Ilhas Faroe",     hint: "País bem pequeno" },
      { word: "Estônia",         hint: "Do leste europeu" },
      { word: "Letônia",         hint: "Do leste europeu" },
      { word: "Lituânia",        hint: "Do leste europeu" },
      { word: "Moldávia",        hint: "Do leste europeu" },
      { word: "Irlanda do Norte",hint: "Fala inglês" },
      { word: "Honduras",        hint: "Da América Central" },
      { word: "Guatemala",       hint: "Da América Central" },
      { word: "El Salvador",     hint: "Da América Central" },
      { word: "Cuba",            hint: "Ilha do Caribe" },
      { word: "Haiti",           hint: "Ilha do Caribe" },
      { word: "Trinidad e Tobago", hint: "Ilha do Caribe" },
      { word: "Curaçao",         hint: "Ilha do Caribe" },
      { word: "Índia",           hint: "País bem populoso" },
      { word: "Indonésia",       hint: "País bem populoso" },
      { word: "Tailândia",       hint: "Da Ásia" },
      { word: "Vietnã",          hint: "Da Ásia" },
      { word: "Filipinas",       hint: "Da Ásia" },
      { word: "Iraque",          hint: "Do Oriente Médio" },
      { word: "Emirados Árabes", hint: "País do deserto" },
      { word: "Kuwait",          hint: "Do Oriente Médio" },
      { word: "Jordânia",        hint: "Do Oriente Médio" },
      { word: "Uzbequistão",     hint: "Da Ásia" },
      { word: "Coreia do Norte", hint: "País fechado" },
      { word: "Mali",            hint: "Da África" },
      { word: "Burkina Faso",    hint: "Da África" },
      { word: "Angola",          hint: "Fala português" },
      { word: "Moçambique",      hint: "Fala português" },
      { word: "Cabo Verde",      hint: "Fala português" }
    ]
  },

  comida: {
    label: "🍕 Comida",
    words: [
      { word: "Pizza",           hint: "Dá pra dividir" },
      { word: "Feijoada",        hint: "Prato pesado" },
      { word: "Churrasco",       hint: "Feito na brasa" },
      { word: "Coxinha",         hint: "Salgado de festa" },
      { word: "Pão de Queijo",   hint: "Melhor quentinho" },
      { word: "Brigadeiro",      hint: "Doce de festa" },
      { word: "Açaí",            hint: "Servido gelado" },
      { word: "Sushi",           hint: "Comida oriental" },
      { word: "Hambúrguer",      hint: "Lanche rápido" },
      { word: "Lasanha",         hint: "Vai ao forno" },
      { word: "Pastel",          hint: "Comprado na feira" },
      { word: "Moqueca",         hint: "Leva peixe" },
      { word: "Tapioca",         hint: "Comida do Nordeste" },
      { word: "Picanha",         hint: "Bem suculenta" },
      { word: "Sorvete",         hint: "Servido gelado" },
      { word: "Cachorro-quente", hint: "Lanche de rua" },
      { word: "Pipoca",          hint: "Combina com cinema" },
      { word: "Batata frita",    hint: "Acompanhamento comum" },
      { word: "Macarrão",        hint: "Do dia a dia" },
      { word: "Strogonoff",      hint: "Bem cremoso" },
      { word: "Escondidinho",    hint: "Leva purê" },
      { word: "Panqueca",        hint: "Vem enrolada" },
      { word: "Bolo",            hint: "Tem em aniversário" },
      { word: "Pudim",           hint: "Sobremesa clássica" },
      { word: "Beijinho",        hint: "Doce de festa" },
      { word: "Quindim",         hint: "Doce amarelinho" },
      { word: "Cuscuz",          hint: "Café da manhã nordestino" },
      { word: "Vatapá",          hint: "Prato da Bahia" },
      { word: "Acarajé",         hint: "Comida de rua baiana" },
      { word: "Baião de dois",   hint: "Prato do Nordeste" },
      { word: "Empada",          hint: "Salgado recheado" },
      { word: "Esfiha",          hint: "Salgado de padaria" },
      { word: "Kibe",            hint: "Salgado meio árabe" },
      { word: "Nhoque",          hint: "Massa italiana" },
      { word: "Risoto",          hint: "Bem cremoso" },
      { word: "Taco",            hint: "Comida mexicana" },
      { word: "Ramen",           hint: "Comida oriental" },
      { word: "Yakisoba",        hint: "Comida oriental" },
      { word: "Temaki",          hint: "Comida japonesa" },
      { word: "Paçoca",          hint: "Doce de festa junina" },
      { word: "Pé de moleque",   hint: "Doce de festa junina" },
      { word: "Rabanada",        hint: "Aparece no Natal" },
      { word: "Canjica",         hint: "Doce de festa junina" },
      { word: "Milkshake",       hint: "Bebida gelada" },
      { word: "Miojo",           hint: "Fica pronto rápido" },
      { word: "Sopa",            hint: "Servida quente" },
      { word: "Salada",          hint: "Bem leve" },
      { word: "Omelete",         hint: "Leva ovo" },
      { word: "Pão francês",     hint: "De padaria" },
      { word: "Misto-quente",    hint: "Lanche simples" },
      { word: "Waffle",          hint: "Café da manhã doce" },
      { word: "Crepe",           hint: "Massa fininha" },
      { word: "Torta",           hint: "Pode ser doce ou salgada" },
      { word: "Mousse",          hint: "Sobremesa cremosa" },
      { word: "Cocada",          hint: "Doce de coco" },
      { word: "Cajuzinho",       hint: "Doce de festa" },
      { word: "Sonho",           hint: "Doce de padaria" },
      { word: "Churros",         hint: "Doce de rua" },
      { word: "Fondue",          hint: "Come mergulhando" },
      { word: "Sanduíche",       hint: "Lanche rápido" },
      { word: "Nuggets",         hint: "Petisco de frango" },
      { word: "Costela",         hint: "Assa por horas" },
      { word: "Feijão tropeiro", hint: "Prato mineiro" },
      { word: "Pamonha",         hint: "Feita de milho" },
      { word: "Curau",           hint: "Doce de milho" },
      { word: "Bolinho de chuva",hint: "Doce fritinho" },
      { word: "Arroz",           hint: "Tem quase todo dia" },
      { word: "Feijão",          hint: "Tem quase todo dia" },
      { word: "Farofa",          hint: "Acompanhamento comum" },
      { word: "Bife",            hint: "Do dia a dia" },
      { word: "Frango assado",   hint: "Comum aos domingos" },
      { word: "Frango a passarinho", hint: "Petisco de bar" },
      { word: "Torresmo",        hint: "Petisco de bar" },
      { word: "Caldo verde",     hint: "Servido quente" },
      { word: "Canja",           hint: "Boa pra quem está doente" },
      { word: "Rabada",          hint: "Prato pesado" },
      { word: "Dobradinha",      hint: "Prato pesado" },
      { word: "Carne de sol",    hint: "Prato do Nordeste" },
      { word: "Galinhada",       hint: "Feita na panela grande" },
      { word: "Arroz carreteiro",hint: "Prato gaúcho" },
      { word: "Polenta",         hint: "Feita de milho" },
      { word: "Purê de batata",  hint: "Bem cremoso" },
      { word: "Maionese",        hint: "Acompanha churrasco" },
      { word: "Vinagrete",       hint: "Acompanha churrasco" },
      { word: "Caruru",          hint: "Prato da Bahia" },
      { word: "Bobó de camarão", hint: "Prato da Bahia" },
      { word: "Casquinha de siri",hint: "Petisco de praia" },
      { word: "Peixe frito",     hint: "Comum na praia" },
      { word: "Bacalhoada",      hint: "Aparece na Páscoa" },
      { word: "Peru de Natal",   hint: "Aparece no Natal" },
      { word: "Panetone",        hint: "Aparece no Natal" },
      { word: "Salpicão",        hint: "Aparece no Natal" },
      { word: "Pavê",            hint: "Sobremesa de Natal" },
      { word: "Parmegiana",      hint: "Leva queijo derretido" },
      { word: "Fricassê",        hint: "Bem cremoso" },
      { word: "Pão de alho",     hint: "Acompanha churrasco" },
      { word: "Linguiça",        hint: "Feita na brasa" },
      { word: "Espetinho",       hint: "Comida de rua" },
      { word: "Pernil",          hint: "Assa por horas" },
      { word: "Cupim",           hint: "Feito na brasa" },
      { word: "Hot roll",        hint: "Comida japonesa" },
      { word: "Guioza",          hint: "Comida oriental" },
      { word: "Burrito",         hint: "Comida mexicana" },
      { word: "Nachos",          hint: "Comida mexicana" },
      { word: "Guacamole",       hint: "Comida mexicana" },
      { word: "Ceviche",         hint: "Leva peixe cru" },
      { word: "Paella",          hint: "Prato espanhol" },
      { word: "Carbonara",       hint: "Massa italiana" },
      { word: "Ravióli",         hint: "Massa recheada" },
      { word: "Cheesecake",      hint: "Sobremesa gelada" },
      { word: "Brownie",         hint: "Doce de chocolate" },
      { word: "Petit gâteau",    hint: "Quente por dentro" },
      { word: "Picolé",          hint: "Servido gelado" },
      { word: "Gelatina",        hint: "Sobremesa que balança" },
      { word: "Arroz doce",      hint: "Doce de festa junina" },
      { word: "Bolo de cenoura", hint: "Tem cobertura de chocolate" }
    ]
  },

  objetos: {
    label: "🎒 Objetos",
    words: [
      { word: "Guarda-chuva",     hint: "Útil em certos dias" },
      { word: "Óculos",           hint: "Fica no rosto" },
      { word: "Celular",          hint: "Quase todo mundo tem" },
      { word: "Mochila",          hint: "Dá pra carregar coisas" },
      { word: "Relógio",          hint: "Fica no pulso" },
      { word: "Chave",            hint: "Bem pequena" },
      { word: "Espelho",          hint: "Feito de vidro" },
      { word: "Travesseiro",      hint: "Bem macio" },
      { word: "Cadeira",          hint: "Tem em toda casa" },
      { word: "Escova de dente",  hint: "Item de banheiro" },
      { word: "Fone de ouvido",   hint: "Fica na orelha" },
      { word: "Carteira",         hint: "Cabe no bolso" },
      { word: "Lanterna",         hint: "Útil no escuro" },
      { word: "Tesoura",          hint: "Bem afiada" },
      { word: "Vela",             hint: "Feita de cera" },
      { word: "Ventilador",       hint: "Bom no calor" },
      { word: "Geladeira",        hint: "Fica na cozinha" },
      { word: "Televisão",        hint: "Fica na sala" },
      { word: "Controle remoto",  hint: "Fica na mão" },
      { word: "Computador",       hint: "Usado no trabalho" },
      { word: "Teclado",          hint: "Cheio de botões" },
      { word: "Mouse",            hint: "Cabe na mão" },
      { word: "Caneta",           hint: "Cabe no bolso" },
      { word: "Lápis",            hint: "Bem simples" },
      { word: "Caderno",          hint: "Cheio de folhas" },
      { word: "Livro",            hint: "Cheio de páginas" },
      { word: "Copo",             hint: "Fica na cozinha" },
      { word: "Prato",            hint: "Fica na cozinha" },
      { word: "Garfo",            hint: "Fica na cozinha" },
      { word: "Faca",             hint: "Bem afiada" },
      { word: "Colher",           hint: "Fica na cozinha" },
      { word: "Panela",           hint: "Fica no fogão" },
      { word: "Vassoura",         hint: "Serve pra limpar" },
      { word: "Chinelo",          hint: "Vai no pé" },
      { word: "Boné",             hint: "Vai na cabeça" },
      { word: "Cinto",            hint: "Vai na cintura" },
      { word: "Anel",             hint: "Vai no dedo" },
      { word: "Colar",            hint: "Vai no pescoço" },
      { word: "Toalha",           hint: "Fica no banheiro" },
      { word: "Sabonete",         hint: "Fica no banheiro" },
      { word: "Isqueiro",         hint: "Cabe no bolso" },
      { word: "Martelo",          hint: "Ferramenta comum" },
      { word: "Régua",            hint: "Bem reta" },
      { word: "Sofá",             hint: "Fica na sala" },
      { word: "Cama",             hint: "Fica no quarto" },
      { word: "Mesa",             hint: "Tem em toda casa" },
      { word: "Abajur",           hint: "Fica no quarto" },
      { word: "Cortina",          hint: "Fica na janela" },
      { word: "Tapete",           hint: "Fica no chão" },
      { word: "Liquidificador",   hint: "Fica na cozinha" },
      { word: "Micro-ondas",      hint: "Fica na cozinha" },
      { word: "Ferro de passar",  hint: "Esquenta bastante" },
      { word: "Guarda-roupa",     hint: "Fica no quarto" },
      { word: "Cômoda",           hint: "Fica no quarto" },
      { word: "Estante",          hint: "Guarda coisas" },
      { word: "Almofada",         hint: "Bem macia" },
      { word: "Cobertor",         hint: "Bom no frio" },
      { word: "Lençol",           hint: "Fica na cama" },
      { word: "Pente",            hint: "Serve pro cabelo" },
      { word: "Secador",          hint: "Esquenta o ar" },
      { word: "Perfume",          hint: "Tem cheiro bom" },
      { word: "Batom",            hint: "Item de maquiagem" },
      { word: "Mala",             hint: "Vai em viagem" },
      { word: "Chave de fenda",   hint: "Ferramenta comum" },
      { word: "Alicate",          hint: "Ferramenta comum" },
      { word: "Prego",            hint: "Bem pequeno" },
      { word: "Balde",            hint: "Serve pra água" },
      { word: "Pano de prato",    hint: "Fica na cozinha" },
      { word: "Garrafa",          hint: "Serve pra líquidos" },
      { word: "Calculadora",      hint: "Faz contas" },
      { word: "Câmera",           hint: "Registra imagens" },
      { word: "Carregador",       hint: "Fica na tomada" },
      { word: "Óculos de sol",    hint: "Fica no rosto" },
      { word: "Chaveiro",         hint: "Bem pequeno" },
      { word: "Escada",           hint: "Serve pra subir" },
      { word: "Fogão",            hint: "Fica na cozinha" },
      { word: "Panela de pressão",hint: "Faz barulho" },
      { word: "Frigideira",       hint: "Fica no fogão" },
      { word: "Torradeira",       hint: "Fica na cozinha" },
      { word: "Cafeteira",        hint: "Usada de manhã" },
      { word: "Garrafa térmica",  hint: "Mantém a temperatura" },
      { word: "Peneira",          hint: "Fica na cozinha" },
      { word: "Ralador",          hint: "Fica na cozinha" },
      { word: "Tábua de corte",   hint: "Fica na cozinha" },
      { word: "Abridor de latas", hint: "Fica na gaveta" },
      { word: "Avental",          hint: "Usado na cozinha" },
      { word: "Guardanapo",       hint: "Fica na mesa" },
      { word: "Canudo",           hint: "Serve pra beber" },
      { word: "Palito de dente",  hint: "Bem pequeno" },
      { word: "Lixeira",          hint: "Tem em toda casa" },
      { word: "Rodo",             hint: "Serve pra limpar" },
      { word: "Esponja",          hint: "Fica na pia" },
      { word: "Detergente",       hint: "Fica na pia" },
      { word: "Varal",            hint: "Fica na área de serviço" },
      { word: "Pregador de roupa",hint: "Bem pequeno" },
      { word: "Cabide",           hint: "Fica no guarda-roupa" },
      { word: "Aspirador de pó",  hint: "Faz barulho" },
      { word: "Máquina de lavar", hint: "Fica na área de serviço" },
      { word: "Chuveiro",         hint: "Fica no banheiro" },
      { word: "Papel higiênico",  hint: "Fica no banheiro" },
      { word: "Shampoo",          hint: "Fica no banheiro" },
      { word: "Cotonete",         hint: "Bem pequeno" },
      { word: "Esmalte",          hint: "Bem colorido" },
      { word: "Grampeador",       hint: "Fica na mesa" },
      { word: "Borracha",         hint: "Material escolar" },
      { word: "Apontador",        hint: "Material escolar" },
      { word: "Estojo",           hint: "Material escolar" },
      { word: "Cola",             hint: "Material escolar" },
      { word: "Fita adesiva",     hint: "Fica na gaveta" },
      { word: "Pilha",            hint: "Dá energia" },
      { word: "Lâmpada",          hint: "Ilumina a casa" },
      { word: "Interruptor",      hint: "Fica na parede" },
      { word: "Quadro",           hint: "Fica na parede" },
      { word: "Porta-retrato",    hint: "Fica na estante" },
      { word: "Vaso de planta",   hint: "Precisa de água" },
      { word: "Rede",             hint: "Boa pra descansar" },
      { word: "Bicicleta",        hint: "Tem duas rodas" },
      { word: "Bola",             hint: "Usada pra brincar" },
      { word: "Baralho",          hint: "Usado em jogos" },
      { word: "Dado",             hint: "Usado em jogos" },
      { word: "Violão",           hint: "Faz som" },
      { word: "Binóculo",         hint: "Serve pra ver longe" },
      { word: "Cadeado",          hint: "Bem pequeno" },
      { word: "Trena",            hint: "Serve pra medir" }
    ]
  },

  profissoes: {
    label: "👷 Profissões",
    words: [
      { word: "Médico",          hint: "Estudou muitos anos" },
      { word: "Professor",       hint: "Trabalha explicando" },
      { word: "Bombeiro",        hint: "Trabalho arriscado" },
      { word: "Advogado",        hint: "Usa terno" },
      { word: "Cozinheiro",      hint: "Trabalha em pé" },
      { word: "Policial",        hint: "Usa uniforme" },
      { word: "Piloto",          hint: "Trabalha viajando" },
      { word: "Dentista",        hint: "Trabalha sentado" },
      { word: "Eletricista",     hint: "Trabalha com as mãos" },
      { word: "Jornalista",      hint: "Vive informado" },
      { word: "Cabeleireiro",    hint: "Trabalha com as mãos" },
      { word: "Engenheiro",      hint: "Bom em cálculos" },
      { word: "Enfermeiro",      hint: "Ajuda os doentes" },
      { word: "Fotógrafo",       hint: "Trabalho criativo" },
      { word: "Garçom",          hint: "Trabalha em pé" },
      { word: "Arquiteto",       hint: "Trabalho criativo" },
      { word: "Pintor",          hint: "Trabalha com as mãos" },
      { word: "Pedreiro",        hint: "Trabalho pesado" },
      { word: "Encanador",       hint: "Trabalha com as mãos" },
      { word: "Mecânico",        hint: "Fica meio sujo" },
      { word: "Motorista",       hint: "Trabalha na rua" },
      { word: "Padeiro",         hint: "Acorda cedo" },
      { word: "Açougueiro",      hint: "Trabalha com as mãos" },
      { word: "Vendedor",        hint: "Fala com muita gente" },
      { word: "Contador",        hint: "Trabalha com números" },
      { word: "Programador",     hint: "Trabalha no computador" },
      { word: "Designer",        hint: "Trabalho criativo" },
      { word: "Veterinário",     hint: "Gosta de animais" },
      { word: "Farmacêutico",    hint: "Trabalha numa loja" },
      { word: "Psicólogo",       hint: "Sabe escutar" },
      { word: "Nutricionista",   hint: "Entende de comida" },
      { word: "Juiz",            hint: "Usa toga" },
      { word: "Delegado",        hint: "Trabalho sério" },
      { word: "Soldado",         hint: "Usa farda" },
      { word: "Astronauta",      hint: "Profissão rara" },
      { word: "Cientista",       hint: "Vive pesquisando" },
      { word: "Biólogo",         hint: "Estuda a natureza" },
      { word: "Escritor",        hint: "Trabalha escrevendo" },
      { word: "Ator",            hint: "Aparece em cena" },
      { word: "Cantor",          hint: "Trabalha com a voz" },
      { word: "Músico",          hint: "Trabalha com som" },
      { word: "Dançarino",       hint: "Trabalha com o corpo" },
      { word: "Modelo",          hint: "Aparece bastante" },
      { word: "Costureira",      hint: "Trabalha com as mãos" },
      { word: "Jardineiro",      hint: "Trabalha ao ar livre" },
      { word: "Agricultor",      hint: "Trabalha ao ar livre" },
      { word: "Pescador",        hint: "Trabalha perto da água" },
      { word: "Carteiro",        hint: "Anda bastante" },
      { word: "Segurança",       hint: "Fica de olho" },
      { word: "Barbeiro",        hint: "Trabalha com as mãos" },
      { word: "Confeiteiro",     hint: "Trabalha com doces" },
      { word: "Árbitro",         hint: "Trabalha apitando" },
      { word: "Recepcionista",   hint: "Atende as pessoas" },
      { word: "Caixa",           hint: "Trabalha numa loja" },
      { word: "Faxineiro",       hint: "Deixa tudo limpo" },
      { word: "Porteiro",        hint: "Fica na entrada" },
      { word: "Taxista",         hint: "Trabalha dirigindo" },
      { word: "Entregador",      hint: "Trabalha na rua" },
      { word: "Marinheiro",      hint: "Trabalha na água" },
      { word: "Salva-vidas",     hint: "Fica de olho na água" },
      { word: "Comissário de bordo", hint: "Trabalha voando" },
      { word: "Cirurgião",       hint: "Área da saúde" },
      { word: "Pediatra",        hint: "Cuida de crianças" },
      { word: "Historiador",     hint: "Estuda o passado" },
      { word: "Tradutor",        hint: "Trabalha com idiomas" },
      { word: "Locutor",         hint: "Trabalha com a voz" },
      { word: "Palhaço",         hint: "Faz as pessoas rirem" },
      { word: "Mágico",          hint: "Faz truques" },
      { word: "Manicure",        hint: "Cuida das unhas" },
      { word: "Sapateiro",       hint: "Conserta calçados" },
      { word: "Marceneiro",      hint: "Trabalha com madeira" },
      { word: "Frentista",       hint: "Trabalha no posto" },
      { word: "Detetive",        hint: "Vive investigando" },
      { word: "Maquiador",       hint: "Trabalho criativo" },
      { word: "Fisioterapeuta",  hint: "Área da saúde" },
      { word: "Fonoaudiólogo",   hint: "Trabalha com a voz" },
      { word: "Oftalmologista",  hint: "Cuida dos olhos" },
      { word: "Dermatologista",  hint: "Área da saúde" },
      { word: "Psiquiatra",      hint: "Área da saúde" },
      { word: "Anestesista",     hint: "Área da saúde" },
      { word: "Parteira",        hint: "Área da saúde" },
      { word: "Massagista",      hint: "Trabalha com as mãos" },
      { word: "Personal trainer",hint: "Trabalha com o corpo" },
      { word: "Treinador",       hint: "Trabalha com esporte" },
      { word: "Jogador de futebol", hint: "Trabalha com esporte" },
      { word: "Piloto de corrida",  hint: "Trabalho arriscado" },
      { word: "Bibliotecário",   hint: "Trabalha em silêncio" },
      { word: "Secretária",      hint: "Organiza a agenda" },
      { word: "Bancário",        hint: "Trabalha com dinheiro" },
      { word: "Corretor de imóveis", hint: "Fala com muita gente" },
      { word: "Empresário",      hint: "Toma decisões" },
      { word: "Economista",      hint: "Trabalha com números" },
      { word: "Publicitário",    hint: "Trabalho criativo" },
      { word: "Cineasta",        hint: "Trabalha com filmes" },
      { word: "Roteirista",      hint: "Trabalha escrevendo" },
      { word: "Cartunista",      hint: "Trabalha desenhando" },
      { word: "Ilustrador",      hint: "Trabalha desenhando" },
      { word: "Escultor",        hint: "Trabalha com as mãos" },
      { word: "Poeta",           hint: "Trabalha escrevendo" },
      { word: "Compositor",      hint: "Trabalha com música" },
      { word: "DJ",              hint: "Trabalha à noite" },
      { word: "Apresentador",    hint: "Aparece bastante" },
      { word: "Repórter",        hint: "Vive informado" },
      { word: "Cinegrafista",    hint: "Trabalha com imagens" },
      { word: "Youtuber",        hint: "Trabalha na internet" },
      { word: "Influenciador",   hint: "Trabalha na internet" },
      { word: "Maquinista",      hint: "Trabalha viajando" },
      { word: "Metalúrgico",     hint: "Trabalho pesado" },
      { word: "Soldador",        hint: "Trabalha com metal" },
      { word: "Serralheiro",     hint: "Trabalha com metal" },
      { word: "Vidraceiro",      hint: "Trabalha com cuidado" },
      { word: "Agrônomo",        hint: "Trabalha no campo" },
      { word: "Vaqueiro",        hint: "Trabalha no campo" },
      { word: "Lenhador",        hint: "Trabalho pesado" },
      { word: "Guia turístico",  hint: "Anda bastante" },
      { word: "Camareira",       hint: "Trabalha num hotel" },
      { word: "Zelador",         hint: "Cuida do prédio" },
      { word: "Gari",            hint: "Deixa tudo limpo" },
      { word: "Tatuador",        hint: "Trabalho criativo" },
      { word: "Joalheiro",       hint: "Trabalho minucioso" },
      { word: "Relojoeiro",      hint: "Trabalho minucioso" },
      { word: "Sommelier",       hint: "Entende de bebidas" },
      { word: "Bartender",       hint: "Trabalha à noite" },
      { word: "Sorveteiro",      hint: "Trabalha na rua" }
    ]
  },

  animais: {
    label: "🐾 Animais",
    words: [
      { word: "Elefante",     hint: "Bem pesado" },
      { word: "Girafa",       hint: "Come folhas" },
      { word: "Leão",         hint: "Vive em bando" },
      { word: "Jacaré",       hint: "Vive perto da água" },
      { word: "Tartaruga",    hint: "Anda devagar" },
      { word: "Papagaio",     hint: "Tem penas coloridas" },
      { word: "Canguru",      hint: "Dá saltos" },
      { word: "Golfinho",     hint: "Vive no mar" },
      { word: "Águia",        hint: "Voa alto" },
      { word: "Coruja",       hint: "Sai de noite" },
      { word: "Camelo",       hint: "Aguenta o calor" },
      { word: "Pinguim",      hint: "Aguenta o frio" },
      { word: "Zebra",        hint: "Vive na savana" },
      { word: "Urso",         hint: "Bem grandão" },
      { word: "Macaco",       hint: "Sobe em árvores" },
      { word: "Tigre",        hint: "Caçador solitário" },
      { word: "Leopardo",     hint: "Corre bastante" },
      { word: "Onça",         hint: "Vive na mata" },
      { word: "Lobo",         hint: "Vive em bando" },
      { word: "Raposa",       hint: "Bem esperta" },
      { word: "Cavalo",       hint: "Corre bastante" },
      { word: "Vaca",         hint: "Vive na fazenda" },
      { word: "Porco",        hint: "Vive na fazenda" },
      { word: "Ovelha",       hint: "Vive na fazenda" },
      { word: "Cabra",        hint: "Vive na fazenda" },
      { word: "Galinha",      hint: "Vive no galinheiro" },
      { word: "Pato",         hint: "Gosta de água" },
      { word: "Cachorro",     hint: "Bem comum em casa" },
      { word: "Gato",         hint: "Bem comum em casa" },
      { word: "Coelho",       hint: "Pula bastante" },
      { word: "Rato",         hint: "Bem pequeno" },
      { word: "Esquilo",      hint: "Sobe em árvores" },
      { word: "Hipopótamo",   hint: "Fica na água" },
      { word: "Rinoceronte",  hint: "Bem pesado" },
      { word: "Gorila",       hint: "Bem forte" },
      { word: "Panda",        hint: "Come bambu" },
      { word: "Coala",        hint: "Vive em árvores" },
      { word: "Preguiça",     hint: "Bem lenta" },
      { word: "Tamanduá",     hint: "Tem língua comprida" },
      { word: "Tatu",         hint: "Tem casco duro" },
      { word: "Capivara",     hint: "Vive perto da água" },
      { word: "Foca",         hint: "Vive no mar" },
      { word: "Baleia",       hint: "Bem enorme" },
      { word: "Tubarão",      hint: "Vive no mar" },
      { word: "Polvo",        hint: "Vive no mar" },
      { word: "Caranguejo",   hint: "Anda de lado" },
      { word: "Cobra",        hint: "Rasteja" },
      { word: "Lagarto",      hint: "Gosta do sol" },
      { word: "Sapo",         hint: "Vive perto da água" },
      { word: "Aranha",       hint: "Faz teia" },
      { word: "Abelha",       hint: "Faz zumbido" },
      { word: "Borboleta",    hint: "Tem asas coloridas" },
      { word: "Formiga",      hint: "Vive em grupo" },
      { word: "Escorpião",    hint: "Tem ferrão" },
      { word: "Morcego",      hint: "Sai de noite" },
      { word: "Pavão",        hint: "Tem penas bonitas" },
      { word: "Flamingo",     hint: "Fica numa perna só" },
      { word: "Cisne",        hint: "Nada com elegância" },
      { word: "Avestruz",     hint: "Corre muito" },
      { word: "Tucano",       hint: "Tem bico grande" },
      { word: "Beija-flor",   hint: "Bem pequenininho" },
      { word: "Cervo",        hint: "Vive na floresta" },
      { word: "Guaxinim",     hint: "Bem esperto" },
      { word: "Suricato",     hint: "Fica em pé vigiando" },
      { word: "Hiena",        hint: "Vive em bando" },
      { word: "Búfalo",       hint: "Bem pesado" },
      { word: "Alce",         hint: "Vive no frio" },
      { word: "Rena",         hint: "Vive no frio" },
      { word: "Lhama",        hint: "Bem peludo" },
      { word: "Burro",        hint: "Parece cavalo" },
      { word: "Camaleão",     hint: "Muda de cor" },
      { word: "Iguana",       hint: "Gosta do sol" },
      { word: "Peixe",        hint: "Vive na água" },
      { word: "Cavalo-marinho",hint: "Vive no mar" },
      { word: "Lagosta",      hint: "Vive no mar" },
      { word: "Camarão",      hint: "Vive na água" },
      { word: "Caracol",      hint: "Anda devagar" },
      { word: "Gafanhoto",    hint: "Dá saltos" },
      { word: "Joaninha",     hint: "Bem pequenininha" },
      { word: "Mosca",        hint: "Voa por aí" },
      { word: "Vaga-lume",    hint: "Brilha no escuro" },
      { word: "Codorna",      hint: "Bem pequena" },
      { word: "Pombo",        hint: "Vive na cidade" },
      { word: "Arara",        hint: "Tem penas coloridas" },
      { word: "Guepardo",     hint: "Corre muito rápido" },
      { word: "Lontra",       hint: "Vive perto da água" },
      { word: "Ouriço",       hint: "Cheio de espinhos" },
      { word: "Anta",         hint: "Vive na mata" },
      { word: "Quati",        hint: "Bem esperto" },
      { word: "Mico",         hint: "Sobe em árvores" },
      { word: "Lobo-guará",   hint: "Tem pernas compridas" },
      { word: "Jaguatirica",  hint: "Vive na mata" },
      { word: "Cutia",        hint: "Bem pequena" },
      { word: "Paca",         hint: "Vive na mata" },
      { word: "Gambá",        hint: "Tem cheiro forte" },
      { word: "Ornitorrinco", hint: "Bem diferente" },
      { word: "Hamster",      hint: "Bem comum em casa" },
      { word: "Porquinho-da-índia", hint: "Bem pequeno" },
      { word: "Furão",        hint: "Bem esperto" },
      { word: "Castor",       hint: "Rói bastante" },
      { word: "Toupeira",     hint: "Vive embaixo da terra" },
      { word: "Javali",       hint: "Parece porco" },
      { word: "Bode",         hint: "Vive na fazenda" },
      { word: "Carneiro",     hint: "Vive na fazenda" },
      { word: "Touro",        hint: "Bem forte" },
      { word: "Pônei",        hint: "Parece cavalo" },
      { word: "Mula",         hint: "Carrega peso" },
      { word: "Galo",         hint: "Acorda cedo" },
      { word: "Peru",         hint: "Aparece no Natal" },
      { word: "Pelicano",     hint: "Tem bico grande" },
      { word: "Gaivota",      hint: "Vive perto do mar" },
      { word: "Falcão",       hint: "Voa alto" },
      { word: "Gavião",       hint: "Caça do alto" },
      { word: "Urubu",        hint: "Voa em círculos" },
      { word: "Corvo",        hint: "Bem escuro" },
      { word: "Canário",      hint: "Canta bastante" },
      { word: "Periquito",    hint: "Tem penas coloridas" },
      { word: "Calopsita",    hint: "Bem comum em casa" },
      { word: "Sabiá",        hint: "Canta bonito" },
      { word: "Garça",        hint: "Fica perto da água" },
      { word: "Pica-pau",     hint: "Faz barulho na árvore" },
      { word: "Andorinha",    hint: "Voa em bando" },
      { word: "Pardal",       hint: "Vive na cidade" },
      { word: "Ema",          hint: "Corre bastante" },
      { word: "Piranha",      hint: "Vive em rios" },
      { word: "Pirarucu",     hint: "Peixe bem grande" },
      { word: "Salmão",       hint: "Nada contra a corrente" },
      { word: "Atum",         hint: "Vive no mar" },
      { word: "Sardinha",     hint: "Anda em cardume" },
      { word: "Enguia",       hint: "Parece cobra" },
      { word: "Arraia",       hint: "Vive no fundo" },
      { word: "Água-viva",    hint: "Melhor não encostar" },
      { word: "Estrela-do-mar",hint: "Vive no fundo" },
      { word: "Lula",         hint: "Vive no mar" },
      { word: "Orca",         hint: "Vive no mar" },
      { word: "Peixe-boi",    hint: "Bem calmo" },
      { word: "Jabuti",       hint: "Anda devagar" }
    ]
  },

  filmes_series: {
    label: "🎥 Filmes e Séries",
    words: [
      { word: "Titanic",                    hint: "Baseado em fato real" },
      { word: "Vingadores",                 hint: "Tem vários heróis juntos" },
      { word: "Homem-Aranha",               hint: "Tem poderes de aranha" },
      { word: "Batman",                     hint: "Não tem poderes de verdade" },
      { word: "Superman",                   hint: "Vem de outro planeta" },
      { word: "Coringa",                    hint: "É um vilão famoso" },
      { word: "Star Wars",                  hint: "Se passa no espaço" },
      { word: "Harry Potter",               hint: "Tem magia" },
      { word: "Senhor dos Anéis",           hint: "Tem magia" },
      { word: "Jurassic Park",              hint: "Tem dinossauros" },
      { word: "Matrix",                     hint: "Mexe com a realidade" },
      { word: "Velozes e Furiosos",         hint: "Tem muitos carros" },
      { word: "Missão Impossível",          hint: "Cheio de ação" },
      { word: "007",                        hint: "É um agente secreto" },
      { word: "Rocky",                      hint: "É sobre boxe" },
      { word: "O Exterminador do Futuro",   hint: "Tem robôs" },
      { word: "Duro de Matar",              hint: "Cheio de ação" },
      { word: "Alien",                      hint: "Se passa no espaço" },
      { word: "Predador",                   hint: "Se passa na selva" },
      { word: "Tubarão",                    hint: "Se passa no mar" },
      { word: "E.T.",                       hint: "Vem de outro planeta" },
      { word: "De Volta para o Futuro",     hint: "Mexe com o tempo" },
      { word: "Karatê Kid",                 hint: "Envolve luta" },
      { word: "Forrest Gump",               hint: "Conta uma vida inteira" },
      { word: "O Poderoso Chefão",          hint: "Fala de máfia" },
      { word: "Pantera Negra",              hint: "Tem um super-herói" },
      { word: "Doutor Estranho",            hint: "Tem magia" },
      { word: "Homem de Ferro",             hint: "Usa uma armadura" },
      { word: "Capitão América",            hint: "Usa um escudo" },
      { word: "Thor",                       hint: "Usa um martelo" },
      { word: "Cidade de Deus",             hint: "É brasileiro" },
      { word: "Tropa de Elite",             hint: "É brasileiro" },
      { word: "Central do Brasil",          hint: "É brasileiro" },
      { word: "Bacurau",                    hint: "É brasileiro" },
      { word: "Minha Mãe é uma Peça",       hint: "É brasileiro" },
      { word: "Se Eu Fosse Você",           hint: "É brasileiro" },
      { word: "Meu Passado me Condena",     hint: "É brasileiro" },
      { word: "Carandiru",                  hint: "É brasileiro" },
      { word: "Auto da Compadecida",        hint: "É brasileiro" },
      { word: "Lisbela e o Prisioneiro",    hint: "É brasileiro" },
      { word: "Toy Story",                  hint: "É uma animação" },
      { word: "Shrek",                      hint: "É uma animação" },
      { word: "Procurando Nemo",            hint: "É uma animação" },
      { word: "Divertida Mente",            hint: "É uma animação" },
      { word: "Frozen",                     hint: "É uma animação" },
      { word: "Rei Leão",                   hint: "É uma animação" },
      { word: "Moana",                      hint: "É uma animação" },
      { word: "Enrolados",                  hint: "É uma animação" },
      { word: "Zootopia",                   hint: "É uma animação" },
      { word: "Coco",                       hint: "É uma animação" },
      { word: "Up - Altas Aventuras",       hint: "É uma animação" },
      { word: "Carros",                     hint: "É uma animação" },
      { word: "Madagascar",                 hint: "É uma animação" },
      { word: "Kung Fu Panda",              hint: "É uma animação" },
      { word: "Como Treinar o Seu Dragão",  hint: "É uma animação" },
      { word: "Friends",                    hint: "É uma série de comédia" },
      { word: "Breaking Bad",               hint: "É uma série dramática" },
      { word: "Game of Thrones",            hint: "Tem dragões" },
      { word: "Stranger Things",            hint: "Tem algo sobrenatural" },
      { word: "The Office",                 hint: "É uma série de comédia" },
      { word: "Round 6",                    hint: "É uma série coreana" },
      { word: "The Walking Dead",           hint: "Tem zumbis" },
      { word: "Grey's Anatomy",             hint: "Se passa num hospital" },
      { word: "CSI",                        hint: "É investigativo" },
      { word: "Lost",                       hint: "Se passa numa ilha" },
      { word: "Prison Break",               hint: "Se passa numa prisão" },
      { word: "How I Met Your Mother",      hint: "É uma série de comédia" },
      { word: "The Big Bang Theory",        hint: "É uma série de comédia" },
      { word: "House",                      hint: "Se passa num hospital" },
      { word: "Dexter",                     hint: "Segue um assassino" },
      { word: "Sherlock",                   hint: "É investigativo" },
      { word: "Peaky Blinders",             hint: "Envolve máfia" },
      { word: "The Crown",                  hint: "Fala da realeza" },
      { word: "Vikings",                    hint: "Envolve guerreiros antigos" },
      { word: "Suits",                      hint: "Envolve advogados" },
      { word: "Chaves",                     hint: "É antigo e engraçado" },
      { word: "Sítio do Picapau Amarelo",   hint: "É infantil" },
      { word: "Cavaleiros do Zodíaco",      hint: "É um anime antigo" },
      { word: "Avenida Brasil",             hint: "É uma novela" },
      { word: "A Grande Família",           hint: "É uma série de comédia" },
      { word: "Malhação",                   hint: "É uma novela" },
      { word: "Zorra Total",                hint: "É de comédia" },
      { word: "Vai Que Cola",               hint: "É de comédia" },
      { word: "Pantanal",                   hint: "É uma novela" },
      { word: "Laços de Família",           hint: "É uma novela" },
      { word: "O Clone",                    hint: "É uma novela" },
      { word: "Escrava Isaura",             hint: "É uma novela" },
      { word: "Roque Santeiro",             hint: "É uma novela" },
      { word: "A Diarista",                 hint: "É de comédia" },
      { word: "Sai de Baixo",               hint: "É de comédia" },
      { word: "Naruto",                     hint: "É um anime" },
      { word: "Dragon Ball",                hint: "É um anime" },
      { word: "One Piece",                  hint: "É um anime" },
      { word: "Pokémon",                    hint: "É um anime" },
      { word: "Death Note",                 hint: "É um anime" },
      { word: "Attack on Titan",            hint: "É um anime" },
      { word: "My Hero Academia",           hint: "É um anime" },
      { word: "Demon Slayer",               hint: "É um anime" },
      { word: "Sailor Moon",                hint: "É um anime" },
      { word: "Digimon",                    hint: "É um anime" },
      { word: "O Silêncio dos Inocentes",   hint: "É de suspense" },
      { word: "Psicose",                    hint: "É de suspense" },
      { word: "O Iluminado",                hint: "É de terror" },
      { word: "Invocação do Mal",           hint: "É de terror" },
      { word: "Pânico",                     hint: "É de terror" },
      { word: "Grease",                     hint: "É um musical" },
      { word: "La La Land",                 hint: "É um musical" },
      { word: "Mamma Mia",                  hint: "É um musical" },
      { word: "Bridgerton",                 hint: "É uma série de romance" }
    ]
  },

  marcas: {
    label: "🏷️ Marcas",
    words: [
      { word: "Apple",           hint: "Faz celulares" },
      { word: "Samsung",         hint: "Faz celulares" },
      { word: "Google",          hint: "É uma empresa de tecnologia" },
      { word: "Microsoft",       hint: "Faz sistemas operacionais" },
      { word: "Amazon",          hint: "Vende de tudo online" },
      { word: "Meta",            hint: "É dona de redes sociais" },
      { word: "Sony",            hint: "Faz eletrônicos" },
      { word: "LG",              hint: "Faz eletrônicos" },
      { word: "Xiaomi",          hint: "Faz celulares" },
      { word: "Motorola",        hint: "Faz celulares" },
      { word: "Dell",            hint: "Faz computadores" },
      { word: "HP",              hint: "Faz computadores" },
      { word: "Lenovo",          hint: "Faz computadores" },
      { word: "Asus",            hint: "Faz computadores" },
      { word: "Intel",           hint: "Faz processadores" },
      { word: "Nvidia",          hint: "Faz placas de vídeo" },
      { word: "Netflix",         hint: "É de streaming" },
      { word: "Spotify",         hint: "É de streaming de música" },
      { word: "TikTok",          hint: "É uma rede social" },
      { word: "Instagram",       hint: "É uma rede social" },
      { word: "WhatsApp",        hint: "É um aplicativo de mensagens" },
      { word: "YouTube",         hint: "É de vídeos" },
      { word: "Twitter",         hint: "É uma rede social" },
      { word: "LinkedIn",        hint: "É uma rede social profissional" },
      { word: "Uber",            hint: "Serve pra pedir carro" },
      { word: "iFood",           hint: "Serve pra pedir comida" },
      { word: "Nubank",          hint: "É um banco digital" },
      { word: "PicPay",          hint: "É um banco digital" },
      { word: "Mercado Livre",   hint: "Vende de tudo online" },
      { word: "Shopee",          hint: "Vende de tudo online" },
      { word: "Coca-Cola",       hint: "É um refrigerante" },
      { word: "Pepsi",           hint: "É um refrigerante" },
      { word: "Guaraná Antarctica", hint: "É um refrigerante" },
      { word: "Fanta",           hint: "É um refrigerante" },
      { word: "Sprite",          hint: "É um refrigerante" },
      { word: "Red Bull",        hint: "É energético" },
      { word: "Heineken",        hint: "É uma cerveja" },
      { word: "Skol",            hint: "É uma cerveja" },
      { word: "Brahma",          hint: "É uma cerveja" },
      { word: "Itaipava",        hint: "É uma cerveja" },
      { word: "Nescafé",         hint: "É de café" },
      { word: "Nestlé",          hint: "Faz vários alimentos" },
      { word: "Danone",          hint: "Faz iogurte" },
      { word: "Doritos",         hint: "É um salgadinho" },
      { word: "Ruffles",         hint: "É um salgadinho" },
      { word: "Lay's",           hint: "É um salgadinho" },
      { word: "Bauducco",        hint: "Faz panetone" },
      { word: "Nutella",         hint: "É um creme de avelã" },
      { word: "Kit Kat",         hint: "É um chocolate" },
      { word: "Bis",             hint: "É um chocolate" },
      { word: "Trident",         hint: "É um chiclete" },
      { word: "Halls",           hint: "É uma bala" },
      { word: "Toddy",           hint: "É achocolatado" },
      { word: "Nescau",          hint: "É achocolatado" },
      { word: "Sadia",           hint: "Faz frango" },
      { word: "Perdigão",        hint: "Faz frango" },
      { word: "Seara",           hint: "Faz frango" },
      { word: "Oreo",            hint: "É um biscoito" },
      { word: "M&M's",           hint: "É um chocolate colorido" },
      { word: "Snickers",        hint: "É um chocolate" },
      { word: "Nike",            hint: "Faz tênis" },
      { word: "Adidas",          hint: "Faz tênis" },
      { word: "Puma",            hint: "Faz tênis" },
      { word: "Reebok",          hint: "Faz tênis" },
      { word: "Vans",            hint: "Faz tênis" },
      { word: "Havaianas",       hint: "Faz chinelo" },
      { word: "Zara",            hint: "Vende roupas" },
      { word: "C&A",             hint: "Vende roupas" },
      { word: "Renner",          hint: "Vende roupas" },
      { word: "Riachuelo",       hint: "Vende roupas" },
      { word: "Levi's",          hint: "Faz jeans" },
      { word: "Ray-Ban",         hint: "Faz óculos" },
      { word: "Chanel",          hint: "É de luxo" },
      { word: "Gucci",           hint: "É de luxo" },
      { word: "Louis Vuitton",   hint: "É de luxo" },
      { word: "Rolex",           hint: "Faz relógios" },
      { word: "Calvin Klein",    hint: "Vende roupas" },
      { word: "Lacoste",         hint: "Tem um jacaré no logo" },
      { word: "Hering",          hint: "Vende roupas" },
      { word: "Track & Field",   hint: "Vende roupas esportivas" },
      { word: "Ferrari",         hint: "Faz carros esportivos" },
      { word: "Lamborghini",     hint: "Faz carros esportivos" },
      { word: "Volkswagen",      hint: "Faz carros" },
      { word: "Chevrolet",       hint: "Faz carros" },
      { word: "Fiat",            hint: "Faz carros" },
      { word: "Ford",            hint: "Faz carros" },
      { word: "Toyota",          hint: "Faz carros" },
      { word: "Honda",           hint: "Faz carros e motos" },
      { word: "Hyundai",         hint: "Faz carros" },
      { word: "Renault",         hint: "Faz carros" },
      { word: "Nissan",          hint: "Faz carros" },
      { word: "BMW",             hint: "Faz carros" },
      { word: "Mercedes-Benz",   hint: "Faz carros de luxo" },
      { word: "Audi",            hint: "Faz carros" },
      { word: "Porsche",         hint: "Faz carros esportivos" },
      { word: "Jeep",            hint: "Faz carros" },
      { word: "Volvo",           hint: "Faz carros" },
      { word: "Peugeot",         hint: "Faz carros" },
      { word: "Citroën",         hint: "Faz carros" },
      { word: "Kia",             hint: "Faz carros" },
      { word: "McDonald's",      hint: "Vende lanches" },
      { word: "Burger King",     hint: "Vende lanches" },
      { word: "KFC",             hint: "Vende frango frito" },
      { word: "Subway",          hint: "Vende sanduíches" },
      { word: "Habib's",         hint: "Vende esfihas" },
      { word: "Bob's",           hint: "Vende lanches" },
      { word: "Outback",         hint: "É um restaurante" },
      { word: "Starbucks",       hint: "Vende café" },
      { word: "Casas Bahia",     hint: "Vende eletrodomésticos" },
      { word: "Magazine Luiza",  hint: "Vende de tudo" },
      { word: "Americanas",      hint: "Vende de tudo" },
      { word: "Carrefour",       hint: "É um supermercado" },
      { word: "Pão de Açúcar",   hint: "É um supermercado" },
      { word: "Latam",           hint: "É uma companhia aérea" },
      { word: "Gol",             hint: "É uma companhia aérea" },
      { word: "Azul",            hint: "É uma companhia aérea" },
      { word: "PlayStation",     hint: "É um videogame" },
      { word: "Xbox",            hint: "É um videogame" },
      { word: "Nintendo",        hint: "É um videogame" },
      { word: "Lego",            hint: "São blocos de montar" },
      { word: "Barbie",          hint: "É uma boneca" },
      { word: "Colgate",         hint: "Faz pasta de dente" },
      { word: "Gillette",        hint: "Faz lâminas de barbear" },
      { word: "Duracell",        hint: "Faz pilhas" },
      { word: "Brastemp",        hint: "Faz eletrodomésticos" }
    ]
  }

};

// ============================================================
//  FAMÍLIAS DE DICAS (usadas no modo Encontre sua Dupla)
//
//  No modo Dupla, todas as palavras da rodada saem de uma mesma
//  "família" — palavras próximas entre si (ex.: só comida japonesa,
//  só goleiros, só times do interior). Assim fica difícil separar
//  as duplas só pelo assunto, e o jogo fica mais interessante.
//
//  Cada família é uma lista de dicas que "andam juntas". Palavras
//  cujas dicas não aparecem aqui se agrupam automaticamente com
//  outras que tenham a MESMA dica — então palavras novas entram
//  no esquema sem precisar mexer nesta tabela (basta reaproveitar
//  dicas existentes ou adicionar a dica nova numa família).
// ============================================================

const HINT_FAMILIES = {

  brasileirao_jogadores: [
    ["Joga no gol", "Joga com luvas", "Goleiro veterano"],
    ["Joga na frente", "Faz gols", "Fazia muitos gols", "Fez gol importante", "Bom de cabeça"],
    ["Joga no meio", "É volante", "Meia experiente", "Meia veterano", "Dá bons passes"],
    ["Joga na defesa", "Joga na lateral"],
    ["É jovem", "É bem jovem", "É muito novo", "É uma promessa"],
    ["Já é experiente", "Já é veterano", "Bem experiente", "Um dos mais velhos"],
    ["É rápido", "É veloz", "Corre bastante", "Gosta de driblar", "É habilidoso"],
    ["Chuta bem", "Chuta forte", "Chuta de canhota", "Bate pênaltis"],
    ["É baixinho", "É bem baixinho"],
    ["Jogou na Europa", "Voltou da Europa", "Jogou longe do Brasil", "Já jogou fora"],
    ["É bem intenso", "Vive em polêmica", "Tem apelido curioso", "Tem nome curioso", "É bem forte"]
  ],

  jogadores_famosos: [
    ["Joga no gol", "Jogava no gol"],
    ["Joga na defesa", "Jogava na defesa", "Joga na lateral", "Jogava na lateral", "Cruza muito bem"],
    ["Joga no meio", "É volante", "Dava muitos passes", "Dava belos passes", "Dá muitas assistências", "Batia bem as faltas"],
    ["Faz muitos gols", "Fazia muitos gols", "Fez muitos gols", "Bom de finalização", "Baixinho e goleador"],
    ["Ídolo antigo", "Ídolo de um clube só", "Vivia sorrindo", "Foi elegante em campo", "É careca", "Chutava muito forte"],
    ["É jovem", "É muito novo"],
    ["Muito rápido", "É veloz", "Corre bastante", "Gosta de driblar", "Gostava de driblar", "Jogava pela ponta"]
  ],

  famosos: [
    ["Canta", "Cantava", "Canta e dança", "Canta há muito tempo", "Tem uma voz forte", "Tinha voz marcante", "Tem voz marcante", "Canta em dupla", "Canta e escreve", "Canta e atua", "Faz música eletrônica", "Ficou famoso dançando"],
    ["Aparece na TV", "Aparecia na TV", "Fala nos jogos", "Saiu de um reality"],
    ["Atua", "Atua há muito tempo", "Já atuou muito"],
    ["Faz filmes", "Do cinema antigo", "Famosa desde nova"],
    ["Faz as pessoas rirem", "Fazia as pessoas rirem"],
    ["Famoso na internet", "Famosa na internet"],
    ["É muito rico", "Mexia com tecnologia", "Muito inteligente"],
    ["Foi ídolo no esporte", "É atleta"]
  ],

  times_europa: [
    ["Muito vencedor", "Já foi dominante", "Domina no país", "Clube rico", "Forte atualmente", "Torcida enorme", "Vence bastante no país"],
    ["Camisa listrada", "Camisa quadriculada"],
    ["Camisa azul", "Camisa azul clara"],
    ["Revela jovens", "Revela brasileiros"],
    ["Torcida fiel", "Torcida quente", "Torcida barulhenta"],
    ["Time discreto", "Já foi mais forte", "Já foi campeão surpresa", "Já surpreendeu no campeonato", "Já jogou a Champions", "Já venceu a Europa"],
    ["Fica em Londres", "Time da capital", "Divide a cidade com um gigante"],
    ["Clube recente", "Clube recente na elite", "Clube pequeno e rico"]
  ],

  times_brasileirao: [
    ["Torcida gigante", "Ganhou títulos recentes", "Revelou craques"],
    ["Time do Sul", "Time do sul"],
    ["Time carioca", "Time carioca tradicional"],
    ["Time da capital", "Time do Centro-Oeste"],
    ["Time do interior", "Time paulista", "Time tradicional de SP"],
    ["Já foi campeão surpresa", "Já foi mais forte", "Vive subindo e caindo", "Cresceu recentemente", "Clube recente"]
  ],

  selecoes: [
    ["Da América do Sul", "Rival histórico do Brasil", "Já foi campeã várias vezes", "Faz divisa com o Brasil", "Joga na altitude", "País pequeno e tradicional"],
    ["Já foi campeã", "Onde o futebol nasceu", "Já foi campeã europeia", "Teve boa geração", "Cor laranja", "Camisa quadriculada"],
    ["Da África", "Surpreendeu na Copa", "Tem muita história"],
    ["Do leste europeu", "País bem novo"],
    ["País bem pequeno", "País pequeno", "Quase nunca vence"],
    ["Da América do Norte", "País bem rico", "Ilha do Caribe", "Da América Central"],
    ["Da Ásia", "Bem distante", "País bem populoso", "Do outro lado do mundo", "Da Oceania", "País fechado"],
    ["Do Oriente Médio", "País do deserto", "Sediou uma Copa", "Fica entre continentes"],
    ["Fala inglês", "Da Europa"],
    ["Ilha do Mediterrâneo", "País bem grande"]
  ],

  comida: [
    ["Comida oriental", "Comida japonesa", "Leva peixe cru"],
    ["Comida mexicana", "Prato espanhol"],
    ["Doce de festa", "Doce de coco", "Doce amarelinho", "Tem em aniversário"],
    ["Doce de festa junina", "Feita de milho", "Doce de milho"],
    ["Sobremesa clássica", "Sobremesa cremosa", "Sobremesa gelada", "Sobremesa que balança", "Tem cobertura de chocolate", "Quente por dentro", "Doce de chocolate"],
    ["Servido gelado", "Bebida gelada"],
    ["Aparece no Natal", "Aparece na Páscoa", "Sobremesa de Natal"],
    ["Feito na brasa", "Bem suculenta", "Assa por horas", "Acompanha churrasco"],
    ["Salgado de festa", "Salgado recheado", "Salgado de padaria", "Salgado meio árabe", "Comprado na feira"],
    ["Doce de rua", "Doce fritinho", "Doce de padaria", "Café da manhã doce", "Massa fininha"],
    ["Lanche rápido", "Lanche de rua", "Lanche simples", "Comida de rua", "Petisco de frango"],
    ["Massa italiana", "Massa recheada", "Vai ao forno"],
    ["Comida do Nordeste", "Prato do Nordeste", "Café da manhã nordestino"],
    ["Prato da Bahia", "Comida de rua baiana"],
    ["Prato pesado", "Prato mineiro", "Prato gaúcho", "Feita na panela grande"],
    ["Bem cremoso", "Leva purê", "Leva queijo derretido"],
    ["Leva peixe", "Petisco de praia", "Comum na praia"],
    ["Servida quente", "Servido quente", "Boa pra quem está doente", "Fica pronto rápido"],
    ["Tem quase todo dia", "Do dia a dia", "Acompanhamento comum", "Comum aos domingos", "Leva ovo", "De padaria"]
  ],

  objetos: [
    ["Fica na cozinha", "Fica no fogão", "Fica na pia", "Fica na gaveta", "Usado na cozinha", "Fica na mesa"],
    ["Faz barulho", "Usada de manhã", "Mantém a temperatura", "Esquenta bastante", "Esquenta o ar", "Fica na área de serviço", "Ilumina a casa", "Dá energia", "Fica na tomada"],
    ["Fica no banheiro", "Item de banheiro"],
    ["Fica no quarto", "Fica na cama", "Fica no guarda-roupa", "Bom no frio", "Bem macio", "Bem macia"],
    ["Fica na sala", "Fica na estante", "Fica na parede", "Fica no chão", "Fica na janela", "Precisa de água"],
    ["Ferramenta comum", "Serve pra medir", "Serve pra subir", "Bem afiada", "Bem reta"],
    ["Material escolar", "Cheio de folhas", "Cheio de páginas", "Bem simples", "Faz contas"],
    ["Serve pra limpar", "Serve pra água"],
    ["Bem pequeno", "Bem pequena", "Cabe no bolso", "Cabe na mão"],
    ["Vai no pé", "Vai na cabeça", "Vai na cintura", "Vai no dedo", "Vai no pescoço", "Fica no rosto", "Fica no pulso", "Fica na orelha", "Serve pro cabelo", "Tem cheiro bom", "Item de maquiagem", "Bem colorido"],
    ["Usado no trabalho", "Cheio de botões", "Quase todo mundo tem", "Registra imagens", "Fica na mão"],
    ["Usado em jogos", "Usada pra brincar", "Faz som", "Tem duas rodas", "Boa pra descansar", "Serve pra ver longe"]
  ],

  profissoes: [
    ["Área da saúde", "Ajuda os doentes", "Cuida de crianças", "Cuida dos olhos", "Estudou muitos anos", "Sabe escutar", "Entende de comida"],
    ["Trabalha com as mãos", "Trabalho minucioso", "Conserta calçados", "Trabalha com madeira", "Trabalha com cuidado", "Cuida das unhas"],
    ["Trabalho criativo", "Trabalha desenhando", "Trabalha escrevendo", "Trabalha com música", "Trabalha com filmes", "Trabalha com imagens"],
    ["Trabalha com a voz", "Trabalha com som", "Aparece em cena", "Aparece bastante", "Faz as pessoas rirem", "Faz truques", "Trabalha com o corpo", "Trabalha à noite"],
    ["Trabalha na rua", "Trabalha dirigindo", "Trabalha viajando", "Anda bastante", "Trabalha voando", "Trabalha no posto"],
    ["Trabalho pesado", "Trabalha com metal", "Fica meio sujo", "Trabalho arriscado"],
    ["Trabalha ao ar livre", "Trabalha no campo", "Trabalha perto da água", "Trabalha na água", "Estuda a natureza", "Fica de olho na água", "Gosta de animais"],
    ["Trabalha com números", "Trabalha com dinheiro", "Trabalha no computador", "Trabalha na internet", "Organiza a agenda", "Toma decisões", "Bom em cálculos", "Trabalha com idiomas", "Estuda o passado", "Trabalha em silêncio", "Vive pesquisando"],
    ["Usa uniforme", "Usa farda", "Usa terno", "Usa toga", "Trabalho sério", "Fica de olho", "Vive investigando", "Fica na entrada"],
    ["Atende as pessoas", "Trabalha numa loja", "Fala com muita gente", "Trabalha em pé"],
    ["Acorda cedo", "Trabalha com doces", "Entende de bebidas"],
    ["Deixa tudo limpo", "Cuida do prédio", "Trabalha num hotel"],
    ["Trabalha com esporte", "Trabalha apitando"]
  ],

  animais: [
    ["Vive no mar", "Vive na água", "Vive em rios", "Vive no fundo", "Anda em cardume", "Nada contra a corrente", "Peixe bem grande", "Parece cobra", "Melhor não encostar", "Anda de lado", "Bem calmo", "Bem enorme"],
    ["Vive perto da água", "Fica na água", "Fica perto da água", "Gosta de água", "Vive perto do mar"],
    ["Vive na fazenda", "Vive no galinheiro", "Acorda cedo", "Parece cavalo", "Carrega peso", "Parece porco", "Aparece no Natal"],
    ["Bem comum em casa", "Pula bastante"],
    ["Bem pesado", "Bem grandão", "Bem forte", "Vive na savana", "Vive em bando", "Caçador solitário", "Corre bastante", "Corre muito rápido", "Corre muito", "Come folhas", "Aguenta o calor"],
    ["Vive na mata", "Tem casco duro", "Tem língua comprida", "Bem lenta", "Tem pernas compridas", "Vive embaixo da terra", "Tem cheiro forte", "Bem diferente", "Rói bastante", "Bem esperta", "Bem esperto"],
    ["Tem penas coloridas", "Tem bico grande", "Tem penas bonitas", "Fica numa perna só", "Nada com elegância", "Canta bastante", "Canta bonito", "Bem pequenininho"],
    ["Voa alto", "Caça do alto", "Voa em círculos", "Bem escuro", "Sai de noite", "Voa em bando", "Vive na cidade"],
    ["Aguenta o frio", "Vive no frio", "Bem peludo"],
    ["Rasteja", "Gosta do sol", "Muda de cor", "Anda devagar"],
    ["Faz teia", "Faz zumbido", "Tem asas coloridas", "Vive em grupo", "Tem ferrão", "Voa por aí", "Brilha no escuro", "Bem pequenininha"],
    ["Sobe em árvores", "Vive em árvores", "Come bambu"]
  ],

  filmes_series: [
    ["Tem vários heróis juntos", "Tem poderes de aranha", "Não tem poderes de verdade", "Vem de outro planeta", "É um vilão famoso", "Tem um super-herói", "Usa uma armadura", "Usa um escudo", "Usa um martelo"],
    ["Se passa no espaço", "Tem magia", "Mexe com a realidade", "Mexe com o tempo", "Tem dinossauros", "Tem robôs"],
    ["Cheio de ação", "É um agente secreto", "Tem muitos carros", "É sobre boxe", "Envolve luta", "Se passa na selva", "Se passa no mar"],
    ["É uma série de comédia", "É de comédia", "É antigo e engraçado"],
    ["É uma novela", "É infantil"],
    ["É um anime", "É um anime antigo"],
    ["É de suspense", "É de terror", "Tem algo sobrenatural", "Tem zumbis", "Segue um assassino", "É investigativo"],
    ["É uma série dramática", "Se passa num hospital", "Se passa numa ilha", "Se passa numa prisão", "Envolve máfia", "Fala de máfia", "Fala da realeza", "Envolve guerreiros antigos", "Envolve advogados", "É uma série coreana", "Tem dragões"],
    ["É um musical", "É uma série de romance", "Conta uma vida inteira", "Baseado em fato real"]
  ],

  marcas: [
    ["Faz celulares", "Faz computadores", "Faz eletrônicos", "É uma empresa de tecnologia", "Faz sistemas operacionais", "Faz processadores", "Faz placas de vídeo"],
    ["É uma rede social", "É de streaming", "É de streaming de música", "É um aplicativo de mensagens", "É de vídeos", "É uma rede social profissional", "Serve pra pedir carro", "Serve pra pedir comida", "É um banco digital", "Vende de tudo online"],
    ["É um refrigerante", "É energético", "É uma cerveja", "É de café"],
    ["Faz vários alimentos", "Faz iogurte", "É um salgadinho", "Faz panetone", "É um creme de avelã", "É um chocolate", "É um chiclete", "É uma bala", "É achocolatado", "Faz frango", "É um biscoito", "É um chocolate colorido"],
    ["Faz tênis", "Faz chinelo", "Vende roupas", "Faz jeans", "Faz óculos", "É de luxo", "Faz relógios", "Tem um jacaré no logo", "Vende roupas esportivas"],
    ["Faz carros", "Faz carros esportivos", "Faz carros de luxo", "Faz carros e motos"],
    ["Vende lanches", "Vende frango frito", "Vende sanduíches", "Vende esfihas", "É um restaurante", "Vende café"],
    ["Vende eletrodomésticos", "Vende de tudo", "É um supermercado", "Faz eletrodomésticos"],
    ["É um videogame", "São blocos de montar", "É uma boneca"],
    ["Faz pasta de dente", "Faz lâminas de barbear", "Faz pilhas"]
  ]

};
